//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.10 at 07:38:55 PM CEST 
//


package es.caib.avaedi.at4forms.front.menuDefinition.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MenuDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MenuDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}TOOLBAR" minOccurs="0"/>
 *         &lt;element ref="{}LINK" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}FORM" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}MENU" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MenuDefinition", propOrder = {
    "toolbarOrLINKOrFORM"
})
public class MenuDefinition {

    @XmlElements({
        @XmlElement(name = "LINK", type = Link.class),
        @XmlElement(name = "MENU", type = Menu.class),
        @XmlElement(name = "FORM", type = Form.class),
        @XmlElement(name = "TOOLBAR", type = Toolbar.class)
    })
    protected List<Object> toolbarOrLINKOrFORM;

    /**
     * Gets the value of the toolbarOrLINKOrFORM property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toolbarOrLINKOrFORM property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTOOLBAROrLINKOrFORM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Link }
     * {@link Menu }
     * {@link Form }
     * {@link Toolbar }
     * 
     * 
     */
    public List<Object> getTOOLBAROrLINKOrFORM() {
        if (toolbarOrLINKOrFORM == null) {
            toolbarOrLINKOrFORM = new ArrayList<Object>();
        }
        return this.toolbarOrLINKOrFORM;
    }

}
