//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.07.10 at 07:38:55 PM CEST
//


package es.caib.avaedi.at4forms.front.menuDefinition.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the menuDefinition.model package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MENU_QNAME = new QName("", "MENU");
    private final static QName _MENUDEFINITION_QNAME = new QName("", "MENUDEFINITION");
    private final static QName _SEARCH_QNAME = new QName("", "SEARCH");
    private final static QName _LINK_QNAME = new QName("", "LINK");
    private final static QName _FORM_QNAME = new QName("", "FORM");
    private final static QName _TOOLBAR_QNAME = new QName("", "TOOLBAR");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: menuDefinition.model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Search }
     *
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link MenuDefinition }
     *
     */
    public MenuDefinition createMenuDefinition() {
        return new MenuDefinition();
    }

    /**
     * Create an instance of {@link Toolbar }
     *
     */
    public Toolbar createToolbar() {
        return new Toolbar();
    }

    /**
     * Create an instance of {@link Menu }
     *
     */
    public Menu createMenu() {
        return new Menu();
    }

    /**
     * Create an instance of {@link Link }
     *
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Form }
     *
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Menu }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MENU")
    public JAXBElement<Menu> createMENU(Menu value) {
        return new JAXBElement<Menu>(_MENU_QNAME, Menu.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MenuDefinition }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "MENUDEFINITION")
    public JAXBElement<MenuDefinition> createMENUDEFINITION(MenuDefinition value) {
        return new JAXBElement<MenuDefinition>(_MENUDEFINITION_QNAME, MenuDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Search }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "SEARCH")
    public JAXBElement<Search> createSEARCH(Search value) {
        return new JAXBElement<Search>(_SEARCH_QNAME, Search.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "LINK")
    public JAXBElement<Link> createLINK(Link value) {
        return new JAXBElement<Link>(_LINK_QNAME, Link.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Form }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "FORM")
    public JAXBElement<Form> createFORM(Form value) {
        return new JAXBElement<Form>(_FORM_QNAME, Form.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Toolbar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "TOOLBAR")
    public JAXBElement<Toolbar> createTOOLBAR(Toolbar value) {
        return new JAXBElement<Toolbar>(_TOOLBAR_QNAME, Toolbar.class, null, value);
    }

}
