//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for bicfi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bicfi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bi" type="{http://www.catastro.meh.es/}bii"/>
 *         &lt;element name="inft" type="{http://www.catastro.meh.es/}infte" minOccurs="0"/>
 *         &lt;element name="mov" type="{http://www.catastro.meh.es/}movi"/>
 *         &lt;element name="lsf" type="{http://www.catastro.meh.es/}lsf" minOccurs="0"/>
 *         &lt;element name="lsi" type="{http://www.catastro.meh.es/}lsi" minOccurs="0"/>
 *         &lt;element name="coordi" type="{http://www.catastro.meh.es/}tcoord" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bicfi", propOrder = { "bi", "inft", "mov", "lsf", "lsi", "coordi" })
public class Bicfi {

	@XmlElement(required = true)
	protected Bii bi;
	protected Infte inft;
	@XmlElement(required = true)
	protected Movi mov;
	protected Lsf lsf;
	protected Lsi lsi;
	protected Tcoord coordi;

	/**
	 * Gets the value of the bi property.
	 * 
	 * @return possible object is {@link Bii }
	 * 
	 */
	public Bii getBi() {
		return bi;
	}

	/**
	 * Sets the value of the bi property.
	 * 
	 * @param value
	 *            allowed object is {@link Bii }
	 * 
	 */
	public void setBi(Bii value) {
		this.bi = value;
	}

	/**
	 * Gets the value of the inft property.
	 * 
	 * @return possible object is {@link Infte }
	 * 
	 */
	public Infte getInft() {
		return inft;
	}

	/**
	 * Sets the value of the inft property.
	 * 
	 * @param value
	 *            allowed object is {@link Infte }
	 * 
	 */
	public void setInft(Infte value) {
		this.inft = value;
	}

	/**
	 * Gets the value of the mov property.
	 * 
	 * @return possible object is {@link Movi }
	 * 
	 */
	public Movi getMov() {
		return mov;
	}

	/**
	 * Sets the value of the mov property.
	 * 
	 * @param value
	 *            allowed object is {@link Movi }
	 * 
	 */
	public void setMov(Movi value) {
		this.mov = value;
	}

	/**
	 * Gets the value of the lsf property.
	 * 
	 * @return possible object is {@link Lsf }
	 * 
	 */
	public Lsf getLsf() {
		return lsf;
	}

	/**
	 * Sets the value of the lsf property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsf }
	 * 
	 */
	public void setLsf(Lsf value) {
		this.lsf = value;
	}

	/**
	 * Gets the value of the lsi property.
	 * 
	 * @return possible object is {@link Lsi }
	 * 
	 */
	public Lsi getLsi() {
		return lsi;
	}

	/**
	 * Sets the value of the lsi property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsi }
	 * 
	 */
	public void setLsi(Lsi value) {
		this.lsi = value;
	}

	/**
	 * Gets the value of the coordi property.
	 * 
	 * @return possible object is {@link Tcoord }
	 * 
	 */
	public Tcoord getCoordi() {
		return coordi;
	}

	/**
	 * Sets the value of the coordi property.
	 * 
	 * @param value
	 *            allowed object is {@link Tcoord }
	 * 
	 */
	public void setCoordi(Tcoord value) {
		this.coordi = value;
	}

}
