//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for bijis complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bijis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bi" type="{http://www.catastro.meh.es/}biis" minOccurs="0"/>
 *         &lt;element name="exp" type="{http://www.catastro.meh.es/}mov" minOccurs="0"/>
 *         &lt;element name="mov" type="{http://www.catastro.meh.es/}mov" minOccurs="0"/>
 *         &lt;element name="lsf" type="{http://www.catastro.meh.es/}lsf" minOccurs="0"/>
 *         &lt;element name="lcbi" type="{http://www.catastro.meh.es/}lcbi" minOccurs="0"/>
 *         &lt;element name="lsi" type="{http://www.catastro.meh.es/}lsi" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bijis", propOrder = { "bi", "exp", "mov", "lsf", "lcbi", "lsi" })
@XmlSeeAlso({ Bijsis.class })
public class Bijis {

	protected Biis bi;
	protected Mov exp;
	protected Mov mov;
	protected Lsf lsf;
	protected Lcbi lcbi;
	protected Lsi lsi;

	/**
	 * Gets the value of the bi property.
	 * 
	 * @return possible object is {@link Biis }
	 * 
	 */
	public Biis getBi() {
		return bi;
	}

	/**
	 * Sets the value of the bi property.
	 * 
	 * @param value
	 *            allowed object is {@link Biis }
	 * 
	 */
	public void setBi(Biis value) {
		this.bi = value;
	}

	/**
	 * Gets the value of the exp property.
	 * 
	 * @return possible object is {@link Mov }
	 * 
	 */
	public Mov getExp() {
		return exp;
	}

	/**
	 * Sets the value of the exp property.
	 * 
	 * @param value
	 *            allowed object is {@link Mov }
	 * 
	 */
	public void setExp(Mov value) {
		this.exp = value;
	}

	/**
	 * Gets the value of the mov property.
	 * 
	 * @return possible object is {@link Mov }
	 * 
	 */
	public Mov getMov() {
		return mov;
	}

	/**
	 * Sets the value of the mov property.
	 * 
	 * @param value
	 *            allowed object is {@link Mov }
	 * 
	 */
	public void setMov(Mov value) {
		this.mov = value;
	}

	/**
	 * Gets the value of the lsf property.
	 * 
	 * @return possible object is {@link Lsf }
	 * 
	 */
	public Lsf getLsf() {
		return lsf;
	}

	/**
	 * Sets the value of the lsf property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsf }
	 * 
	 */
	public void setLsf(Lsf value) {
		this.lsf = value;
	}

	/**
	 * Gets the value of the lcbi property.
	 * 
	 * @return possible object is {@link Lcbi }
	 * 
	 */
	public Lcbi getLcbi() {
		return lcbi;
	}

	/**
	 * Sets the value of the lcbi property.
	 * 
	 * @param value
	 *            allowed object is {@link Lcbi }
	 * 
	 */
	public void setLcbi(Lcbi value) {
		this.lcbi = value;
	}

	/**
	 * Gets the value of the lsi property.
	 * 
	 * @return possible object is {@link Lsi }
	 * 
	 */
	public Lsi getLsi() {
		return lsi;
	}

	/**
	 * Sets the value of the lsi property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsi }
	 * 
	 */
	public void setLsi(Lsi value) {
		this.lsi = value;
	}

}
