//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Indicadores economicos rusticos
 * 
 * <p>
 * Java class for bru complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="bru">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bvc" type="{http://www.catastro.meh.es/}vcat"/>
 *         &lt;element name="bcl" type="{http://www.catastro.meh.es/}cbon"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bru", propOrder = { "bvc", "bcl" })
public class Bru {

	@XmlElement(required = true)
	protected String bvc;
	@XmlElement(required = true)
	protected Cbon bcl;

	/**
	 * Gets the value of the bvc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBvc() {
		return bvc;
	}

	/**
	 * Sets the value of the bvc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBvc(String value) {
		this.bvc = value;
	}

	/**
	 * Gets the value of the bcl property.
	 * 
	 * @return possible object is {@link Cbon }
	 * 
	 */
	public Cbon getBcl() {
		return bcl;
	}

	/**
	 * Sets the value of the bcl property.
	 * 
	 * @param value
	 *            allowed object is {@link Cbon }
	 * 
	 */
	public void setBcl(Cbon value) {
		this.bcl = value;
	}

}
