//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Codigo de entidad generadora
 * 
 * <p>
 * Java class for ceg complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ceg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="engf" type="{http://www.catastro.meh.es/}engf" minOccurs="0"/>
 *           &lt;element name="cde" type="{http://www.catastro.meh.es/}cd" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="rp" type="{http://www.catastro.meh.es/}rp" minOccurs="0"/>
 *           &lt;element name="not" type="{http://www.catastro.meh.es/}nota" minOccurs="0"/>
 *           &lt;element name="cd" type="{http://www.catastro.meh.es/}cd" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ceg", propOrder = { "engf", "cde", "rp", "not", "cd" })
public class Ceg {

	protected Engf engf;
	protected BigInteger cde;
	protected Rp rp;
	protected Nota not;
	protected BigInteger cd;

	/**
	 * Gets the value of the engf property.
	 * 
	 * @return possible object is {@link Engf }
	 * 
	 */
	public Engf getEngf() {
		return engf;
	}

	/**
	 * Sets the value of the engf property.
	 * 
	 * @param value
	 *            allowed object is {@link Engf }
	 * 
	 */
	public void setEngf(Engf value) {
		this.engf = value;
	}

	/**
	 * Gets the value of the cde property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getCde() {
		return cde;
	}

	/**
	 * Sets the value of the cde property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setCde(BigInteger value) {
		this.cde = value;
	}

	/**
	 * Gets the value of the rp property.
	 * 
	 * @return possible object is {@link Rp }
	 * 
	 */
	public Rp getRp() {
		return rp;
	}

	/**
	 * Sets the value of the rp property.
	 * 
	 * @param value
	 *            allowed object is {@link Rp }
	 * 
	 */
	public void setRp(Rp value) {
		this.rp = value;
	}

	/**
	 * Gets the value of the not property.
	 * 
	 * @return possible object is {@link Nota }
	 * 
	 */
	public Nota getNot() {
		return not;
	}

	/**
	 * Sets the value of the not property.
	 * 
	 * @param value
	 *            allowed object is {@link Nota }
	 * 
	 */
	public void setNot(Nota value) {
		this.not = value;
	}

	/**
	 * Gets the value of the cd property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getCd() {
		return cd;
	}

	/**
	 * Sets the value of the cd property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setCd(BigInteger value) {
		this.cd = value;
	}

}
