//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for cfpa.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="cfpa">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CONT"/>
 *     &lt;enumeration value="EV01"/>
 *     &lt;enumeration value="EV03"/>
 *     &lt;enumeration value="EN01"/>
 *     &lt;enumeration value="BAJA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "cfpa")
@XmlEnum
public enum Cfpa {

	CONT("CONT"), @XmlEnumValue("EV01")
	EV_01("EV01"), @XmlEnumValue("EV03")
	EV_03("EV03"), @XmlEnumValue("EN01")
	EN_01("EN01"), BAJA("BAJA");
	private final String value;

	Cfpa(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Cfpa fromValue(String v) {
		for (Cfpa c : Cfpa.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
