//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 01:59:25 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for consulta_municipieror complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="consulta_municipieror">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="control" type="{http://www.catastro.meh.es/}cabrmun"/>
 *         &lt;choice>
 *           &lt;element name="municipiero" type="{http://www.catastro.meh.es/}municipiero"/>
 *           &lt;element name="lerr" type="{http://www.catastro.meh.es/}lerr"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consulta_municipieror", propOrder = { "control", "municipiero", "lerr" })
@XmlRootElement(name = "consulta_municipiero")
public class ConsultaMunicipieror {

	@XmlElement(required = true)
	protected Cabrmun control;
	protected Municipiero municipiero;
	protected Lerr lerr;

	/**
	 * Gets the value of the control property.
	 * 
	 * @return possible object is {@link Cabrmun }
	 * 
	 */
	public Cabrmun getControl() {
		return control;
	}

	/**
	 * Sets the value of the control property.
	 * 
	 * @param value
	 *            allowed object is {@link Cabrmun }
	 * 
	 */
	public void setControl(Cabrmun value) {
		this.control = value;
	}

	/**
	 * Gets the value of the municipiero property.
	 * 
	 * @return possible object is {@link Municipiero }
	 * 
	 */
	public Municipiero getMunicipiero() {
		return municipiero;
	}

	/**
	 * Sets the value of the municipiero property.
	 * 
	 * @param value
	 *            allowed object is {@link Municipiero }
	 * 
	 */
	public void setMunicipiero(Municipiero value) {
		this.municipiero = value;
	}

	/**
	 * Gets the value of the lerr property.
	 * 
	 * @return possible object is {@link Lerr }
	 * 
	 */
	public Lerr getLerr() {
		return lerr;
	}

	/**
	 * Sets the value of the lerr property.
	 * 
	 * @param value
	 *            allowed object is {@link Lerr }
	 * 
	 */
	public void setLerr(Lerr value) {
		this.lerr = value;
	}

}
