//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Construccion
 * 
 * <p>
 * Java class for consi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="consi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idcons" type="{http://www.catastro.meh.es/}idcons" minOccurs="0"/>
 *         &lt;element name="idconscat" type="{http://www.catastro.meh.es/}idconscati" minOccurs="0"/>
 *         &lt;element name="lcd" type="{http://www.catastro.meh.es/}stringnb" minOccurs="0"/>
 *         &lt;element name="dt" type="{http://www.catastro.meh.es/}domi" minOccurs="0"/>
 *         &lt;element name="dte" type="{http://www.catastro.meh.es/}domie" minOccurs="0"/>
 *         &lt;element name="dfcons" type="{http://www.catastro.meh.es/}dfcons" minOccurs="0"/>
 *         &lt;element name="dvcons" type="{http://www.catastro.meh.es/}dvcons" minOccurs="0"/>
 *         &lt;element name="evcons" type="{http://www.catastro.meh.es/}evcons" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consi", propOrder = { "idcons", "idconscat", "lcd", "dt", "dte", "dfcons", "dvcons", "evcons" })
public class Consi {

	protected Idcons idcons;
	protected Idconscati idconscat;
	protected String lcd;
	protected Domi dt;
	protected Domie dte;
	protected Dfcons dfcons;
	protected Dvcons dvcons;
	protected Evcons evcons;

	/**
	 * Gets the value of the idcons property.
	 * 
	 * @return possible object is {@link Idcons }
	 * 
	 */
	public Idcons getIdcons() {
		return idcons;
	}

	/**
	 * Sets the value of the idcons property.
	 * 
	 * @param value
	 *            allowed object is {@link Idcons }
	 * 
	 */
	public void setIdcons(Idcons value) {
		this.idcons = value;
	}

	/**
	 * Gets the value of the idconscat property.
	 * 
	 * @return possible object is {@link Idconscati }
	 * 
	 */
	public Idconscati getIdconscat() {
		return idconscat;
	}

	/**
	 * Sets the value of the idconscat property.
	 * 
	 * @param value
	 *            allowed object is {@link Idconscati }
	 * 
	 */
	public void setIdconscat(Idconscati value) {
		this.idconscat = value;
	}

	/**
	 * Gets the value of the lcd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLcd() {
		return lcd;
	}

	/**
	 * Sets the value of the lcd property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLcd(String value) {
		this.lcd = value;
	}

	/**
	 * Gets the value of the dt property.
	 * 
	 * @return possible object is {@link Domi }
	 * 
	 */
	public Domi getDt() {
		return dt;
	}

	/**
	 * Sets the value of the dt property.
	 * 
	 * @param value
	 *            allowed object is {@link Domi }
	 * 
	 */
	public void setDt(Domi value) {
		this.dt = value;
	}

	/**
	 * Gets the value of the dte property.
	 * 
	 * @return possible object is {@link Domie }
	 * 
	 */
	public Domie getDte() {
		return dte;
	}

	/**
	 * Sets the value of the dte property.
	 * 
	 * @param value
	 *            allowed object is {@link Domie }
	 * 
	 */
	public void setDte(Domie value) {
		this.dte = value;
	}

	/**
	 * Gets the value of the dfcons property.
	 * 
	 * @return possible object is {@link Dfcons }
	 * 
	 */
	public Dfcons getDfcons() {
		return dfcons;
	}

	/**
	 * Sets the value of the dfcons property.
	 * 
	 * @param value
	 *            allowed object is {@link Dfcons }
	 * 
	 */
	public void setDfcons(Dfcons value) {
		this.dfcons = value;
	}

	/**
	 * Gets the value of the dvcons property.
	 * 
	 * @return possible object is {@link Dvcons }
	 * 
	 */
	public Dvcons getDvcons() {
		return dvcons;
	}

	/**
	 * Sets the value of the dvcons property.
	 * 
	 * @param value
	 *            allowed object is {@link Dvcons }
	 * 
	 */
	public void setDvcons(Dvcons value) {
		this.dvcons = value;
	}

	/**
	 * Gets the value of the evcons property.
	 * 
	 * @return possible object is {@link Evcons }
	 * 
	 */
	public Evcons getEvcons() {
		return evcons;
	}

	/**
	 * Sets the value of the evcons property.
	 * 
	 * @param value
	 *            allowed object is {@link Evcons }
	 * 
	 */
	public void setEvcons(Evcons value) {
		this.evcons = value;
	}

}
