//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Derechos
 * 
 * <p>
 * Java class for der complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="der">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cdr" type="{http://www.catastro.meh.es/}cdr"/>
 *         &lt;element name="pct" type="{http://www.catastro.meh.es/}pct"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "der", propOrder = { "cdr", "pct" })
public class Der {

	@XmlElement(required = true)
	protected Cdr cdr;
	@XmlElement(required = true)
	protected String pct;

	/**
	 * Gets the value of the cdr property.
	 * 
	 * @return possible object is {@link Cdr }
	 * 
	 */
	public Cdr getCdr() {
		return cdr;
	}

	/**
	 * Sets the value of the cdr property.
	 * 
	 * @param value
	 *            allowed object is {@link Cdr }
	 * 
	 */
	public void setCdr(Cdr value) {
		this.cdr = value;
	}

	/**
	 * Gets the value of the pct property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPct() {
		return pct;
	}

	/**
	 * Sets the value of the pct property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPct(String value) {
		this.pct = value;
	}

}
