//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Datos fisicos de la construccion
 * 
 * <p>
 * Java class for dfcons complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dfcons">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cuc" type="{http://www.catastro.meh.es/}cuc" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="car" type="{http://www.catastro.meh.es/}car"/>
 *           &lt;element name="modl" type="{http://www.catastro.meh.es/}modl"/>
 *         &lt;/choice>
 *         &lt;element name="cdes" type="{http://www.catastro.meh.es/}cdes" minOccurs="0"/>
 *         &lt;element name="refor" type="{http://www.catastro.meh.es/}refor" minOccurs="0"/>
 *         &lt;element name="aec" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="ili" type="{http://www.catastro.meh.es/}ie" minOccurs="0"/>
 *         &lt;element name="stl" type="{http://www.catastro.meh.es/}supp"/>
 *         &lt;element name="spt" type="{http://www.catastro.meh.es/}supp" minOccurs="0"/>
 *         &lt;element name="sil" type="{http://www.catastro.meh.es/}supp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dfcons", propOrder = { "cuc", "car", "modl", "cdes", "refor", "aec", "ili", "stl", "spt", "sil" })
public class Dfcons {

	protected String cuc;
	protected String car;
	protected Modl modl;
	protected String cdes;
	protected Refor refor;
	@XmlSchemaType(name = "gYear")
	protected XMLGregorianCalendar aec;
	protected Ie ili;
	@XmlElement(required = true)
	protected String stl;
	protected String spt;
	protected String sil;

	/**
	 * Gets the value of the cuc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCuc() {
		return cuc;
	}

	/**
	 * Sets the value of the cuc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCuc(String value) {
		this.cuc = value;
	}

	/**
	 * Gets the value of the car property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCar() {
		return car;
	}

	/**
	 * Sets the value of the car property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCar(String value) {
		this.car = value;
	}

	/**
	 * Gets the value of the modl property.
	 * 
	 * @return possible object is {@link Modl }
	 * 
	 */
	public Modl getModl() {
		return modl;
	}

	/**
	 * Sets the value of the modl property.
	 * 
	 * @param value
	 *            allowed object is {@link Modl }
	 * 
	 */
	public void setModl(Modl value) {
		this.modl = value;
	}

	/**
	 * Gets the value of the cdes property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCdes() {
		return cdes;
	}

	/**
	 * Sets the value of the cdes property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCdes(String value) {
		this.cdes = value;
	}

	/**
	 * Gets the value of the refor property.
	 * 
	 * @return possible object is {@link Refor }
	 * 
	 */
	public Refor getRefor() {
		return refor;
	}

	/**
	 * Sets the value of the refor property.
	 * 
	 * @param value
	 *            allowed object is {@link Refor }
	 * 
	 */
	public void setRefor(Refor value) {
		this.refor = value;
	}

	/**
	 * Gets the value of the aec property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAec() {
		return aec;
	}

	/**
	 * Sets the value of the aec property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAec(XMLGregorianCalendar value) {
		this.aec = value;
	}

	/**
	 * Gets the value of the ili property.
	 * 
	 * @return possible object is {@link Ie }
	 * 
	 */
	public Ie getIli() {
		return ili;
	}

	/**
	 * Sets the value of the ili property.
	 * 
	 * @param value
	 *            allowed object is {@link Ie }
	 * 
	 */
	public void setIli(Ie value) {
		this.ili = value;
	}

	/**
	 * Gets the value of the stl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStl() {
		return stl;
	}

	/**
	 * Sets the value of the stl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStl(String value) {
		this.stl = value;
	}

	/**
	 * Gets the value of the spt property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpt() {
		return spt;
	}

	/**
	 * Sets the value of the spt property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpt(String value) {
		this.spt = value;
	}

	/**
	 * Gets the value of the sil property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSil() {
		return sil;
	}

	/**
	 * Sets the value of the sil property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSil(String value) {
		this.sil = value;
	}

}
