//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Datos fisicos del suelo
 * 
 * <p>
 * Java class for dfsu complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dfsu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fach" type="{http://www.catastro.meh.es/}fach" minOccurs="0"/>
 *         &lt;element name="sup" type="{http://www.catastro.meh.es/}supp" minOccurs="0"/>
 *         &lt;element name="fondo" type="{http://www.catastro.meh.es/}fondo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dfsu", propOrder = { "fach", "sup", "fondo" })
public class Dfsu {

	protected Fach fach;
	protected String sup;
	protected BigInteger fondo;

	/**
	 * Gets the value of the fach property.
	 * 
	 * @return possible object is {@link Fach }
	 * 
	 */
	public Fach getFach() {
		return fach;
	}

	/**
	 * Sets the value of the fach property.
	 * 
	 * @param value
	 *            allowed object is {@link Fach }
	 * 
	 */
	public void setFach(Fach value) {
		this.fach = value;
	}

	/**
	 * Gets the value of the sup property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSup() {
		return sup;
	}

	/**
	 * Sets the value of the sup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSup(String value) {
		this.sup = value;
	}

	/**
	 * Gets the value of the fondo property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getFondo() {
		return fondo;
	}

	/**
	 * Sets the value of the fondo property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setFondo(BigInteger value) {
		this.fondo = value;
	}

}
