//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Datos fisicos de la unidad constructiva
 * 
 * <p>
 * Java class for dfuc complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dfuc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ac" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="iacons" type="{http://www.catastro.meh.es/}iacons" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="so" type="{http://www.catastro.meh.es/}supp" minOccurs="0"/>
 *           &lt;element name="cucm" type="{http://www.catastro.meh.es/}cuc" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="lf" type="{http://www.catastro.meh.es/}lf" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dfuc", propOrder = { "ac", "iacons", "so", "cucm", "lf" })
public class Dfuc {

	@XmlSchemaType(name = "gYear")
	protected XMLGregorianCalendar ac;
	protected String iacons;
	protected String so;
	protected String cucm;
	protected String lf;

	/**
	 * Gets the value of the ac property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAc() {
		return ac;
	}

	/**
	 * Sets the value of the ac property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAc(XMLGregorianCalendar value) {
		this.ac = value;
	}

	/**
	 * Gets the value of the iacons property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIacons() {
		return iacons;
	}

	/**
	 * Sets the value of the iacons property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIacons(String value) {
		this.iacons = value;
	}

	/**
	 * Gets the value of the so property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSo() {
		return so;
	}

	/**
	 * Sets the value of the so property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSo(String value) {
		this.so = value;
	}

	/**
	 * Gets the value of the cucm property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCucm() {
		return cucm;
	}

	/**
	 * Sets the value of the cucm property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCucm(String value) {
		this.cucm = value;
	}

	/**
	 * Gets the value of the lf property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLf() {
		return lf;
	}

	/**
	 * Sets the value of the lf property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLf(String value) {
		this.lf = value;
	}

}
