//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Direccion
 * 
 * <p>
 * Java class for dir complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dir">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cv" type="{http://www.catastro.meh.es/}cv" minOccurs="0"/>
 *         &lt;element name="tv" type="{http://www.catastro.meh.es/}tv"/>
 *         &lt;element name="nv" type="{http://www.catastro.meh.es/}nv"/>
 *         &lt;element name="pnp" type="{http://www.catastro.meh.es/}pnp" minOccurs="0"/>
 *         &lt;element name="plp" type="{http://www.catastro.meh.es/}plp" minOccurs="0"/>
 *         &lt;element name="snp" type="{http://www.catastro.meh.es/}snp" minOccurs="0"/>
 *         &lt;element name="slp" type="{http://www.catastro.meh.es/}slp" minOccurs="0"/>
 *         &lt;element name="km" type="{http://www.catastro.meh.es/}km" minOccurs="0"/>
 *         &lt;element name="td" type="{http://www.catastro.meh.es/}dne" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dir", propOrder = { "cv", "tv", "nv", "pnp", "plp", "snp", "slp", "km", "td" })
public class Dir {

	protected String cv;
	@XmlElement(required = true)
	protected String tv;
	@XmlElement(required = true)
	protected String nv;
	protected String pnp;
	protected String plp;
	protected String snp;
	protected String slp;
	protected String km;
	protected String td;

	/**
	 * Gets the value of the cv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCv() {
		return cv;
	}

	/**
	 * Sets the value of the cv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCv(String value) {
		this.cv = value;
	}

	/**
	 * Gets the value of the tv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTv() {
		return tv;
	}

	/**
	 * Sets the value of the tv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTv(String value) {
		this.tv = value;
	}

	/**
	 * Gets the value of the nv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNv() {
		return nv;
	}

	/**
	 * Sets the value of the nv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNv(String value) {
		this.nv = value;
	}

	/**
	 * Gets the value of the pnp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPnp() {
		return pnp;
	}

	/**
	 * Sets the value of the pnp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPnp(String value) {
		this.pnp = value;
	}

	/**
	 * Gets the value of the plp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPlp() {
		return plp;
	}

	/**
	 * Sets the value of the plp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPlp(String value) {
		this.plp = value;
	}

	/**
	 * Gets the value of the snp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSnp() {
		return snp;
	}

	/**
	 * Sets the value of the snp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSnp(String value) {
		this.snp = value;
	}

	/**
	 * Gets the value of the slp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSlp() {
		return slp;
	}

	/**
	 * Sets the value of the slp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSlp(String value) {
		this.slp = value;
	}

	/**
	 * Gets the value of the km property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getKm() {
		return km;
	}

	/**
	 * Sets the value of the km property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setKm(String value) {
		this.km = value;
	}

	/**
	 * Gets the value of the td property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTd() {
		return td;
	}

	/**
	 * Sets the value of the td property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTd(String value) {
		this.td = value;
	}

}
