//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:00:57 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for dsa complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dsa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="den" type="{http://www.catastro.meh.es/}denr"/>
 *         &lt;element name="lbi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dbi" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="bir" type="{http://www.catastro.meh.es/}bir" minOccurs="0"/>
 *                             &lt;element name="ltit" type="{http://www.catastro.meh.es/}ltit" minOccurs="0"/>
 *                             &lt;element name="finca" type="{http://www.catastro.meh.es/}fincared" minOccurs="0"/>
 *                             &lt;element name="lcons" type="{http://www.catastro.meh.es/}lconsr" minOccurs="0"/>
 *                             &lt;element name="lspr" type="{http://www.catastro.meh.es/}lspr" minOccurs="0"/>
 *                             &lt;element name="err" type="{http://www.catastro.meh.es/}err" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dsa", propOrder = { "den", "lbi" })
public class Dsa {

	@XmlElement(required = true)
	protected Denr den;
	@XmlElement(required = true)
	protected Dsa.Lbi lbi;

	/**
	 * Gets the value of the den property.
	 * 
	 * @return possible object is {@link Denr }
	 * 
	 */
	public Denr getDen() {
		return den;
	}

	/**
	 * Sets the value of the den property.
	 * 
	 * @param value
	 *            allowed object is {@link Denr }
	 * 
	 */
	public void setDen(Denr value) {
		this.den = value;
	}

	/**
	 * Gets the value of the lbi property.
	 * 
	 * @return possible object is {@link Dsa.Lbi }
	 * 
	 */
	public Dsa.Lbi getLbi() {
		return lbi;
	}

	/**
	 * Sets the value of the lbi property.
	 * 
	 * @param value
	 *            allowed object is {@link Dsa.Lbi }
	 * 
	 */
	public void setLbi(Dsa.Lbi value) {
		this.lbi = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="dbi" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="bir" type="{http://www.catastro.meh.es/}bir" minOccurs="0"/>
	 *                   &lt;element name="ltit" type="{http://www.catastro.meh.es/}ltit" minOccurs="0"/>
	 *                   &lt;element name="finca" type="{http://www.catastro.meh.es/}fincared" minOccurs="0"/>
	 *                   &lt;element name="lcons" type="{http://www.catastro.meh.es/}lconsr" minOccurs="0"/>
	 *                   &lt;element name="lspr" type="{http://www.catastro.meh.es/}lspr" minOccurs="0"/>
	 *                   &lt;element name="err" type="{http://www.catastro.meh.es/}err" minOccurs="0"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "dbi" })
	public static class Lbi {

		@XmlElement(required = true)
		protected List<Dsa.Lbi.Dbi> dbi;

		/**
		 * Gets the value of the dbi property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the dbi property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getDbi().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Dsa.Lbi.Dbi }
		 * 
		 * 
		 */
		public List<Dsa.Lbi.Dbi> getDbi() {
			if (dbi == null) {
				dbi = new ArrayList<Dsa.Lbi.Dbi>();
			}
			return this.dbi;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="bir" type="{http://www.catastro.meh.es/}bir" minOccurs="0"/>
		 *         &lt;element name="ltit" type="{http://www.catastro.meh.es/}ltit" minOccurs="0"/>
		 *         &lt;element name="finca" type="{http://www.catastro.meh.es/}fincared" minOccurs="0"/>
		 *         &lt;element name="lcons" type="{http://www.catastro.meh.es/}lconsr" minOccurs="0"/>
		 *         &lt;element name="lspr" type="{http://www.catastro.meh.es/}lspr" minOccurs="0"/>
		 *         &lt;element name="err" type="{http://www.catastro.meh.es/}err" minOccurs="0"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "bir", "ltit", "finca", "lcons", "lspr", "err" })
		public static class Dbi {

			protected Bir bir;
			protected Ltit ltit;
			protected Fincared finca;
			protected Lconsr lcons;
			protected Lspr lspr;
			protected Err err;

			/**
			 * Gets the value of the bir property.
			 * 
			 * @return possible object is {@link Bir }
			 * 
			 */
			public Bir getBir() {
				return bir;
			}

			/**
			 * Sets the value of the bir property.
			 * 
			 * @param value
			 *            allowed object is {@link Bir }
			 * 
			 */
			public void setBir(Bir value) {
				this.bir = value;
			}

			/**
			 * Gets the value of the ltit property.
			 * 
			 * @return possible object is {@link Ltit }
			 * 
			 */
			public Ltit getLtit() {
				return ltit;
			}

			/**
			 * Sets the value of the ltit property.
			 * 
			 * @param value
			 *            allowed object is {@link Ltit }
			 * 
			 */
			public void setLtit(Ltit value) {
				this.ltit = value;
			}

			/**
			 * Gets the value of the finca property.
			 * 
			 * @return possible object is {@link Fincared }
			 * 
			 */
			public Fincared getFinca() {
				return finca;
			}

			/**
			 * Sets the value of the finca property.
			 * 
			 * @param value
			 *            allowed object is {@link Fincared }
			 * 
			 */
			public void setFinca(Fincared value) {
				this.finca = value;
			}

			/**
			 * Gets the value of the lcons property.
			 * 
			 * @return possible object is {@link Lconsr }
			 * 
			 */
			public Lconsr getLcons() {
				return lcons;
			}

			/**
			 * Sets the value of the lcons property.
			 * 
			 * @param value
			 *            allowed object is {@link Lconsr }
			 * 
			 */
			public void setLcons(Lconsr value) {
				this.lcons = value;
			}

			/**
			 * Gets the value of the lspr property.
			 * 
			 * @return possible object is {@link Lspr }
			 * 
			 */
			public Lspr getLspr() {
				return lspr;
			}

			/**
			 * Sets the value of the lspr property.
			 * 
			 * @param value
			 *            allowed object is {@link Lspr }
			 * 
			 */
			public void setLspr(Lspr value) {
				this.lspr = value;
			}

			/**
			 * Gets the value of the err property.
			 * 
			 * @return possible object is {@link Err }
			 * 
			 */
			public Err getErr() {
				return err;
			}

			/**
			 * Sets the value of the err property.
			 * 
			 * @param value
			 *            allowed object is {@link Err }
			 * 
			 */
			public void setErr(Err value) {
				this.err = value;
			}

		}

	}

}
