//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 01:59:03 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Domicilio tributario
 * 
 * <p>
 * Java class for dtdnp complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dtdnp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.catastro.meh.es/}dt">
 *       &lt;sequence>
 *         &lt;element name="loine" type="{http://www.catastro.meh.es/}loine"/>
 *         &lt;element name="cmc" type="{http://www.catastro.meh.es/}cmc"/>
 *         &lt;element name="np" type="{http://www.catastro.meh.es/}np"/>
 *         &lt;element name="nm" type="{http://www.catastro.meh.es/}nm"/>
 *         &lt;element name="nem" type="{http://www.catastro.meh.es/}nem" minOccurs="0"/>
 *         &lt;element name="locs" type="{http://www.catastro.meh.es/}locsdnp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dtdnp")
public class Dtdnp extends Dt {

}
