//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for elemsf complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="elemsf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fincacs" type="{http://www.catastro.meh.es/}fincacs" minOccurs="0"/>
 *         &lt;element name="lsuelocs" type="{http://www.catastro.meh.es/}lsuelocs" minOccurs="0"/>
 *         &lt;element name="luccs" type="{http://www.catastro.meh.es/}luccs" minOccurs="0"/>
 *         &lt;element name="lbics" type="{http://www.catastro.meh.es/}lbics" minOccurs="0"/>
 *         &lt;element name="lconscs" type="{http://www.catastro.meh.es/}lconscs" minOccurs="0"/>
 *         &lt;element name="lsprcs" type="{http://www.catastro.meh.es/}lsprcs" minOccurs="0"/>
 *         &lt;element name="lreparcs" type="{http://www.catastro.meh.es/}lreparcs" minOccurs="0"/>
 *         &lt;element name="fxcc" type="{http://www.catastro.meh.es/}fxcc" minOccurs="0"/>
 *         &lt;element name="limg" type="{http://www.catastro.meh.es/}limg" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elemsf", propOrder = { "fincacs", "lsuelocs", "luccs", "lbics", "lconscs", "lsprcs", "lreparcs", "fxcc", "limg" })
public class Elemsf {

	protected Fincacs fincacs;
	protected Lsuelocs lsuelocs;
	protected Luccs luccs;
	protected Lbics lbics;
	protected Lconscs lconscs;
	protected Lsprcs lsprcs;
	protected Lreparcs lreparcs;
	protected Fxcc fxcc;
	protected Limg limg;

	/**
	 * Gets the value of the fincacs property.
	 * 
	 * @return possible object is {@link Fincacs }
	 * 
	 */
	public Fincacs getFincacs() {
		return fincacs;
	}

	/**
	 * Sets the value of the fincacs property.
	 * 
	 * @param value
	 *            allowed object is {@link Fincacs }
	 * 
	 */
	public void setFincacs(Fincacs value) {
		this.fincacs = value;
	}

	/**
	 * Gets the value of the lsuelocs property.
	 * 
	 * @return possible object is {@link Lsuelocs }
	 * 
	 */
	public Lsuelocs getLsuelocs() {
		return lsuelocs;
	}

	/**
	 * Sets the value of the lsuelocs property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsuelocs }
	 * 
	 */
	public void setLsuelocs(Lsuelocs value) {
		this.lsuelocs = value;
	}

	/**
	 * Gets the value of the luccs property.
	 * 
	 * @return possible object is {@link Luccs }
	 * 
	 */
	public Luccs getLuccs() {
		return luccs;
	}

	/**
	 * Sets the value of the luccs property.
	 * 
	 * @param value
	 *            allowed object is {@link Luccs }
	 * 
	 */
	public void setLuccs(Luccs value) {
		this.luccs = value;
	}

	/**
	 * Gets the value of the lbics property.
	 * 
	 * @return possible object is {@link Lbics }
	 * 
	 */
	public Lbics getLbics() {
		return lbics;
	}

	/**
	 * Sets the value of the lbics property.
	 * 
	 * @param value
	 *            allowed object is {@link Lbics }
	 * 
	 */
	public void setLbics(Lbics value) {
		this.lbics = value;
	}

	/**
	 * Gets the value of the lconscs property.
	 * 
	 * @return possible object is {@link Lconscs }
	 * 
	 */
	public Lconscs getLconscs() {
		return lconscs;
	}

	/**
	 * Sets the value of the lconscs property.
	 * 
	 * @param value
	 *            allowed object is {@link Lconscs }
	 * 
	 */
	public void setLconscs(Lconscs value) {
		this.lconscs = value;
	}

	/**
	 * Gets the value of the lsprcs property.
	 * 
	 * @return possible object is {@link Lsprcs }
	 * 
	 */
	public Lsprcs getLsprcs() {
		return lsprcs;
	}

	/**
	 * Sets the value of the lsprcs property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsprcs }
	 * 
	 */
	public void setLsprcs(Lsprcs value) {
		this.lsprcs = value;
	}

	/**
	 * Gets the value of the lreparcs property.
	 * 
	 * @return possible object is {@link Lreparcs }
	 * 
	 */
	public Lreparcs getLreparcs() {
		return lreparcs;
	}

	/**
	 * Sets the value of the lreparcs property.
	 * 
	 * @param value
	 *            allowed object is {@link Lreparcs }
	 * 
	 */
	public void setLreparcs(Lreparcs value) {
		this.lreparcs = value;
	}

	/**
	 * Gets the value of the fxcc property.
	 * 
	 * @return possible object is {@link Fxcc }
	 * 
	 */
	public Fxcc getFxcc() {
		return fxcc;
	}

	/**
	 * Sets the value of the fxcc property.
	 * 
	 * @param value
	 *            allowed object is {@link Fxcc }
	 * 
	 */
	public void setFxcc(Fxcc value) {
		this.fxcc = value;
	}

	/**
	 * Gets the value of the limg property.
	 * 
	 * @return possible object is {@link Limg }
	 * 
	 */
	public Limg getLimg() {
		return limg;
	}

	/**
	 * Sets the value of the limg property.
	 * 
	 * @param value
	 *            allowed object is {@link Limg }
	 * 
	 */
	public void setLimg(Limg value) {
		this.limg = value;
	}

}
