//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for elemvi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="elemvi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fincacev" type="{http://www.catastro.meh.es/}fincace" minOccurs="0"/>
 *         &lt;element name="lsuelov" type="{http://www.catastro.meh.es/}lsuelocev" minOccurs="0"/>
 *         &lt;element name="lucv" type="{http://www.catastro.meh.es/}luccev" minOccurs="0"/>
 *         &lt;element name="lbicenv" type="{http://www.catastro.meh.es/}lbicenvi" minOccurs="0"/>
 *         &lt;element name="lconsv" type="{http://www.catastro.meh.es/}lconscev" minOccurs="0"/>
 *         &lt;element name="lsprv" type="{http://www.catastro.meh.es/}lsprcev" minOccurs="0"/>
 *         &lt;element name="lreparv" type="{http://www.catastro.meh.es/}lreparcev" minOccurs="0"/>
 *         &lt;element name="fxcc" type="{http://www.catastro.meh.es/}fxcc" minOccurs="0"/>
 *         &lt;element name="limg" type="{http://www.catastro.meh.es/}limg" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elemvi", propOrder = { "fincacev", "lsuelov", "lucv", "lbicenv", "lconsv", "lsprv", "lreparv", "fxcc", "limg" })
public class Elemvi {

	protected Fincace fincacev;
	protected Lsuelocev lsuelov;
	protected Luccev lucv;
	protected Lbicenvi lbicenv;
	protected Lconscev lconsv;
	protected Lsprcev lsprv;
	protected Lreparcev lreparv;
	protected Fxcc fxcc;
	protected Limg limg;

	/**
	 * Gets the value of the fincacev property.
	 * 
	 * @return possible object is {@link Fincace }
	 * 
	 */
	public Fincace getFincacev() {
		return fincacev;
	}

	/**
	 * Sets the value of the fincacev property.
	 * 
	 * @param value
	 *            allowed object is {@link Fincace }
	 * 
	 */
	public void setFincacev(Fincace value) {
		this.fincacev = value;
	}

	/**
	 * Gets the value of the lsuelov property.
	 * 
	 * @return possible object is {@link Lsuelocev }
	 * 
	 */
	public Lsuelocev getLsuelov() {
		return lsuelov;
	}

	/**
	 * Sets the value of the lsuelov property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsuelocev }
	 * 
	 */
	public void setLsuelov(Lsuelocev value) {
		this.lsuelov = value;
	}

	/**
	 * Gets the value of the lucv property.
	 * 
	 * @return possible object is {@link Luccev }
	 * 
	 */
	public Luccev getLucv() {
		return lucv;
	}

	/**
	 * Sets the value of the lucv property.
	 * 
	 * @param value
	 *            allowed object is {@link Luccev }
	 * 
	 */
	public void setLucv(Luccev value) {
		this.lucv = value;
	}

	/**
	 * Gets the value of the lbicenv property.
	 * 
	 * @return possible object is {@link Lbicenvi }
	 * 
	 */
	public Lbicenvi getLbicenv() {
		return lbicenv;
	}

	/**
	 * Sets the value of the lbicenv property.
	 * 
	 * @param value
	 *            allowed object is {@link Lbicenvi }
	 * 
	 */
	public void setLbicenv(Lbicenvi value) {
		this.lbicenv = value;
	}

	/**
	 * Gets the value of the lconsv property.
	 * 
	 * @return possible object is {@link Lconscev }
	 * 
	 */
	public Lconscev getLconsv() {
		return lconsv;
	}

	/**
	 * Sets the value of the lconsv property.
	 * 
	 * @param value
	 *            allowed object is {@link Lconscev }
	 * 
	 */
	public void setLconsv(Lconscev value) {
		this.lconsv = value;
	}

	/**
	 * Gets the value of the lsprv property.
	 * 
	 * @return possible object is {@link Lsprcev }
	 * 
	 */
	public Lsprcev getLsprv() {
		return lsprv;
	}

	/**
	 * Sets the value of the lsprv property.
	 * 
	 * @param value
	 *            allowed object is {@link Lsprcev }
	 * 
	 */
	public void setLsprv(Lsprcev value) {
		this.lsprv = value;
	}

	/**
	 * Gets the value of the lreparv property.
	 * 
	 * @return possible object is {@link Lreparcev }
	 * 
	 */
	public Lreparcev getLreparv() {
		return lreparv;
	}

	/**
	 * Sets the value of the lreparv property.
	 * 
	 * @param value
	 *            allowed object is {@link Lreparcev }
	 * 
	 */
	public void setLreparv(Lreparcev value) {
		this.lreparv = value;
	}

	/**
	 * Gets the value of the fxcc property.
	 * 
	 * @return possible object is {@link Fxcc }
	 * 
	 */
	public Fxcc getFxcc() {
		return fxcc;
	}

	/**
	 * Sets the value of the fxcc property.
	 * 
	 * @param value
	 *            allowed object is {@link Fxcc }
	 * 
	 */
	public void setFxcc(Fxcc value) {
		this.fxcc = value;
	}

	/**
	 * Gets the value of the limg property.
	 * 
	 * @return possible object is {@link Limg }
	 * 
	 */
	public Limg getLimg() {
		return limg;
	}

	/**
	 * Sets the value of the limg property.
	 * 
	 * @param value
	 *            allowed object is {@link Limg }
	 * 
	 */
	public void setLimg(Limg value) {
		this.limg = value;
	}

}
