//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Explicacion de la valoracion del bien inmueble
 * 
 * <p>
 * Java class for evbi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="evbi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="duso" type="{http://www.catastro.meh.es/}desc" minOccurs="0"/>
 *         &lt;element name="vcsa" type="{http://www.catastro.meh.es/}vcat" minOccurs="0"/>
 *         &lt;element name="vcsrc" type="{http://www.catastro.meh.es/}vcat" minOccurs="0"/>
 *         &lt;element name="ired" type="{http://www.catastro.meh.es/}vcat" minOccurs="0"/>
 *         &lt;element name="uared" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="avsa" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="ivcm" type="{http://www.catastro.meh.es/}ia" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evbi", propOrder = { "duso", "vcsa", "vcsrc", "ired", "uared", "avsa", "ivcm" })
public class Evbi {

	protected String duso;
	protected String vcsa;
	protected String vcsrc;
	protected String ired;
	@XmlSchemaType(name = "gYear")
	protected XMLGregorianCalendar uared;
	@XmlSchemaType(name = "gYear")
	protected XMLGregorianCalendar avsa;
	protected Ia ivcm;

	/**
	 * Gets the value of the duso property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDuso() {
		return duso;
	}

	/**
	 * Sets the value of the duso property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDuso(String value) {
		this.duso = value;
	}

	/**
	 * Gets the value of the vcsa property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVcsa() {
		return vcsa;
	}

	/**
	 * Sets the value of the vcsa property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVcsa(String value) {
		this.vcsa = value;
	}

	/**
	 * Gets the value of the vcsrc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVcsrc() {
		return vcsrc;
	}

	/**
	 * Sets the value of the vcsrc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVcsrc(String value) {
		this.vcsrc = value;
	}

	/**
	 * Gets the value of the ired property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIred() {
		return ired;
	}

	/**
	 * Sets the value of the ired property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIred(String value) {
		this.ired = value;
	}

	/**
	 * Gets the value of the uared property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getUared() {
		return uared;
	}

	/**
	 * Sets the value of the uared property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setUared(XMLGregorianCalendar value) {
		this.uared = value;
	}

	/**
	 * Gets the value of the avsa property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAvsa() {
		return avsa;
	}

	/**
	 * Sets the value of the avsa property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAvsa(XMLGregorianCalendar value) {
		this.avsa = value;
	}

	/**
	 * Gets the value of the ivcm property.
	 * 
	 * @return possible object is {@link Ia }
	 * 
	 */
	public Ia getIvcm() {
		return ivcm;
	}

	/**
	 * Sets the value of the ivcm property.
	 * 
	 * @param value
	 *            allowed object is {@link Ia }
	 * 
	 */
	public void setIvcm(Ia value) {
		this.ivcm = value;
	}

}
