//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Explicacion de la valoracion de la finca
 * 
 * <p>
 * Java class for evf complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="evf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mbc" type="{http://www.catastro.meh.es/}imb1" minOccurs="0"/>
 *         &lt;element name="mbrs" type="{http://www.catastro.meh.es/}imb1" minOccurs="0"/>
 *         &lt;element name="mbcci" type="{http://www.catastro.meh.es/}imb1" minOccurs="0"/>
 *         &lt;element name="mbrcni" type="{http://www.catastro.meh.es/}imb1" minOccurs="0"/>
 *         &lt;element name="mbrci" type="{http://www.catastro.meh.es/}imb1" minOccurs="0"/>
 *         &lt;element name="vuzc" type="{http://www.catastro.meh.es/}vur" minOccurs="0"/>
 *         &lt;element name="vup" type="{http://www.catastro.meh.es/}vur" minOccurs="0"/>
 *         &lt;element name="vrp" type="{http://www.catastro.meh.es/}vur" minOccurs="0"/>
 *         &lt;element name="gb" type="{http://www.catastro.meh.es/}gb" minOccurs="0"/>
 *         &lt;element name="nbop" type="{http://www.catastro.meh.es/}nbo" minOccurs="0"/>
 *         &lt;element name="fbop" type="{http://www.catastro.meh.es/}fecha" minOccurs="0"/>
 *         &lt;element name="nbovm" type="{http://www.catastro.meh.es/}nbo" minOccurs="0"/>
 *         &lt;element name="fbovm" type="{http://www.catastro.meh.es/}fecha" minOccurs="0"/>
 *         &lt;element name="aantv" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="gntv" type="{http://www.catastro.meh.es/}gntv" minOccurs="0"/>
 *         &lt;element name="fboom" type="{http://www.catastro.meh.es/}fecha" minOccurs="0"/>
 *         &lt;element name="nboom" type="{http://www.catastro.meh.es/}nbo" minOccurs="0"/>
 *         &lt;element name="cicir" type="{http://www.catastro.meh.es/}cicir" minOccurs="0"/>
 *         &lt;element name="mbpe" type="{http://www.catastro.meh.es/}imb2" minOccurs="0"/>
 *         &lt;element name="mbpg" type="{http://www.catastro.meh.es/}imb2" minOccurs="0"/>
 *         &lt;element name="mbpr" type="{http://www.catastro.meh.es/}imb2" minOccurs="0"/>
 *         &lt;element name="mcua" type="{http://www.catastro.meh.es/}imb2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evf", propOrder = { "mbc", "mbrs", "mbcci", "mbrcni", "mbrci", "vuzc", "vup", "vrp", "gb", "nbop", "fbop", "nbovm", "fbovm", "aantv", "gntv", "fboom", "nboom", "cicir", "mbpe", "mbpg", "mbpr", "mcua" })
public class Evf {

	protected String mbc;
	protected String mbrs;
	protected String mbcci;
	protected String mbrcni;
	protected String mbrci;
	protected String vuzc;
	protected String vup;
	protected String vrp;
	protected String gb;
	protected BigInteger nbop;
	protected XMLGregorianCalendar fbop;
	protected BigInteger nbovm;
	protected XMLGregorianCalendar fbovm;
	@XmlSchemaType(name = "gYear")
	protected XMLGregorianCalendar aantv;
	protected String gntv;
	protected XMLGregorianCalendar fboom;
	protected BigInteger nboom;
	protected String cicir;
	protected String mbpe;
	protected String mbpg;
	protected String mbpr;
	protected String mcua;

	/**
	 * Gets the value of the mbc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbc() {
		return mbc;
	}

	/**
	 * Sets the value of the mbc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbc(String value) {
		this.mbc = value;
	}

	/**
	 * Gets the value of the mbrs property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbrs() {
		return mbrs;
	}

	/**
	 * Sets the value of the mbrs property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbrs(String value) {
		this.mbrs = value;
	}

	/**
	 * Gets the value of the mbcci property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbcci() {
		return mbcci;
	}

	/**
	 * Sets the value of the mbcci property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbcci(String value) {
		this.mbcci = value;
	}

	/**
	 * Gets the value of the mbrcni property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbrcni() {
		return mbrcni;
	}

	/**
	 * Sets the value of the mbrcni property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbrcni(String value) {
		this.mbrcni = value;
	}

	/**
	 * Gets the value of the mbrci property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbrci() {
		return mbrci;
	}

	/**
	 * Sets the value of the mbrci property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbrci(String value) {
		this.mbrci = value;
	}

	/**
	 * Gets the value of the vuzc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVuzc() {
		return vuzc;
	}

	/**
	 * Sets the value of the vuzc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVuzc(String value) {
		this.vuzc = value;
	}

	/**
	 * Gets the value of the vup property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVup() {
		return vup;
	}

	/**
	 * Sets the value of the vup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVup(String value) {
		this.vup = value;
	}

	/**
	 * Gets the value of the vrp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVrp() {
		return vrp;
	}

	/**
	 * Sets the value of the vrp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVrp(String value) {
		this.vrp = value;
	}

	/**
	 * Gets the value of the gb property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGb() {
		return gb;
	}

	/**
	 * Sets the value of the gb property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGb(String value) {
		this.gb = value;
	}

	/**
	 * Gets the value of the nbop property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNbop() {
		return nbop;
	}

	/**
	 * Sets the value of the nbop property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNbop(BigInteger value) {
		this.nbop = value;
	}

	/**
	 * Gets the value of the fbop property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFbop() {
		return fbop;
	}

	/**
	 * Sets the value of the fbop property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFbop(XMLGregorianCalendar value) {
		this.fbop = value;
	}

	/**
	 * Gets the value of the nbovm property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNbovm() {
		return nbovm;
	}

	/**
	 * Sets the value of the nbovm property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNbovm(BigInteger value) {
		this.nbovm = value;
	}

	/**
	 * Gets the value of the fbovm property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFbovm() {
		return fbovm;
	}

	/**
	 * Sets the value of the fbovm property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFbovm(XMLGregorianCalendar value) {
		this.fbovm = value;
	}

	/**
	 * Gets the value of the aantv property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getAantv() {
		return aantv;
	}

	/**
	 * Sets the value of the aantv property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setAantv(XMLGregorianCalendar value) {
		this.aantv = value;
	}

	/**
	 * Gets the value of the gntv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGntv() {
		return gntv;
	}

	/**
	 * Sets the value of the gntv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGntv(String value) {
		this.gntv = value;
	}

	/**
	 * Gets the value of the fboom property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFboom() {
		return fboom;
	}

	/**
	 * Sets the value of the fboom property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFboom(XMLGregorianCalendar value) {
		this.fboom = value;
	}

	/**
	 * Gets the value of the nboom property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNboom() {
		return nboom;
	}

	/**
	 * Sets the value of the nboom property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNboom(BigInteger value) {
		this.nboom = value;
	}

	/**
	 * Gets the value of the cicir property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCicir() {
		return cicir;
	}

	/**
	 * Sets the value of the cicir property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCicir(String value) {
		this.cicir = value;
	}

	/**
	 * Gets the value of the mbpe property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbpe() {
		return mbpe;
	}

	/**
	 * Sets the value of the mbpe property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbpe(String value) {
		this.mbpe = value;
	}

	/**
	 * Gets the value of the mbpg property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbpg() {
		return mbpg;
	}

	/**
	 * Sets the value of the mbpg property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbpg(String value) {
		this.mbpg = value;
	}

	/**
	 * Gets the value of the mbpr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMbpr() {
		return mbpr;
	}

	/**
	 * Sets the value of the mbpr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMbpr(String value) {
		this.mbpr = value;
	}

	/**
	 * Gets the value of the mcua property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMcua() {
		return mcua;
	}

	/**
	 * Sets the value of the mcua property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMcua(String value) {
		this.mcua = value;
	}

}
