//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tipo de fachada
 * 
 * <p>
 * Java class for fach complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fach">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="long" type="{http://www.catastro.meh.es/}lf" minOccurs="0"/>
 *         &lt;element name="tipof" type="{http://www.catastro.meh.es/}tipof"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fach", propOrder = { "_long", "tipof" })
public class Fach {

	@XmlElement(name = "long")
	protected String _long;
	@XmlElement(required = true)
	protected Tipof tipof;

	/**
	 * Gets the value of the long property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLong() {
		return _long;
	}

	/**
	 * Sets the value of the long property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLong(String value) {
		this._long = value;
	}

	/**
	 * Gets the value of the tipof property.
	 * 
	 * @return possible object is {@link Tipof }
	 * 
	 */
	public Tipof getTipof() {
		return tipof;
	}

	/**
	 * Sets the value of the tipof property.
	 * 
	 * @param value
	 *            allowed object is {@link Tipof }
	 * 
	 */
	public void setTipof(Tipof value) {
		this.tipof = value;
	}

}
