//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fincac complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fincac">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element name="fincaeam" type="{http://www.catastro.meh.es/}finca"/>
 *             &lt;element name="movam" type="{http://www.catastro.meh.es/}movami"/>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element name="fincaeb" type="{http://www.catastro.meh.es/}finca"/>
 *             &lt;element name="movb" type="{http://www.catastro.meh.es/}movb"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="fincas" type="{http://www.catastro.meh.es/}finca"/>
 *           &lt;element name="exp" type="{http://www.catastro.meh.es/}mov"/>
 *           &lt;element name="tmovb" type="{http://www.catastro.meh.es/}tmovb" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="fincaf" type="{http://www.catastro.meh.es/}finca"/>
 *           &lt;element name="movf" type="{http://www.catastro.meh.es/}movf"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="fincafb" type="{http://www.catastro.meh.es/}finca"/>
 *           &lt;element name="movb" type="{http://www.catastro.meh.es/}movb"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fincac", propOrder = { "content" })
public class Fincac {

	@XmlElementRefs({ @XmlElementRef(name = "fincaeb", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "tmovb", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "movam", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "fincaf", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "movb", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "exp", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "fincaeam", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "movf", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "fincafb", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false), @XmlElementRef(name = "fincas", namespace = "http://www.catastro.meh.es/", type = JAXBElement.class, required = false) })
	protected List<JAXBElement<?>> content;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following
	 * reason: The field name "Movb" is used by two different parts of a schema.
	 * See: line 8185 of
	 * file:/D:/PROGRAMACION/at4/workspaces/generalLuna/SoapTest/src/xsd/ldc.xsd
	 * line 8171 of
	 * file:/D:/PROGRAMACION/at4/workspaces/generalLuna/SoapTest/src/xsd/ldc.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one of
	 * both of the following declarations to change their names: Gets the value
	 * of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link Finca }{@code >} {@link JAXBElement }
	 * {@code <}{@link Tmovb }{@code >} {@link JAXBElement }{@code <}
	 * {@link Movami }{@code >} {@link JAXBElement }{@code <}{@link Movb }{@code >}
	 * {@link JAXBElement }{@code <}{@link Finca }{@code >} {@link JAXBElement }
	 * {@code <}{@link Mov }{@code >} {@link JAXBElement }{@code <}{@link Finca }
	 * {@code >} {@link JAXBElement }{@code <}{@link Movf }{@code >}
	 * {@link JAXBElement }{@code <}{@link Finca }{@code >} {@link JAXBElement }
	 * {@code <}{@link Finca }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<?>> getContent() {
		if (content == null) {
			content = new ArrayList<JAXBElement<?>>();
		}
		return this.content;
	}

}
