//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for fincacfbi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fincacfbi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="fincafb" type="{http://www.catastro.meh.es/}fincaii" minOccurs="0"/>
 *           &lt;element name="movb" type="{http://www.catastro.meh.es/}movb"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fincacfbi", propOrder = { "fincafb", "movb" })
public class Fincacfbi {

	protected Fincaii fincafb;
	protected Movb movb;

	/**
	 * Gets the value of the fincafb property.
	 * 
	 * @return possible object is {@link Fincaii }
	 * 
	 */
	public Fincaii getFincafb() {
		return fincafb;
	}

	/**
	 * Sets the value of the fincafb property.
	 * 
	 * @param value
	 *            allowed object is {@link Fincaii }
	 * 
	 */
	public void setFincafb(Fincaii value) {
		this.fincafb = value;
	}

	/**
	 * Gets the value of the movb property.
	 * 
	 * @return possible object is {@link Movb }
	 * 
	 */
	public Movb getMovb() {
		return movb;
	}

	/**
	 * Sets the value of the movb property.
	 * 
	 * @param value
	 *            allowed object is {@link Movb }
	 * 
	 */
	public void setMovb(Movb value) {
		this.movb = value;
	}

}
