//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Fichero de salida que incluye el CSV
 * 
 * <p>
 * Java class for fioCSV complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fioCSV">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Documento" type="{http://www.catastro.meh.es/}DocumentoCSV" minOccurs="0"/>
 *         &lt;element name="err" type="{http://www.catastro.meh.es/}err" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fioCSV", propOrder = { "documento", "err" })
public class FioCSV {

	@XmlElement(name = "Documento")
	protected DocumentoCSV documento;
	protected Err err;

	/**
	 * Gets the value of the documento property.
	 * 
	 * @return possible object is {@link DocumentoCSV }
	 * 
	 */
	public DocumentoCSV getDocumento() {
		return documento;
	}

	/**
	 * Sets the value of the documento property.
	 * 
	 * @param value
	 *            allowed object is {@link DocumentoCSV }
	 * 
	 */
	public void setDocumento(DocumentoCSV value) {
		this.documento = value;
	}

	/**
	 * Gets the value of the err property.
	 * 
	 * @return possible object is {@link Err }
	 * 
	 */
	public Err getErr() {
		return err;
	}

	/**
	 * Sets the value of the err property.
	 * 
	 * @param value
	 *            allowed object is {@link Err }
	 * 
	 */
	public void setErr(Err value) {
		this.err = value;
	}

}
