//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Informacion de ponencia
 * 
 * <p>
 * Java class for fpon complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="fpon">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="cvpv" type="{http://www.catastro.meh.es/}cv"/>
 *           &lt;element name="ctvpv" type="{http://www.catastro.meh.es/}ctvpv"/>
 *         &lt;/sequence>
 *         &lt;element name="zv" type="{http://www.catastro.meh.es/}zv"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fpon", propOrder = { "cvpv", "ctvpv", "zv" })
public class Fpon {

	protected String cvpv;
	protected String ctvpv;
	protected String zv;

	/**
	 * Gets the value of the cvpv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCvpv() {
		return cvpv;
	}

	/**
	 * Sets the value of the cvpv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCvpv(String value) {
		this.cvpv = value;
	}

	/**
	 * Gets the value of the ctvpv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCtvpv() {
		return ctvpv;
	}

	/**
	 * Sets the value of the ctvpv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCtvpv(String value) {
		this.ctvpv = value;
	}

	/**
	 * Gets the value of the zv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getZv() {
		return zv;
	}

	/**
	 * Sets the value of the zv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setZv(String value) {
		this.zv = value;
	}

}
