//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Informacion adicional de identificacion
 * 
 * <p>
 * Java class for idadis complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idadis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nfbi" type="{http://www.catastro.meh.es/}nfbi" minOccurs="0"/>
 *         &lt;element name="iia" type="{http://www.catastro.meh.es/}iia" minOccurs="0"/>
 *         &lt;element name="nfr" type="{http://www.catastro.meh.es/}nfr" minOccurs="0"/>
 *         &lt;element name="idufir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noedh" type="{http://www.catastro.meh.es/}noedh" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idadis", propOrder = { "nfbi", "iia", "nfr", "idufir", "noedh" })
public class Idadis {

	protected String nfbi;
	protected String iia;
	protected Nfr nfr;
	protected String idufir;
	protected String noedh;

	/**
	 * Gets the value of the nfbi property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNfbi() {
		return nfbi;
	}

	/**
	 * Sets the value of the nfbi property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNfbi(String value) {
		this.nfbi = value;
	}

	/**
	 * Gets the value of the iia property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIia() {
		return iia;
	}

	/**
	 * Sets the value of the iia property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIia(String value) {
		this.iia = value;
	}

	/**
	 * Gets the value of the nfr property.
	 * 
	 * @return possible object is {@link Nfr }
	 * 
	 */
	public Nfr getNfr() {
		return nfr;
	}

	/**
	 * Sets the value of the nfr property.
	 * 
	 * @param value
	 *            allowed object is {@link Nfr }
	 * 
	 */
	public void setNfr(Nfr value) {
		this.nfr = value;
	}

	/**
	 * Gets the value of the idufir property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdufir() {
		return idufir;
	}

	/**
	 * Sets the value of the idufir property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdufir(String value) {
		this.idufir = value;
	}

	/**
	 * Gets the value of the noedh property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNoedh() {
		return noedh;
	}

	/**
	 * Sets the value of the noedh property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNoedh(String value) {
		this.noedh = value;
	}

}
