//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Identificacion del bien inmueble completa
 * 
 * <p>
 * Java class for idbic complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idbic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cn" type="{http://www.catastro.meh.es/}cn"/>
 *         &lt;element name="lrc" type="{http://www.catastro.meh.es/}lrc"/>
 *         &lt;element name="erc" type="{http://www.catastro.meh.es/}erc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idbic", propOrder = { "cn", "lrc", "erc" })
public class Idbic {

	@XmlElement(required = true)
	protected Cn cn;
	@XmlElement(required = true)
	protected String lrc;
	@XmlElement(required = true)
	protected String erc;

	/**
	 * Gets the value of the cn property.
	 * 
	 * @return possible object is {@link Cn }
	 * 
	 */
	public Cn getCn() {
		return cn;
	}

	/**
	 * Sets the value of the cn property.
	 * 
	 * @param value
	 *            allowed object is {@link Cn }
	 * 
	 */
	public void setCn(Cn value) {
		this.cn = value;
	}

	/**
	 * Gets the value of the lrc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLrc() {
		return lrc;
	}

	/**
	 * Sets the value of the lrc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLrc(String value) {
		this.lrc = value;
	}

	/**
	 * Gets the value of the erc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getErc() {
		return erc;
	}

	/**
	 * Sets the value of the erc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setErc(String value) {
		this.erc = value;
	}

}
