//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * identificacion de bien inmueble selectiva
 * 
 * <p>
 * Java class for idbis complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idbis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="idbic" type="{http://www.catastro.meh.es/}idbic"/>
 *         &lt;element name="idbip" type="{http://www.catastro.meh.es/}idbip"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idbis", propOrder = { "idbic", "idbip" })
public class Idbis {

	protected Idbic idbic;
	protected Idbip idbip;

	/**
	 * Gets the value of the idbic property.
	 * 
	 * @return possible object is {@link Idbic }
	 * 
	 */
	public Idbic getIdbic() {
		return idbic;
	}

	/**
	 * Sets the value of the idbic property.
	 * 
	 * @param value
	 *            allowed object is {@link Idbic }
	 * 
	 */
	public void setIdbic(Idbic value) {
		this.idbic = value;
	}

	/**
	 * Gets the value of the idbip property.
	 * 
	 * @return possible object is {@link Idbip }
	 * 
	 */
	public Idbip getIdbip() {
		return idbip;
	}

	/**
	 * Sets the value of the idbip property.
	 * 
	 * @param value
	 *            allowed object is {@link Idbip }
	 * 
	 */
	public void setIdbip(Idbip value) {
		this.idbip = value;
	}

}
