//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Identificacion de finca
 * 
 * <p>
 * Java class for idf complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cn" type="{http://www.catastro.meh.es/}cnf" minOccurs="0"/>
 *         &lt;element name="pc" type="{http://www.catastro.meh.es/}pc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idf", propOrder = { "cn", "pc" })
@XmlSeeAlso({ Idfcat.class })
public class Idf {

	protected Cnf cn;
	@XmlElement(required = true)
	protected Pc pc;

	/**
	 * Gets the value of the cn property.
	 * 
	 * @return possible object is {@link Cnf }
	 * 
	 */
	public Cnf getCn() {
		return cn;
	}

	/**
	 * Sets the value of the cn property.
	 * 
	 * @param value
	 *            allowed object is {@link Cnf }
	 * 
	 */
	public void setCn(Cnf value) {
		this.cn = value;
	}

	/**
	 * Gets the value of the pc property.
	 * 
	 * @return possible object is {@link Pc }
	 * 
	 */
	public Pc getPc() {
		return pc;
	}

	/**
	 * Sets the value of the pc property.
	 * 
	 * @param value
	 *            allowed object is {@link Pc }
	 * 
	 */
	public void setPc(Pc value) {
		this.pc = value;
	}

}
