//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Identificacion segun INE
 * 
 * <p>
 * Java class for idine complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.catastro.meh.es/}idbi">
 *       &lt;sequence>
 *         &lt;element name="loine" type="{http://www.catastro.meh.es/}loine"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idine", propOrder = { "loine" })
public class Idine extends Idbi {

	@XmlElement(required = true)
	protected Loine loine;

	/**
	 * Gets the value of the loine property.
	 * 
	 * @return possible object is {@link Loine }
	 * 
	 */
	public Loine getLoine() {
		return loine;
	}

	/**
	 * Sets the value of the loine property.
	 * 
	 * @param value
	 *            allowed object is {@link Loine }
	 * 
	 */
	public void setLoine(Loine value) {
		this.loine = value;
	}

}
