//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for idreg complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idreg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="locat" type="{http://www.catastro.meh.es/}locat"/>
 *         &lt;element name="rcl" type="{http://www.catastro.meh.es/}rcl" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idreg", propOrder = { "locat", "rcl" })
public class Idreg {

	@XmlElement(required = true)
	protected Locat locat;
	protected Rcl rcl;

	/**
	 * Gets the value of the locat property.
	 * 
	 * @return possible object is {@link Locat }
	 * 
	 */
	public Locat getLocat() {
		return locat;
	}

	/**
	 * Sets the value of the locat property.
	 * 
	 * @param value
	 *            allowed object is {@link Locat }
	 * 
	 */
	public void setLocat(Locat value) {
		this.locat = value;
	}

	/**
	 * Gets the value of the rcl property.
	 * 
	 * @return possible object is {@link Rcl }
	 * 
	 */
	public Rcl getRcl() {
		return rcl;
	}

	/**
	 * Sets the value of the rcl property.
	 * 
	 * @param value
	 *            allowed object is {@link Rcl }
	 * 
	 */
	public void setRcl(Rcl value) {
		this.rcl = value;
	}

}
