//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for idspri complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="idspri">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.catastro.meh.es/}pc">
 *       &lt;sequence>
 *         &lt;element name="cn" type="{http://www.catastro.meh.es/}cn"/>
 *         &lt;element name="cspr" type="{http://www.catastro.meh.es/}cspr"/>
 *         &lt;element name="ccc" type="{http://www.catastro.meh.es/}ccc"/>
 *         &lt;choice>
 *           &lt;element name="locat" type="{http://www.catastro.meh.es/}locat"/>
 *           &lt;element name="loine" type="{http://www.catastro.meh.es/}loine"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "idspri", propOrder = { "cn", "cspr", "ccc", "locat", "loine" })
public class Idspri extends Pc {

	@XmlElement(required = true)
	protected Cn cn;
	@XmlElement(required = true)
	protected String cspr;
	@XmlElement(required = true)
	protected String ccc;
	protected Locat locat;
	protected Loine loine;

	/**
	 * Gets the value of the cn property.
	 * 
	 * @return possible object is {@link Cn }
	 * 
	 */
	public Cn getCn() {
		return cn;
	}

	/**
	 * Sets the value of the cn property.
	 * 
	 * @param value
	 *            allowed object is {@link Cn }
	 * 
	 */
	public void setCn(Cn value) {
		this.cn = value;
	}

	/**
	 * Gets the value of the cspr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCspr() {
		return cspr;
	}

	/**
	 * Sets the value of the cspr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCspr(String value) {
		this.cspr = value;
	}

	/**
	 * Gets the value of the ccc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCcc() {
		return ccc;
	}

	/**
	 * Sets the value of the ccc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCcc(String value) {
		this.ccc = value;
	}

	/**
	 * Gets the value of the locat property.
	 * 
	 * @return possible object is {@link Locat }
	 * 
	 */
	public Locat getLocat() {
		return locat;
	}

	/**
	 * Sets the value of the locat property.
	 * 
	 * @param value
	 *            allowed object is {@link Locat }
	 * 
	 */
	public void setLocat(Locat value) {
		this.locat = value;
	}

	/**
	 * Gets the value of the loine property.
	 * 
	 * @return possible object is {@link Loine }
	 * 
	 */
	public Loine getLoine() {
		return loine;
	}

	/**
	 * Sets the value of the loine property.
	 * 
	 * @param value
	 *            allowed object is {@link Loine }
	 * 
	 */
	public void setLoine(Loine value) {
		this.loine = value;
	}

}
