//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Identificacion de la unidad constructiva
 * 
 * <p>
 * Java class for iduc complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="iduc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ruc" type="{http://www.catastro.meh.es/}ruc"/>
 *         &lt;element name="cn" type="{http://www.catastro.meh.es/}cn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iduc", propOrder = { "ruc", "cn" })
@XmlSeeAlso({ Iducati.class, Iducat.class })
public class Iduc {

	@XmlElement(required = true)
	protected Ruc ruc;
	@XmlElement(required = true)
	protected Cn cn;

	/**
	 * Gets the value of the ruc property.
	 * 
	 * @return possible object is {@link Ruc }
	 * 
	 */
	public Ruc getRuc() {
		return ruc;
	}

	/**
	 * Sets the value of the ruc property.
	 * 
	 * @param value
	 *            allowed object is {@link Ruc }
	 * 
	 */
	public void setRuc(Ruc value) {
		this.ruc = value;
	}

	/**
	 * Gets the value of the cn property.
	 * 
	 * @return possible object is {@link Cn }
	 * 
	 */
	public Cn getCn() {
		return cn;
	}

	/**
	 * Sets the value of the cn property.
	 * 
	 * @param value
	 *            allowed object is {@link Cn }
	 * 
	 */
	public void setCn(Cn value) {
		this.cn = value;
	}

}
