//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Identificacion de entidad generadora para el formato unico
 * 
 * <p>
 * Java class for iegi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="iegi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="teg" type="{http://www.catastro.meh.es/}teg"/>
 *         &lt;element name="ceg" type="{http://www.catastro.meh.es/}cegi"/>
 *         &lt;element name="neg" type="{http://www.catastro.meh.es/}neg"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "iegi", propOrder = { "teg", "ceg", "neg" })
public class Iegi {

	@XmlElement(required = true)
	protected Teg teg;
	@XmlElement(required = true)
	protected Cegi ceg;
	@XmlElement(required = true)
	protected String neg;

	/**
	 * Gets the value of the teg property.
	 * 
	 * @return possible object is {@link Teg }
	 * 
	 */
	public Teg getTeg() {
		return teg;
	}

	/**
	 * Sets the value of the teg property.
	 * 
	 * @param value
	 *            allowed object is {@link Teg }
	 * 
	 */
	public void setTeg(Teg value) {
		this.teg = value;
	}

	/**
	 * Gets the value of the ceg property.
	 * 
	 * @return possible object is {@link Cegi }
	 * 
	 */
	public Cegi getCeg() {
		return ceg;
	}

	/**
	 * Sets the value of the ceg property.
	 * 
	 * @param value
	 *            allowed object is {@link Cegi }
	 * 
	 */
	public void setCeg(Cegi value) {
		this.ceg = value;
	}

	/**
	 * Gets the value of the neg property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNeg() {
		return neg;
	}

	/**
	 * Sets the value of the neg property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNeg(String value) {
		this.neg = value;
	}

}
