//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Informacion de notarios y registradores del bien inmueble
 * 
 * <p>
 * Java class for inrbi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="inrbi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sup" type="{http://www.catastro.meh.es/}sup" minOccurs="0"/>
 *         &lt;element name="ciur" type="{http://www.catastro.meh.es/}ciur" minOccurs="0"/>
 *         &lt;element name="tcons" type="{http://www.catastro.meh.es/}tcons" minOccurs="0"/>
 *         &lt;element name="tnfr" type="{http://www.catastro.meh.es/}tnfr" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inrbi", propOrder = { "sup", "ciur", "tcons", "tnfr" })
public class Inrbi {

	protected BigInteger sup;
	protected String ciur;
	protected String tcons;
	protected String tnfr;

	/**
	 * Gets the value of the sup property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getSup() {
		return sup;
	}

	/**
	 * Sets the value of the sup property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setSup(BigInteger value) {
		this.sup = value;
	}

	/**
	 * Gets the value of the ciur property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCiur() {
		return ciur;
	}

	/**
	 * Sets the value of the ciur property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCiur(String value) {
		this.ciur = value;
	}

	/**
	 * Gets the value of the tcons property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTcons() {
		return tcons;
	}

	/**
	 * Sets the value of the tcons property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTcons(String value) {
		this.tcons = value;
	}

	/**
	 * Gets the value of the tnfr property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTnfr() {
		return tnfr;
	}

	/**
	 * Sets the value of the tnfr property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTnfr(String value) {
		this.tnfr = value;
	}

}
