//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lbicenv complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lbicenv">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;choice>
 *             &lt;element name="bicec" type="{http://www.catastro.meh.es/}bicece"/>
 *             &lt;element name="bij" type="{http://www.catastro.meh.es/}bije"/>
 *           &lt;/choice>
 *           &lt;element name="biccb" type="{http://www.catastro.meh.es/}biccb"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lbicenv", propOrder = { "bicecOrBijOrBiccb" })
public class Lbicenv {

	@XmlElements({ @XmlElement(name = "bicec", type = Bicece.class), @XmlElement(name = "bij", type = Bije.class), @XmlElement(name = "biccb", type = Biccb.class) })
	protected List<Object> bicecOrBijOrBiccb;

	/**
	 * Gets the value of the bicecOrBijOrBiccb property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the bicecOrBijOrBiccb property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBicecOrBijOrBiccb().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Bicece }
	 * {@link Bije } {@link Biccb }
	 * 
	 * 
	 */
	public List<Object> getBicecOrBijOrBiccb() {
		if (bicecOrBijOrBiccb == null) {
			bicecOrBijOrBiccb = new ArrayList<Object>();
		}
		return this.bicecOrBijOrBiccb;
	}

}
