//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lbicen complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lbicen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.catastro.meh.es/}bic">
 *       &lt;choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;choice>
 *             &lt;element name="bicec" type="{http://www.catastro.meh.es/}bicec" minOccurs="0"/>
 *             &lt;element name="bij" type="{http://www.catastro.meh.es/}bij" minOccurs="0"/>
 *           &lt;/choice>
 *           &lt;element name="biccb" type="{http://www.catastro.meh.es/}biccb" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;sequence minOccurs="0">
 *           &lt;element name="bicf" type="{http://www.catastro.meh.es/}bicf" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="bicreg" type="{http://www.catastro.meh.es/}bireg" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lbicen")
@XmlSeeAlso({ Lbicenreg.class, Lbicenf.class })
public class Lbicen extends Bic {

}
