//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lelem complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lelem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="elemv" type="{http://www.catastro.meh.es/}elemv" maxOccurs="unbounded"/>
 *         &lt;element name="elemf" type="{http://www.catastro.meh.es/}elemf" maxOccurs="unbounded"/>
 *         &lt;element name="elemr" type="{http://www.catastro.meh.es/}elemr" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lelem", propOrder = { "elemv", "elemf", "elemr" })
public class Lelem {

	protected List<Elemv> elemv;
	protected List<Elemf> elemf;
	protected List<Elemr> elemr;

	/**
	 * Gets the value of the elemv property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the elemv property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElemv().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Elemv }
	 * 
	 * 
	 */
	public List<Elemv> getElemv() {
		if (elemv == null) {
			elemv = new ArrayList<Elemv>();
		}
		return this.elemv;
	}

	/**
	 * Gets the value of the elemf property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the elemf property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElemf().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Elemf }
	 * 
	 * 
	 */
	public List<Elemf> getElemf() {
		if (elemf == null) {
			elemf = new ArrayList<Elemf>();
		}
		return this.elemf;
	}

	/**
	 * Gets the value of the elemr property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the elemr property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElemr().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Elemr }
	 * 
	 * 
	 */
	public List<Elemr> getElemr() {
		if (elemr == null) {
			elemr = new ArrayList<Elemr>();
		}
		return this.elemr;
	}

}
