//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Localizacion selectiva
 * 
 * <p>
 * Java class for locs complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="locs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="lous" type="{http://www.catastro.meh.es/}lous"/>
 *         &lt;element name="lors" type="{http://www.catastro.meh.es/}lors"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locs", propOrder = { "lous", "lors" })
public class Locs {

	protected Lous lous;
	protected Lors lors;

	/**
	 * Gets the value of the lous property.
	 * 
	 * @return possible object is {@link Lous }
	 * 
	 */
	public Lous getLous() {
		return lous;
	}

	/**
	 * Sets the value of the lous property.
	 * 
	 * @param value
	 *            allowed object is {@link Lous }
	 * 
	 */
	public void setLous(Lous value) {
		this.lous = value;
	}

	/**
	 * Gets the value of the lors property.
	 * 
	 * @return possible object is {@link Lors }
	 * 
	 */
	public Lors getLors() {
		return lors;
	}

	/**
	 * Sets the value of the lors property.
	 * 
	 * @param value
	 *            allowed object is {@link Lors }
	 * 
	 */
	public void setLors(Lors value) {
		this.lors = value;
	}

}
