//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Localizacion interna
 * 
 * <p>
 * Java class for loint complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="loint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bq" type="{http://www.catastro.meh.es/}bq" minOccurs="0"/>
 *         &lt;element name="es" type="{http://www.catastro.meh.es/}es" minOccurs="0"/>
 *         &lt;element name="pt" type="{http://www.catastro.meh.es/}pt" minOccurs="0"/>
 *         &lt;element name="pu" type="{http://www.catastro.meh.es/}pu" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "loint", propOrder = { "bq", "es", "pt", "pu" })
public class Loint {

	protected String bq;
	protected String es;
	protected String pt;
	protected String pu;

	/**
	 * Gets the value of the bq property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBq() {
		return bq;
	}

	/**
	 * Sets the value of the bq property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBq(String value) {
		this.bq = value;
	}

	/**
	 * Gets the value of the es property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEs() {
		return es;
	}

	/**
	 * Sets the value of the es property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEs(String value) {
		this.es = value;
	}

	/**
	 * Gets the value of the pt property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPt() {
		return pt;
	}

	/**
	 * Sets the value of the pt property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPt(String value) {
		this.pt = value;
	}

	/**
	 * Gets the value of the pu property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPu() {
		return pu;
	}

	/**
	 * Sets the value of the pu property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPu(String value) {
		this.pu = value;
	}

}
