//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Localizacion rustica
 * 
 * <p>
 * Java class for lorus complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lorus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cma" type="{http://www.catastro.meh.es/}cma" minOccurs="0"/>
 *         &lt;element name="czc" type="{http://www.catastro.meh.es/}czc" minOccurs="0"/>
 *         &lt;element name="cpp" type="{http://www.catastro.meh.es/}cpp" minOccurs="0"/>
 *         &lt;element name="npa" type="{http://www.catastro.meh.es/}npa" minOccurs="0"/>
 *         &lt;element name="cpaj" type="{http://www.catastro.meh.es/}cpaj" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lorus", propOrder = { "cma", "czc", "cpp", "npa", "cpaj" })
@XmlSeeAlso({ Lorusf.class, Lorusfop.class })
public class Lorus {

	protected String cma;
	protected String czc;
	protected Cpp cpp;
	protected String npa;
	protected String cpaj;

	/**
	 * Gets the value of the cma property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCma() {
		return cma;
	}

	/**
	 * Sets the value of the cma property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCma(String value) {
		this.cma = value;
	}

	/**
	 * Gets the value of the czc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCzc() {
		return czc;
	}

	/**
	 * Sets the value of the czc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCzc(String value) {
		this.czc = value;
	}

	/**
	 * Gets the value of the cpp property.
	 * 
	 * @return possible object is {@link Cpp }
	 * 
	 */
	public Cpp getCpp() {
		return cpp;
	}

	/**
	 * Sets the value of the cpp property.
	 * 
	 * @param value
	 *            allowed object is {@link Cpp }
	 * 
	 */
	public void setCpp(Cpp value) {
		this.cpp = value;
	}

	/**
	 * Gets the value of the npa property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNpa() {
		return npa;
	}

	/**
	 * Sets the value of the npa property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNpa(String value) {
		this.npa = value;
	}

	/**
	 * Gets the value of the cpaj property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCpaj() {
		return cpaj;
	}

	/**
	 * Sets the value of the cpaj property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCpaj(String value) {
		this.cpaj = value;
	}

}
