//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for lorusfop complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lorusfop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.catastro.meh.es/}lorus">
 *       &lt;sequence>
 *         &lt;element name="cma" type="{http://www.catastro.meh.es/}cma" minOccurs="0"/>
 *         &lt;element name="czc" type="{http://www.catastro.meh.es/}czc" minOccurs="0"/>
 *         &lt;element name="cpp" type="{http://www.catastro.meh.es/}cpp"/>
 *         &lt;element name="npa" type="{http://www.catastro.meh.es/}npa"/>
 *         &lt;element name="cpaj" type="{http://www.catastro.meh.es/}cpaj"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lorusfop")
public class Lorusfop extends Lorus {

}
