//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Lista de plantas
 * 
 * <p>
 * Java class for lplan complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="lplan">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="plansig">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="npss" type="{http://www.catastro.meh.es/}npss"/>
 *                   &lt;element name="npsig" type="{http://www.catastro.meh.es/}npsig"/>
 *                   &lt;element name="nd" type="{http://www.catastro.meh.es/}nd"/>
 *                   &lt;element name="ld">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dest">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="cd" type="{http://www.catastro.meh.es/}cdest"/>
 *                                       &lt;element name="supd" type="{http://www.catastro.meh.es/}supd"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lplan", propOrder = { "plansig" })
public class Lplan {

	@XmlElement(required = true)
	protected Lplan.Plansig plansig;

	/**
	 * Gets the value of the plansig property.
	 * 
	 * @return possible object is {@link Lplan.Plansig }
	 * 
	 */
	public Lplan.Plansig getPlansig() {
		return plansig;
	}

	/**
	 * Sets the value of the plansig property.
	 * 
	 * @param value
	 *            allowed object is {@link Lplan.Plansig }
	 * 
	 */
	public void setPlansig(Lplan.Plansig value) {
		this.plansig = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="npss" type="{http://www.catastro.meh.es/}npss"/>
	 *         &lt;element name="npsig" type="{http://www.catastro.meh.es/}npsig"/>
	 *         &lt;element name="nd" type="{http://www.catastro.meh.es/}nd"/>
	 *         &lt;element name="ld">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="dest">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="cd" type="{http://www.catastro.meh.es/}cdest"/>
	 *                             &lt;element name="supd" type="{http://www.catastro.meh.es/}supd"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "npss", "npsig", "nd", "ld" })
	public static class Plansig {

		@XmlElement(required = true)
		protected BigInteger npss;
		@XmlElement(required = true)
		protected String npsig;
		@XmlElement(required = true)
		protected BigInteger nd;
		@XmlElement(required = true)
		protected Lplan.Plansig.Ld ld;

		/**
		 * Gets the value of the npss property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getNpss() {
			return npss;
		}

		/**
		 * Sets the value of the npss property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setNpss(BigInteger value) {
			this.npss = value;
		}

		/**
		 * Gets the value of the npsig property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getNpsig() {
			return npsig;
		}

		/**
		 * Sets the value of the npsig property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setNpsig(String value) {
			this.npsig = value;
		}

		/**
		 * Gets the value of the nd property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getNd() {
			return nd;
		}

		/**
		 * Sets the value of the nd property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setNd(BigInteger value) {
			this.nd = value;
		}

		/**
		 * Gets the value of the ld property.
		 * 
		 * @return possible object is {@link Lplan.Plansig.Ld }
		 * 
		 */
		public Lplan.Plansig.Ld getLd() {
			return ld;
		}

		/**
		 * Sets the value of the ld property.
		 * 
		 * @param value
		 *            allowed object is {@link Lplan.Plansig.Ld }
		 * 
		 */
		public void setLd(Lplan.Plansig.Ld value) {
			this.ld = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="dest">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="cd" type="{http://www.catastro.meh.es/}cdest"/>
		 *                   &lt;element name="supd" type="{http://www.catastro.meh.es/}supd"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "dest" })
		public static class Ld {

			@XmlElement(required = true)
			protected Lplan.Plansig.Ld.Dest dest;

			/**
			 * Gets the value of the dest property.
			 * 
			 * @return possible object is {@link Lplan.Plansig.Ld.Dest }
			 * 
			 */
			public Lplan.Plansig.Ld.Dest getDest() {
				return dest;
			}

			/**
			 * Sets the value of the dest property.
			 * 
			 * @param value
			 *            allowed object is {@link Lplan.Plansig.Ld.Dest }
			 * 
			 */
			public void setDest(Lplan.Plansig.Ld.Dest value) {
				this.dest = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="cd" type="{http://www.catastro.meh.es/}cdest"/>
			 *         &lt;element name="supd" type="{http://www.catastro.meh.es/}supd"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "cd", "supd" })
			public static class Dest {

				@XmlElement(required = true)
				protected String cd;
				@XmlElement(required = true)
				protected BigInteger supd;

				/**
				 * Gets the value of the cd property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getCd() {
					return cd;
				}

				/**
				 * Sets the value of the cd property.
				 * 
				 * @param value
				 *            allowed object is {@link String }
				 * 
				 */
				public void setCd(String value) {
					this.cd = value;
				}

				/**
				 * Gets the value of the supd property.
				 * 
				 * @return possible object is {@link BigInteger }
				 * 
				 */
				public BigInteger getSupd() {
					return supd;
				}

				/**
				 * Sets the value of the supd property.
				 * 
				 * @param value
				 *            allowed object is {@link BigInteger }
				 * 
				 */
				public void setSupd(BigInteger value) {
					this.supd = value;
				}

			}

		}

	}

}
