//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for modl.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="modl">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TL1"/>
 *     &lt;enumeration value="TL2"/>
 *     &lt;enumeration value="TL3"/>
 *     &lt;enumeration value="TL4"/>
 *     &lt;enumeration value="TC1"/>
 *     &lt;enumeration value="TC2"/>
 *     &lt;enumeration value="TC3"/>
 *     &lt;enumeration value="TC4"/>
 *     &lt;enumeration value="AL1"/>
 *     &lt;enumeration value="AL2"/>
 *     &lt;enumeration value="AL3"/>
 *     &lt;enumeration value="AL4"/>
 *     &lt;enumeration value="AC1"/>
 *     &lt;enumeration value="AC2"/>
 *     &lt;enumeration value="AC3"/>
 *     &lt;enumeration value="AC4"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "modl")
@XmlEnum
public enum Modl {

	@XmlEnumValue("TL1")
	TL_1("TL1"), @XmlEnumValue("TL2")
	TL_2("TL2"), @XmlEnumValue("TL3")
	TL_3("TL3"), @XmlEnumValue("TL4")
	TL_4("TL4"), @XmlEnumValue("TC1")
	TC_1("TC1"), @XmlEnumValue("TC2")
	TC_2("TC2"), @XmlEnumValue("TC3")
	TC_3("TC3"), @XmlEnumValue("TC4")
	TC_4("TC4"), @XmlEnumValue("AL1")
	AL_1("AL1"), @XmlEnumValue("AL2")
	AL_2("AL2"), @XmlEnumValue("AL3")
	AL_3("AL3"), @XmlEnumValue("AL4")
	AL_4("AL4"), @XmlEnumValue("AC1")
	AC_1("AC1"), @XmlEnumValue("AC2")
	AC_2("AC2"), @XmlEnumValue("AC3")
	AC_3("AC3"), @XmlEnumValue("AC4")
	AC_4("AC4");
	private final String value;

	Modl(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Modl fromValue(String v) {
		for (Modl c : Modl.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
