//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for nump complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="nump">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pc" type="{http://www.catastro.meh.es/}pc"/>
 *         &lt;element name="num" type="{http://www.catastro.meh.es/}num"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nump", propOrder = { "pc", "num" })
public class Nump {

	@XmlElement(required = true)
	protected Pc pc;
	@XmlElement(required = true)
	protected Num num;

	/**
	 * Gets the value of the pc property.
	 * 
	 * @return possible object is {@link Pc }
	 * 
	 */
	public Pc getPc() {
		return pc;
	}

	/**
	 * Sets the value of the pc property.
	 * 
	 * @param value
	 *            allowed object is {@link Pc }
	 * 
	 */
	public void setPc(Pc value) {
		this.pc = value;
	}

	/**
	 * Gets the value of the num property.
	 * 
	 * @return possible object is {@link Num }
	 * 
	 */
	public Num getNum() {
		return num;
	}

	/**
	 * Sets the value of the num property.
	 * 
	 * @param value
	 *            allowed object is {@link Num }
	 * 
	 */
	public void setNum(Num value) {
		this.num = value;
	}

}
