//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for rbiu complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="rbiu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="rcu" type="{http://www.catastro.meh.es/}rcu"/>
 *         &lt;element name="cpp" type="{http://www.catastro.meh.es/}cpp"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rbiu", propOrder = { "rcu", "cpp" })
public class Rbiu {

	protected Rcu rcu;
	protected Cpp cpp;

	/**
	 * Gets the value of the rcu property.
	 * 
	 * @return possible object is {@link Rcu }
	 * 
	 */
	public Rcu getRcu() {
		return rcu;
	}

	/**
	 * Sets the value of the rcu property.
	 * 
	 * @param value
	 *            allowed object is {@link Rcu }
	 * 
	 */
	public void setRcu(Rcu value) {
		this.rcu = value;
	}

	/**
	 * Gets the value of the cpp property.
	 * 
	 * @return possible object is {@link Cpp }
	 * 
	 */
	public Cpp getCpp() {
		return cpp;
	}

	/**
	 * Sets the value of the cpp property.
	 * 
	 * @param value
	 *            allowed object is {@link Cpp }
	 * 
	 */
	public void setCpp(Cpp value) {
		this.cpp = value;
	}

}
