//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for reparcsi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="reparcsi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="repars" type="{http://www.catastro.meh.es/}reparsi"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reparcsi", propOrder = { "repars" })
public class Reparcsi {

	protected Reparsi repars;

	/**
	 * Gets the value of the repars property.
	 * 
	 * @return possible object is {@link Reparsi }
	 * 
	 */
	public Reparsi getRepars() {
		return repars;
	}

	/**
	 * Sets the value of the repars property.
	 * 
	 * @param value
	 *            allowed object is {@link Reparsi }
	 * 
	 */
	public void setRepars(Reparsi value) {
		this.repars = value;
	}

}
