//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Clave de la unidad constructiva
 * 
 * <p>
 * Java class for ruc complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ruc">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.catastro.meh.es/}pc">
 *       &lt;sequence>
 *         &lt;element name="cuc" type="{http://www.catastro.meh.es/}cuc"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruc", propOrder = { "cuc" })
public class Ruc extends Pc {

	@XmlElement(required = true)
	protected String cuc;

	/**
	 * Gets the value of the cuc property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCuc() {
		return cuc;
	}

	/**
	 * Sets the value of the cuc property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCuc(String value) {
		this.cuc = value;
	}

}
