//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for sprcfi complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="sprcfi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="sprf" type="{http://www.catastro.meh.es/}spr"/>
 *           &lt;element name="movf" type="{http://www.catastro.meh.es/}movi"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sprcfi", propOrder = { "sprf", "movf" })
public class Sprcfi {

	protected Spr sprf;
	protected Movi movf;

	/**
	 * Gets the value of the sprf property.
	 * 
	 * @return possible object is {@link Spr }
	 * 
	 */
	public Spr getSprf() {
		return sprf;
	}

	/**
	 * Sets the value of the sprf property.
	 * 
	 * @param value
	 *            allowed object is {@link Spr }
	 * 
	 */
	public void setSprf(Spr value) {
		this.sprf = value;
	}

	/**
	 * Gets the value of the movf property.
	 * 
	 * @return possible object is {@link Movi }
	 * 
	 */
	public Movi getMovf() {
		return movf;
	}

	/**
	 * Sets the value of the movf property.
	 * 
	 * @param value
	 *            allowed object is {@link Movi }
	 * 
	 */
	public void setMovf(Movi value) {
		this.movf = value;
	}

}
