//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Datos de coordinacion
 * 
 * <p>
 * Java class for tcoord complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tcoord">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="csv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="documento" type="{http://www.catastro.meh.es/}tdocucoord"/>
 *         &lt;/choice>
 *         &lt;element name="idufir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fecha" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcoord", propOrder = { "csv", "documento", "idufir", "fecha" })
public class Tcoord {

	protected String csv;
	protected Tdocucoord documento;
	@XmlElement(required = true)
	protected String idufir;
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar fecha;

	/**
	 * Gets the value of the csv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCsv() {
		return csv;
	}

	/**
	 * Sets the value of the csv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCsv(String value) {
		this.csv = value;
	}

	/**
	 * Gets the value of the documento property.
	 * 
	 * @return possible object is {@link Tdocucoord }
	 * 
	 */
	public Tdocucoord getDocumento() {
		return documento;
	}

	/**
	 * Sets the value of the documento property.
	 * 
	 * @param value
	 *            allowed object is {@link Tdocucoord }
	 * 
	 */
	public void setDocumento(Tdocucoord value) {
		this.documento = value;
	}

	/**
	 * Gets the value of the idufir property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIdufir() {
		return idufir;
	}

	/**
	 * Sets the value of the idufir property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIdufir(String value) {
		this.idufir = value;
	}

	/**
	 * Gets the value of the fecha property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFecha() {
		return fecha;
	}

	/**
	 * Sets the value of the fecha property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFecha(XMLGregorianCalendar value) {
		this.fecha = value;
	}

}
