//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tdocumentoresult complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tdocumentoresult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="csv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="metadatos" type="{http://www.catastro.meh.es/}tmetadatos" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tdocumentoresult", propOrder = { "csv", "metadatos" })
public class Tdocumentoresult {

	protected String csv;
	protected Tmetadatos metadatos;

	/**
	 * Gets the value of the csv property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCsv() {
		return csv;
	}

	/**
	 * Sets the value of the csv property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCsv(String value) {
		this.csv = value;
	}

	/**
	 * Gets the value of the metadatos property.
	 * 
	 * @return possible object is {@link Tmetadatos }
	 * 
	 */
	public Tmetadatos getMetadatos() {
		return metadatos;
	}

	/**
	 * Sets the value of the metadatos property.
	 * 
	 * @param value
	 *            allowed object is {@link Tmetadatos }
	 * 
	 */
	public void setMetadatos(Tmetadatos value) {
		this.metadatos = value;
	}

}
