//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tfi.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="tfi">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NRGE"/>
 *     &lt;enumeration value="NRGC"/>
 *     &lt;enumeration value="NRGR"/>
 *     &lt;enumeration value="CFIE"/>
 *     &lt;enumeration value="CFIC"/>
 *     &lt;enumeration value="CFIS"/>
 *     &lt;enumeration value="CFIR"/>
 *     &lt;enumeration value="CCOM"/>
 *     &lt;enumeration value="CCAT"/>
 *     &lt;enumeration value="CVPE"/>
 *     &lt;enumeration value="CVPC"/>
 *     &lt;enumeration value="CPAD"/>
 *     &lt;enumeration value="CDOC"/>
 *     &lt;enumeration value="CERR"/>
 *     &lt;enumeration value="WTCE"/>
 *     &lt;enumeration value="WTCS"/>
 *     &lt;enumeration value="WTAE"/>
 *     &lt;enumeration value="WTAS"/>
 *     &lt;enumeration value="WTEE"/>
 *     &lt;enumeration value="WTES"/>
 *     &lt;enumeration value="WTXE"/>
 *     &lt;enumeration value="WTXS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tfi")
@XmlEnum
public enum Tfi {

	NRGE, NRGC, NRGR, CFIE, CFIC, CFIS, CFIR, CCOM, CCAT, CVPE, CVPC, CPAD, CDOC, CERR, WTCE, WTCS, WTAE, WTAS, WTEE, WTES, WTXE, WTXS;

	public String value() {
		return name();
	}

	public static Tfi fromValue(String v) {
		return valueOf(v);
	}

}
