//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tinfoGraf complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tinfoGraf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="fxcc" type="{http://www.catastro.meh.es/}fxcc" minOccurs="0"/>
 *         &lt;element name="inspire" type="{http://www.catastro.meh.es/}inspire" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tinfoGraf", propOrder = { "fxcc", "inspire" })
public class TinfoGraf {

	protected Fxcc fxcc;
	protected Inspire inspire;

	/**
	 * Gets the value of the fxcc property.
	 * 
	 * @return possible object is {@link Fxcc }
	 * 
	 */
	public Fxcc getFxcc() {
		return fxcc;
	}

	/**
	 * Sets the value of the fxcc property.
	 * 
	 * @param value
	 *            allowed object is {@link Fxcc }
	 * 
	 */
	public void setFxcc(Fxcc value) {
		this.fxcc = value;
	}

	/**
	 * Gets the value of the inspire property.
	 * 
	 * @return possible object is {@link Inspire }
	 * 
	 */
	public Inspire getInspire() {
		return inspire;
	}

	/**
	 * Sets the value of the inspire property.
	 * 
	 * @param value
	 *            allowed object is {@link Inspire }
	 * 
	 */
	public void setInspire(Inspire value) {
		this.inspire = value;
	}

}
