//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 02:13:53 PM CEST 
//

package es.caib.avaedi.meh.catastro;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Tipo personas afectada
 * 
 * <p>
 * Java class for tpersonAfect complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tpersonAfect">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nif" type="{http://www.catastro.meh.es/}nif" minOccurs="0"/>
 *         &lt;element name="nom" type="{http://www.catastro.meh.es/}nom" minOccurs="0"/>
 *         &lt;element name="fecha" type="{http://www.catastro.meh.es/}fecha" minOccurs="0"/>
 *         &lt;element name="condicion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rc" type="{http://www.catastro.meh.es/}rcli" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tpersonAfect", propOrder = { "nif", "nom", "fecha", "condicion", "rc" })
public class TpersonAfect {

	protected String nif;
	protected String nom;
	protected XMLGregorianCalendar fecha;
	protected String condicion;
	protected Rcli rc;

	/**
	 * Gets the value of the nif property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNif() {
		return nif;
	}

	/**
	 * Sets the value of the nif property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNif(String value) {
		this.nif = value;
	}

	/**
	 * Gets the value of the nom property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNom() {
		return nom;
	}

	/**
	 * Sets the value of the nom property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNom(String value) {
		this.nom = value;
	}

	/**
	 * Gets the value of the fecha property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFecha() {
		return fecha;
	}

	/**
	 * Sets the value of the fecha property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFecha(XMLGregorianCalendar value) {
		this.fecha = value;
	}

	/**
	 * Gets the value of the condicion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCondicion() {
		return condicion;
	}

	/**
	 * Sets the value of the condicion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCondicion(String value) {
		this.condicion = value;
	}

	/**
	 * Gets the value of the rc property.
	 * 
	 * @return possible object is {@link Rcli }
	 * 
	 */
	public Rcli getRc() {
		return rc;
	}

	/**
	 * Sets the value of the rc property.
	 * 
	 * @param value
	 *            allowed object is {@link Rcli }
	 * 
	 */
	public void setRc(Rcli value) {
		this.rc = value;
	}

}
