package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * AccesibilidadAjustesRazonables generated by hbm2java
 */
@Entity
@Table(name = "aed_acc_ajustesrazonables")
public class AccesibilidadAjustesRazonables extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	private String ajustesrazonablesCoste;
	private String ajustesrazonablesDescripcion;
	private Integer edificionosusceptibleajustes;
	/**
	 * edificiosusceptibleajustes_total
	 */
	private Integer edificiosusceptibleajustesTotal;
	private String financiacionayuda;
	private String importegastoscomunes;
	/**
	 * observaciones_analisis_no_medidas
	 */
	private String observacionesAnalisisNoMedidas;
	private String observacionesCargaeconomica;
	/**
	 * observaciones_consideracionesinmueble
	 */
	private String observacionesConsideracionesinmueble;
	private String personasdiscapacitadasomayores;
	/**
	 * viviendasnoitinerarioaccesible
	 */
	private String viviendasnoitinerarioaccesible;

	public AccesibilidadAjustesRazonables() {
	}

	public AccesibilidadAjustesRazonables(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public AccesibilidadAjustesRazonables(Inspeccion inspeccion, String ajustesrazonablesCoste, String ajustesrazonablesDescripcion, Integer edificionosusceptibleajustes, Integer edificiosusceptibleajustesTotal, String financiacionayuda, String importegastoscomunes, String observacionesAnalisisNoMedidas, String observacionesCargaeconomica, String observacionesConsideracionesinmueble, String personasdiscapacitadasomayores, String viviendasnoitinerarioaccesible) {
		this.inspeccion = inspeccion;
		this.ajustesrazonablesCoste = ajustesrazonablesCoste;
		this.ajustesrazonablesDescripcion = ajustesrazonablesDescripcion;
		this.edificionosusceptibleajustes = edificionosusceptibleajustes;
		this.edificiosusceptibleajustesTotal = edificiosusceptibleajustesTotal;
		this.financiacionayuda = financiacionayuda;
		this.importegastoscomunes = importegastoscomunes;
		this.observacionesAnalisisNoMedidas = observacionesAnalisisNoMedidas;
		this.observacionesCargaeconomica = observacionesCargaeconomica;
		this.observacionesConsideracionesinmueble = observacionesConsideracionesinmueble;
		this.personasdiscapacitadasomayores = personasdiscapacitadasomayores;
		this.viviendasnoitinerarioaccesible = viviendasnoitinerarioaccesible;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "ajustesrazonables_coste")
	public String getAjustesrazonablesCoste() {
		return this.ajustesrazonablesCoste;
	}

	public void setAjustesrazonablesCoste(String ajustesrazonablesCoste) {
		this.ajustesrazonablesCoste = ajustesrazonablesCoste;
	}

	@Column(name = "ajustesrazonables_descripcion")
	public String getAjustesrazonablesDescripcion() {
		return this.ajustesrazonablesDescripcion;
	}

	public void setAjustesrazonablesDescripcion(String ajustesrazonablesDescripcion) {
		this.ajustesrazonablesDescripcion = ajustesrazonablesDescripcion;
	}

	@Column(name = "edificionosusceptibleajustes")
	public Integer getEdificionosusceptibleajustes() {
		return this.edificionosusceptibleajustes;
	}

	public void setEdificionosusceptibleajustes(Integer edificionosusceptibleajustes) {
		this.edificionosusceptibleajustes = edificionosusceptibleajustes;
	}

	/**
	 * * edificiosusceptibleajustes_total
	 */

	@Column(name = "edif_susceptible_ajustes_total")
	public Integer getEdificiosusceptibleajustesTotal() {
		return this.edificiosusceptibleajustesTotal;
	}

	public void setEdificiosusceptibleajustesTotal(Integer edificiosusceptibleajustesTotal) {
		this.edificiosusceptibleajustesTotal = edificiosusceptibleajustesTotal;
	}

	@Column(name = "financiacionayuda")
	public String getFinanciacionayuda() {
		return this.financiacionayuda;
	}

	public void setFinanciacionayuda(String financiacionayuda) {
		this.financiacionayuda = financiacionayuda;
	}

	@Column(name = "importegastoscomunes")
	public String getImportegastoscomunes() {
		return this.importegastoscomunes;
	}

	public void setImportegastoscomunes(String importegastoscomunes) {
		this.importegastoscomunes = importegastoscomunes;
	}

	/**
	 * * observaciones_analisis_no_medidas
	 */

	@Column(name = "obs_analisis_no_medidas")
	public String getObservacionesAnalisisNoMedidas() {
		return this.observacionesAnalisisNoMedidas;
	}

	public void setObservacionesAnalisisNoMedidas(String observacionesAnalisisNoMedidas) {
		this.observacionesAnalisisNoMedidas = observacionesAnalisisNoMedidas;
	}

	@Column(name = "observaciones_cargaeconomica")
	public String getObservacionesCargaeconomica() {
		return this.observacionesCargaeconomica;
	}

	public void setObservacionesCargaeconomica(String observacionesCargaeconomica) {
		this.observacionesCargaeconomica = observacionesCargaeconomica;
	}

	/**
	 * * observaciones_consideracionesinmueble
	 */

	@Column(name = "obs_consideracionesinmueble")
	public String getObservacionesConsideracionesinmueble() {
		return this.observacionesConsideracionesinmueble;
	}

	public void setObservacionesConsideracionesinmueble(String observacionesConsideracionesinmueble) {
		this.observacionesConsideracionesinmueble = observacionesConsideracionesinmueble;
	}

	@Column(name = "personasdiscapacitadasomayores")
	public String getPersonasdiscapacitadasomayores() {
		return this.personasdiscapacitadasomayores;
	}

	public void setPersonasdiscapacitadasomayores(String personasdiscapacitadasomayores) {
		this.personasdiscapacitadasomayores = personasdiscapacitadasomayores;
	}

	/**
	 * * viviendasnoitinerarioaccesible
	 */

	@Column(name = "viviendasnoitin_acc")
	public String getViviendasnoitinerarioaccesible() {
		return this.viviendasnoitinerarioaccesible;
	}

	public void setViviendasnoitinerarioaccesible(String viviendasnoitinerarioaccesible) {
		this.viviendasnoitinerarioaccesible = viviendasnoitinerarioaccesible;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccesibilidadAjustesRazonables))
			return false;
		AccesibilidadAjustesRazonables castOther = (AccesibilidadAjustesRazonables) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
