package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * AccesibilidadPublicos generated by hbm2java
 */
@Entity
@Table(name = "aed_acc_publicos")
public class AccesibilidadPublicos extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	/**
	 * (alojamientosaccesibles_1porcada_50)
	 */
	private String alojamientosaccesibles1porcada50;
	/**
	 * (alojamientosaccesibles_minimo_1)
	 */
	private String alojamientosaccesiblesMinimo1;
	/**
	 * (alojamientosaccesibles_minimo_2)
	 */
	private String alojamientosaccesiblesMinimo2;
	/**
	 * (alojamientosaccesibles_minimo_4)
	 */
	private String alojamientosaccesiblesMinimo4;
	/**
	 * (alojamientosaccesibles_minimo_6)
	 */
	private String alojamientosaccesiblesMinimo6;
	/**
	 * (alojamientosaccesibles_minimo_8)
	 */
	private String alojamientosaccesiblesMinimo8;
	/**
	 * (alojamientosaccesibles_observaciones)
	 */
	private String alojamientosaccesiblesObservaciones;
	/**
	 * (aparcamiento_comercial_porfraccion)
	 */
	private String aparcamientoComercialPorfraccion;
	private String aparcamientoObservaciones;
	/**
	 * (aparcamiento_otrosusos_minimoaparcamientos_unamasporfraccion)
	 */
	private String aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion;
	/**
	 * (aparcamiento_otrosusos_minimoaparcamientos_unaporfraccion)
	 */
	private String aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion;
	/**
	 * (aparcamiento_residencialpublico_poralojamiento)
	 */
	private String aparcamientoResidencialpublicoPoralojamiento;
	private String aparcamientoSillaruedas;
	private Integer entreplantasAccesible;
	/**
	 * (entreplantas_accesible_ascensornoaccesible)
	 */
	private String entreplantasAccesibleAscensornoaccesible;
	/**
	 * (entreplantas_accesible_ascensornoaccesible_dimensiones)
	 */
	private String entreplantasAccesibleAscensornoaccesibleDimensiones;
	/**
	 * (entreplantas_accesible_ascensororampaaccesible)
	 */
	private String entreplantasAccesibleAscensororampaaccesible;
	/**
	 * (entreplantas_accesible_rampaascensornoaccesible)
	 */
	private String entreplantasAccesibleRampaascensornoaccesible;
	/**
	 * (entreplantas_elementosaccesibles)
	 */
	private Integer entreplantasElementosaccesibles;
	/**
	 * (entreplantas_elementosaccesibles_ascensornoaccesible)
	 */
	private String entreplantasElementosaccesiblesAscensornoaccesible;
	/**
	 * (entreplantas_elementosaccesibles_ascensornoaccesible_dimensione)
	 */
	private String entreplantasElementosaccesiblesAscensornoaccesibleDimensione;
	/**
	 * (entreplantas_elementosaccesibles_ascensororampaaccesible)
	 */
	private String entreplantasElementosaccesiblesAscensororampaaccesible;
	/**
	 * (entreplantas_elementosaccesibles_rampaascensornoaccesible)
	 */
	private String entreplantasElementosaccesiblesRampaascensornoaccesible;
	private Integer entreplantasNoaccesible;
	/**
	 * (entreplantas_noaccesible_ascensornoaccesible)
	 */
	private String entreplantasNoaccesibleAscensornoaccesible;
	/**
	 * (entreplantas_noaccesible_ascensornoaccesible_dimensiones)
	 */
	private String entreplantasNoaccesibleAscensornoaccesibleDimensiones;
	/**
	 * (entreplantas_noaccesible_ascensororampaaccesible)
	 */
	private String entreplantasNoaccesibleAscensororampaaccesible;
	/**
	 * (entreplantas_noaccesible_rampaascensornoaccesible)
	 */
	private String entreplantasNoaccesibleRampaascensornoaccesible;
	private String entreplantasObservaciones;
	private Integer entreplantasZonasusopublico;
	/**
	 * (entreplantas_zonasusopublico_ascensornoaccesible)
	 */
	private String entreplantasZonasusopublicoAscensornoaccesible;
	/**
	 * (entreplantas_zonasusopublico_ascensornoaccesible_dimensiones)
	 */
	private String entreplantasZonasusopublicoAscensornoaccesibleDimensiones;
	/**
	 * (entreplantas_zonasusopublico_ascensororampaaccesible)
	 */
	private String entreplantasZonasusopublicoAscensororampaaccesible;
	/**
	 * (entreplantas_zonasusopublico_rampaascensornoaccesible)
	 */
	private String entreplantasZonasusopublicoRampaascensornoaccesible;
	private Integer esTecnicoInspeccion;
	/**
	 * (exterior_edificioitinerarioaccesible_viapublica)
	 */
	private Integer exteriorEdificioitinerarioaccesibleViapublica;
	/**
	 * (exterior_edificioitinerarioaccesible_zonascomunes)
	 */
	private Integer exteriorEdificioitinerarioaccesibleZonascomunes;
	private String exteriorObservaciones;
	/**
	 * (informacionsenalizacion_ascensores)
	 */
	private String informacionsenalizacionAscensores;
	/**
	 * (informacionsenalizacion_ascensores_brailearabigo)
	 */
	private String informacionsenalizacionAscensoresBrailearabigo;
	/**
	 * (informacionsenalizacion_ascensores_numeroplanta)
	 */
	private String informacionsenalizacionAscensoresNumeroplanta;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles)
	 */
	private String informacionsenalizacionBandasvisualestactiles;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles_arranqueescalera)
	 */
	private String informacionsenalizacionBandasvisualestactilesArranqueescalera;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles_colorcontrastado)
	 */
	private String informacionsenalizacionBandasvisualestactilesColorcontrastado;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles_itinerarioaccesi)
	 */
	private String informacionsenalizacionBandasvisualestactilesItinerarioaccesi;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles_relieveexterior)
	 */
	private String informacionsenalizacionBandasvisualestactilesRelieveexterior;
	/**
	 * (informacionsenalizacion_bandasvisualestactiles_relieveinterior)
	 */
	private String informacionsenalizacionBandasvisualestactilesRelieveinterior;
	/**
	 * (informacionsenalizacion_buclemagnetico)
	 */
	private String informacionsenalizacionBuclemagnetico;
	/**
	 * (informacionsenalizacion_buclemagnetico_senalizado)
	 */
	private String informacionsenalizacionBuclemagneticoSenalizado;
	/**
	 * (informacionsenalizacion_observaciones)
	 */
	private String informacionsenalizacionObservaciones;
	/**
	 * (informacionsenalizacion_privado_sia_aparcamiento)
	 */
	private String informacionsenalizacionPrivadoSiaAparcamiento;
	/**
	 * (informacionsenalizacion_privado_sia_ascensores)
	 */
	private String informacionsenalizacionPrivadoSiaAscensores;
	/**
	 * (informacionsenalizacion_privado_sia_entradas)
	 */
	private String informacionsenalizacionPrivadoSiaEntradas;
	/**
	 * (informacionsenalizacion_privado_sia_itinerarios)
	 */
	private String informacionsenalizacionPrivadoSiaItinerarios;
	/**
	 * (informacionsenalizacion_privado_sia_plazasreservadas)
	 */
	private String informacionsenalizacionPrivadoSiaPlazasreservadas;
	/**
	 * (informacionsenalizacion_publico_sia_aparcamiento)
	 */
	private String informacionsenalizacionPublicoSiaAparcamiento;
	/**
	 * (informacionsenalizacion_publico_sia_ascensores)
	 */
	private String informacionsenalizacionPublicoSiaAscensores;
	/**
	 * (informacionsenalizacion_publico_sia_entradas)
	 */
	private String informacionsenalizacionPublicoSiaEntradas;
	/**
	 * (informacionsenalizacion_publico_sia_itinerarios)
	 */
	private String informacionsenalizacionPublicoSiaItinerarios;
	/**
	 * (informacionsenalizacion_publico_sia_plazasreservadas)
	 */
	private String informacionsenalizacionPublicoSiaPlazasreservadas;
	/**
	 * (informacionsenalizacion_publico_sia_puntosatencion)
	 */
	private String informacionsenalizacionPublicoSiaPuntosatencion;
	/**
	 * (informacionsenalizacion_publico_sia_servicioshigienicos)
	 */
	private String informacionsenalizacionPublicoSiaServicioshigienicos;
	/**
	 * (informacionsenalizacion_servicioshigienicossenalizados)
	 */
	private String informacionsenalizacionServicioshigienicossenalizados;
	/**
	 * (informacionsenalizacion_sianorma)
	 */
	private String informacionsenalizacionSianorma;
	/**
	 * (informacionsenalizacion_todosusos_observaciones)
	 */
	private String informacionsenalizacionTodosusosObservaciones;
	private String mecanismosAccesibles;
	private String mecanismosObservaciones;
	private String mobiliariofijoObservaciones;
	private String mobiliariofijoPuntoaccesible;
	private String nif;
	private String piscinasEntradaaccesible;
	private String piscinasObservaciones;
	/**
	 * (plantas_itinerarioaccesible_elementosaccesibles)
	 */
	private Integer plantasItinerarioaccesibleElementosaccesibles;
	/**
	 * (plantas_itinerarioaccesible_entresi)
	 */
	private Integer plantasItinerarioaccesibleEntresi;
	/**
	 * (plantas_itinerarioaccesible_observaciones)
	 */
	private String plantasItinerarioaccesibleObservaciones;
	/**
	 * (plantas_itinerarioaccesible_zonasusoprivado)
	 */
	private Integer plantasItinerarioaccesibleZonasusoprivado;
	/**
	 * (plantas_itinerarioaccesible_zonasusopublico)
	 */
	private Integer plantasItinerarioaccesibleZonasusopublico;
	/**
	 * (plazasreservadas_discapacidadauditiva)
	 */
	private String plazasreservadasDiscapacidadauditiva;
	/**
	 * (plazasreservadas_observaciones)
	 */
	private String plazasreservadasObservaciones;
	private String plazasreservadasSillaruedas;
	/**
	 * (plazasreservadas_zonaespera_sillaruedas)
	 */
	private String plazasreservadasZonaesperaSillaruedas;
	/**
	 * (servicioshigienicos_aseoaccesible)
	 */
	private String servicioshigienicosAseoaccesible;
	/**
	 * (servicioshigienicos_cabinaduchaaccesibles)
	 */
	private String servicioshigienicosCabinaduchaaccesibles;
	/**
	 * (servicioshigienicos_observaciones)
	 */
	private String servicioshigienicosObservaciones;
	private String tecnico;
	private String titulacion;

	public AccesibilidadPublicos() {
	}

	public AccesibilidadPublicos(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public AccesibilidadPublicos(Inspeccion inspeccion, String alojamientosaccesibles1porcada50, String alojamientosaccesiblesMinimo1, String alojamientosaccesiblesMinimo2, String alojamientosaccesiblesMinimo4, String alojamientosaccesiblesMinimo6, String alojamientosaccesiblesMinimo8, String alojamientosaccesiblesObservaciones, String aparcamientoComercialPorfraccion, String aparcamientoObservaciones, String aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion, String aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion, String aparcamientoResidencialpublicoPoralojamiento, String aparcamientoSillaruedas, Integer entreplantasAccesible, String entreplantasAccesibleAscensornoaccesible, String entreplantasAccesibleAscensornoaccesibleDimensiones, String entreplantasAccesibleAscensororampaaccesible, String entreplantasAccesibleRampaascensornoaccesible, Integer entreplantasElementosaccesibles, String entreplantasElementosaccesiblesAscensornoaccesible, String entreplantasElementosaccesiblesAscensornoaccesibleDimensione, String entreplantasElementosaccesiblesAscensororampaaccesible, String entreplantasElementosaccesiblesRampaascensornoaccesible, Integer entreplantasNoaccesible, String entreplantasNoaccesibleAscensornoaccesible, String entreplantasNoaccesibleAscensornoaccesibleDimensiones, String entreplantasNoaccesibleAscensororampaaccesible, String entreplantasNoaccesibleRampaascensornoaccesible, String entreplantasObservaciones, Integer entreplantasZonasusopublico, String entreplantasZonasusopublicoAscensornoaccesible, String entreplantasZonasusopublicoAscensornoaccesibleDimensiones, String entreplantasZonasusopublicoAscensororampaaccesible, String entreplantasZonasusopublicoRampaascensornoaccesible, Integer esTecnicoInspeccion, Integer exteriorEdificioitinerarioaccesibleViapublica, Integer exteriorEdificioitinerarioaccesibleZonascomunes, String exteriorObservaciones, String informacionsenalizacionAscensores, String informacionsenalizacionAscensoresBrailearabigo, String informacionsenalizacionAscensoresNumeroplanta, String informacionsenalizacionBandasvisualestactiles, String informacionsenalizacionBandasvisualestactilesArranqueescalera, String informacionsenalizacionBandasvisualestactilesColorcontrastado, String informacionsenalizacionBandasvisualestactilesItinerarioaccesi, String informacionsenalizacionBandasvisualestactilesRelieveexterior, String informacionsenalizacionBandasvisualestactilesRelieveinterior, String informacionsenalizacionBuclemagnetico, String informacionsenalizacionBuclemagneticoSenalizado, String informacionsenalizacionObservaciones, String informacionsenalizacionPrivadoSiaAparcamiento, String informacionsenalizacionPrivadoSiaAscensores, String informacionsenalizacionPrivadoSiaEntradas, String informacionsenalizacionPrivadoSiaItinerarios, String informacionsenalizacionPrivadoSiaPlazasreservadas, String informacionsenalizacionPublicoSiaAparcamiento, String informacionsenalizacionPublicoSiaAscensores, String informacionsenalizacionPublicoSiaEntradas, String informacionsenalizacionPublicoSiaItinerarios, String informacionsenalizacionPublicoSiaPlazasreservadas, String informacionsenalizacionPublicoSiaPuntosatencion, String informacionsenalizacionPublicoSiaServicioshigienicos, String informacionsenalizacionServicioshigienicossenalizados, String informacionsenalizacionSianorma, String informacionsenalizacionTodosusosObservaciones, String mecanismosAccesibles, String mecanismosObservaciones, String mobiliariofijoObservaciones, String mobiliariofijoPuntoaccesible, String nif, String piscinasEntradaaccesible, String piscinasObservaciones, Integer plantasItinerarioaccesibleElementosaccesibles, Integer plantasItinerarioaccesibleEntresi, String plantasItinerarioaccesibleObservaciones, Integer plantasItinerarioaccesibleZonasusoprivado, Integer plantasItinerarioaccesibleZonasusopublico, String plazasreservadasDiscapacidadauditiva, String plazasreservadasObservaciones, String plazasreservadasSillaruedas, String plazasreservadasZonaesperaSillaruedas, String servicioshigienicosAseoaccesible, String servicioshigienicosCabinaduchaaccesibles, String servicioshigienicosObservaciones, String tecnico, String titulacion) {
		this.inspeccion = inspeccion;
		this.alojamientosaccesibles1porcada50 = alojamientosaccesibles1porcada50;
		this.alojamientosaccesiblesMinimo1 = alojamientosaccesiblesMinimo1;
		this.alojamientosaccesiblesMinimo2 = alojamientosaccesiblesMinimo2;
		this.alojamientosaccesiblesMinimo4 = alojamientosaccesiblesMinimo4;
		this.alojamientosaccesiblesMinimo6 = alojamientosaccesiblesMinimo6;
		this.alojamientosaccesiblesMinimo8 = alojamientosaccesiblesMinimo8;
		this.alojamientosaccesiblesObservaciones = alojamientosaccesiblesObservaciones;
		this.aparcamientoComercialPorfraccion = aparcamientoComercialPorfraccion;
		this.aparcamientoObservaciones = aparcamientoObservaciones;
		this.aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion = aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion;
		this.aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion = aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion;
		this.aparcamientoResidencialpublicoPoralojamiento = aparcamientoResidencialpublicoPoralojamiento;
		this.aparcamientoSillaruedas = aparcamientoSillaruedas;
		this.entreplantasAccesible = entreplantasAccesible;
		this.entreplantasAccesibleAscensornoaccesible = entreplantasAccesibleAscensornoaccesible;
		this.entreplantasAccesibleAscensornoaccesibleDimensiones = entreplantasAccesibleAscensornoaccesibleDimensiones;
		this.entreplantasAccesibleAscensororampaaccesible = entreplantasAccesibleAscensororampaaccesible;
		this.entreplantasAccesibleRampaascensornoaccesible = entreplantasAccesibleRampaascensornoaccesible;
		this.entreplantasElementosaccesibles = entreplantasElementosaccesibles;
		this.entreplantasElementosaccesiblesAscensornoaccesible = entreplantasElementosaccesiblesAscensornoaccesible;
		this.entreplantasElementosaccesiblesAscensornoaccesibleDimensione = entreplantasElementosaccesiblesAscensornoaccesibleDimensione;
		this.entreplantasElementosaccesiblesAscensororampaaccesible = entreplantasElementosaccesiblesAscensororampaaccesible;
		this.entreplantasElementosaccesiblesRampaascensornoaccesible = entreplantasElementosaccesiblesRampaascensornoaccesible;
		this.entreplantasNoaccesible = entreplantasNoaccesible;
		this.entreplantasNoaccesibleAscensornoaccesible = entreplantasNoaccesibleAscensornoaccesible;
		this.entreplantasNoaccesibleAscensornoaccesibleDimensiones = entreplantasNoaccesibleAscensornoaccesibleDimensiones;
		this.entreplantasNoaccesibleAscensororampaaccesible = entreplantasNoaccesibleAscensororampaaccesible;
		this.entreplantasNoaccesibleRampaascensornoaccesible = entreplantasNoaccesibleRampaascensornoaccesible;
		this.entreplantasObservaciones = entreplantasObservaciones;
		this.entreplantasZonasusopublico = entreplantasZonasusopublico;
		this.entreplantasZonasusopublicoAscensornoaccesible = entreplantasZonasusopublicoAscensornoaccesible;
		this.entreplantasZonasusopublicoAscensornoaccesibleDimensiones = entreplantasZonasusopublicoAscensornoaccesibleDimensiones;
		this.entreplantasZonasusopublicoAscensororampaaccesible = entreplantasZonasusopublicoAscensororampaaccesible;
		this.entreplantasZonasusopublicoRampaascensornoaccesible = entreplantasZonasusopublicoRampaascensornoaccesible;
		this.esTecnicoInspeccion = esTecnicoInspeccion;
		this.exteriorEdificioitinerarioaccesibleViapublica = exteriorEdificioitinerarioaccesibleViapublica;
		this.exteriorEdificioitinerarioaccesibleZonascomunes = exteriorEdificioitinerarioaccesibleZonascomunes;
		this.exteriorObservaciones = exteriorObservaciones;
		this.informacionsenalizacionAscensores = informacionsenalizacionAscensores;
		this.informacionsenalizacionAscensoresBrailearabigo = informacionsenalizacionAscensoresBrailearabigo;
		this.informacionsenalizacionAscensoresNumeroplanta = informacionsenalizacionAscensoresNumeroplanta;
		this.informacionsenalizacionBandasvisualestactiles = informacionsenalizacionBandasvisualestactiles;
		this.informacionsenalizacionBandasvisualestactilesArranqueescalera = informacionsenalizacionBandasvisualestactilesArranqueescalera;
		this.informacionsenalizacionBandasvisualestactilesColorcontrastado = informacionsenalizacionBandasvisualestactilesColorcontrastado;
		this.informacionsenalizacionBandasvisualestactilesItinerarioaccesi = informacionsenalizacionBandasvisualestactilesItinerarioaccesi;
		this.informacionsenalizacionBandasvisualestactilesRelieveexterior = informacionsenalizacionBandasvisualestactilesRelieveexterior;
		this.informacionsenalizacionBandasvisualestactilesRelieveinterior = informacionsenalizacionBandasvisualestactilesRelieveinterior;
		this.informacionsenalizacionBuclemagnetico = informacionsenalizacionBuclemagnetico;
		this.informacionsenalizacionBuclemagneticoSenalizado = informacionsenalizacionBuclemagneticoSenalizado;
		this.informacionsenalizacionObservaciones = informacionsenalizacionObservaciones;
		this.informacionsenalizacionPrivadoSiaAparcamiento = informacionsenalizacionPrivadoSiaAparcamiento;
		this.informacionsenalizacionPrivadoSiaAscensores = informacionsenalizacionPrivadoSiaAscensores;
		this.informacionsenalizacionPrivadoSiaEntradas = informacionsenalizacionPrivadoSiaEntradas;
		this.informacionsenalizacionPrivadoSiaItinerarios = informacionsenalizacionPrivadoSiaItinerarios;
		this.informacionsenalizacionPrivadoSiaPlazasreservadas = informacionsenalizacionPrivadoSiaPlazasreservadas;
		this.informacionsenalizacionPublicoSiaAparcamiento = informacionsenalizacionPublicoSiaAparcamiento;
		this.informacionsenalizacionPublicoSiaAscensores = informacionsenalizacionPublicoSiaAscensores;
		this.informacionsenalizacionPublicoSiaEntradas = informacionsenalizacionPublicoSiaEntradas;
		this.informacionsenalizacionPublicoSiaItinerarios = informacionsenalizacionPublicoSiaItinerarios;
		this.informacionsenalizacionPublicoSiaPlazasreservadas = informacionsenalizacionPublicoSiaPlazasreservadas;
		this.informacionsenalizacionPublicoSiaPuntosatencion = informacionsenalizacionPublicoSiaPuntosatencion;
		this.informacionsenalizacionPublicoSiaServicioshigienicos = informacionsenalizacionPublicoSiaServicioshigienicos;
		this.informacionsenalizacionServicioshigienicossenalizados = informacionsenalizacionServicioshigienicossenalizados;
		this.informacionsenalizacionSianorma = informacionsenalizacionSianorma;
		this.informacionsenalizacionTodosusosObservaciones = informacionsenalizacionTodosusosObservaciones;
		this.mecanismosAccesibles = mecanismosAccesibles;
		this.mecanismosObservaciones = mecanismosObservaciones;
		this.mobiliariofijoObservaciones = mobiliariofijoObservaciones;
		this.mobiliariofijoPuntoaccesible = mobiliariofijoPuntoaccesible;
		this.nif = nif;
		this.piscinasEntradaaccesible = piscinasEntradaaccesible;
		this.piscinasObservaciones = piscinasObservaciones;
		this.plantasItinerarioaccesibleElementosaccesibles = plantasItinerarioaccesibleElementosaccesibles;
		this.plantasItinerarioaccesibleEntresi = plantasItinerarioaccesibleEntresi;
		this.plantasItinerarioaccesibleObservaciones = plantasItinerarioaccesibleObservaciones;
		this.plantasItinerarioaccesibleZonasusoprivado = plantasItinerarioaccesibleZonasusoprivado;
		this.plantasItinerarioaccesibleZonasusopublico = plantasItinerarioaccesibleZonasusopublico;
		this.plazasreservadasDiscapacidadauditiva = plazasreservadasDiscapacidadauditiva;
		this.plazasreservadasObservaciones = plazasreservadasObservaciones;
		this.plazasreservadasSillaruedas = plazasreservadasSillaruedas;
		this.plazasreservadasZonaesperaSillaruedas = plazasreservadasZonaesperaSillaruedas;
		this.servicioshigienicosAseoaccesible = servicioshigienicosAseoaccesible;
		this.servicioshigienicosCabinaduchaaccesibles = servicioshigienicosCabinaduchaaccesibles;
		this.servicioshigienicosObservaciones = servicioshigienicosObservaciones;
		this.tecnico = tecnico;
		this.titulacion = titulacion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (alojamientosaccesibles_1porcada_50)
	 */

	@Column(name = "alojami_accesibles_1porcada_50")
	public String getAlojamientosaccesibles1porcada50() {
		return this.alojamientosaccesibles1porcada50;
	}

	public void setAlojamientosaccesibles1porcada50(String alojamientosaccesibles1porcada50) {
		this.alojamientosaccesibles1porcada50 = alojamientosaccesibles1porcada50;
	}

	/**
	 * * (alojamientosaccesibles_minimo_1)
	 */

	@Column(name = "alojami_accesibles_minimo_1")
	public String getAlojamientosaccesiblesMinimo1() {
		return this.alojamientosaccesiblesMinimo1;
	}

	public void setAlojamientosaccesiblesMinimo1(String alojamientosaccesiblesMinimo1) {
		this.alojamientosaccesiblesMinimo1 = alojamientosaccesiblesMinimo1;
	}

	/**
	 * * (alojamientosaccesibles_minimo_2)
	 */

	@Column(name = "alojami_accesibles_minimo_2")
	public String getAlojamientosaccesiblesMinimo2() {
		return this.alojamientosaccesiblesMinimo2;
	}

	public void setAlojamientosaccesiblesMinimo2(String alojamientosaccesiblesMinimo2) {
		this.alojamientosaccesiblesMinimo2 = alojamientosaccesiblesMinimo2;
	}

	/**
	 * * (alojamientosaccesibles_minimo_4)
	 */

	@Column(name = "alojami_accesibles_minimo_4")
	public String getAlojamientosaccesiblesMinimo4() {
		return this.alojamientosaccesiblesMinimo4;
	}

	public void setAlojamientosaccesiblesMinimo4(String alojamientosaccesiblesMinimo4) {
		this.alojamientosaccesiblesMinimo4 = alojamientosaccesiblesMinimo4;
	}

	/**
	 * * (alojamientosaccesibles_minimo_6)
	 */

	@Column(name = "alojami_accesibles_minimo_6")
	public String getAlojamientosaccesiblesMinimo6() {
		return this.alojamientosaccesiblesMinimo6;
	}

	public void setAlojamientosaccesiblesMinimo6(String alojamientosaccesiblesMinimo6) {
		this.alojamientosaccesiblesMinimo6 = alojamientosaccesiblesMinimo6;
	}

	/**
	 * * (alojamientosaccesibles_minimo_8)
	 */

	@Column(name = "alojami_accesibles_minimo_8")
	public String getAlojamientosaccesiblesMinimo8() {
		return this.alojamientosaccesiblesMinimo8;
	}

	public void setAlojamientosaccesiblesMinimo8(String alojamientosaccesiblesMinimo8) {
		this.alojamientosaccesiblesMinimo8 = alojamientosaccesiblesMinimo8;
	}

	/**
	 * * (alojamientosaccesibles_observaciones)
	 */

	@Column(name = "alojami_accesibles_obs")
	public String getAlojamientosaccesiblesObservaciones() {
		return this.alojamientosaccesiblesObservaciones;
	}

	public void setAlojamientosaccesiblesObservaciones(String alojamientosaccesiblesObservaciones) {
		this.alojamientosaccesiblesObservaciones = alojamientosaccesiblesObservaciones;
	}

	/**
	 * * (aparcamiento_comercial_porfraccion)
	 */

	@Column(name = "aparc_comercial_porfracc")
	public String getAparcamientoComercialPorfraccion() {
		return this.aparcamientoComercialPorfraccion;
	}

	public void setAparcamientoComercialPorfraccion(String aparcamientoComercialPorfraccion) {
		this.aparcamientoComercialPorfraccion = aparcamientoComercialPorfraccion;
	}

	@Column(name = "aparcamiento_observaciones")
	public String getAparcamientoObservaciones() {
		return this.aparcamientoObservaciones;
	}

	public void setAparcamientoObservaciones(String aparcamientoObservaciones) {
		this.aparcamientoObservaciones = aparcamientoObservaciones;
	}

	/**
	 * * (aparcamiento_otrosusos_minimoaparcamientos_unamasporfraccion)
	 */

	@Column(name = "aparc_otrus_min_unamasporfracc")
	public String getAparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion() {
		return this.aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion;
	}

	public void setAparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion(String aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion) {
		this.aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion = aparcamientoOtrosusosMinimoaparcamientosUnamasporfraccion;
	}

	/**
	 * * (aparcamiento_otrosusos_minimoaparcamientos_unaporfraccion)
	 */

	@Column(name = "aparc_otrus_min_unaporfraccion")
	public String getAparcamientoOtrosusosMinimoaparcamientosUnaporfraccion() {
		return this.aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion;
	}

	public void setAparcamientoOtrosusosMinimoaparcamientosUnaporfraccion(String aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion) {
		this.aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion = aparcamientoOtrosusosMinimoaparcamientosUnaporfraccion;
	}

	/**
	 * * (aparcamiento_residencialpublico_poralojamiento)
	 */

	@Column(name = "aparc_residencial_pub_por_aloj")
	public String getAparcamientoResidencialpublicoPoralojamiento() {
		return this.aparcamientoResidencialpublicoPoralojamiento;
	}

	public void setAparcamientoResidencialpublicoPoralojamiento(String aparcamientoResidencialpublicoPoralojamiento) {
		this.aparcamientoResidencialpublicoPoralojamiento = aparcamientoResidencialpublicoPoralojamiento;
	}

	@Column(name = "aparcamiento_sillaruedas")
	public String getAparcamientoSillaruedas() {
		return this.aparcamientoSillaruedas;
	}

	public void setAparcamientoSillaruedas(String aparcamientoSillaruedas) {
		this.aparcamientoSillaruedas = aparcamientoSillaruedas;
	}

	@Column(name = "entreplantas_accesible")
	public Integer getEntreplantasAccesible() {
		return this.entreplantasAccesible;
	}

	public void setEntreplantasAccesible(Integer entreplantasAccesible) {
		this.entreplantasAccesible = entreplantasAccesible;
	}

	/**
	 * * (entreplantas_accesible_ascensornoaccesible)
	 */

	@Column(name = "entpla_acces_ascensor_no_acc")
	public String getEntreplantasAccesibleAscensornoaccesible() {
		return this.entreplantasAccesibleAscensornoaccesible;
	}

	public void setEntreplantasAccesibleAscensornoaccesible(String entreplantasAccesibleAscensornoaccesible) {
		this.entreplantasAccesibleAscensornoaccesible = entreplantasAccesibleAscensornoaccesible;
	}

	/**
	 * * (entreplantas_accesible_ascensornoaccesible_dimensiones)
	 */

	@Column(name = "entpla_acces_asc_no_acc_dimen")
	public String getEntreplantasAccesibleAscensornoaccesibleDimensiones() {
		return this.entreplantasAccesibleAscensornoaccesibleDimensiones;
	}

	public void setEntreplantasAccesibleAscensornoaccesibleDimensiones(String entreplantasAccesibleAscensornoaccesibleDimensiones) {
		this.entreplantasAccesibleAscensornoaccesibleDimensiones = entreplantasAccesibleAscensornoaccesibleDimensiones;
	}

	/**
	 * * (entreplantas_accesible_ascensororampaaccesible)
	 */

	@Column(name = "entpla_acces_asc_rampa_acc")
	public String getEntreplantasAccesibleAscensororampaaccesible() {
		return this.entreplantasAccesibleAscensororampaaccesible;
	}

	public void setEntreplantasAccesibleAscensororampaaccesible(String entreplantasAccesibleAscensororampaaccesible) {
		this.entreplantasAccesibleAscensororampaaccesible = entreplantasAccesibleAscensororampaaccesible;
	}

	/**
	 * * (entreplantas_accesible_rampaascensornoaccesible)
	 */

	@Column(name = "entpla_acces_rampaasc_no_acc")
	public String getEntreplantasAccesibleRampaascensornoaccesible() {
		return this.entreplantasAccesibleRampaascensornoaccesible;
	}

	public void setEntreplantasAccesibleRampaascensornoaccesible(String entreplantasAccesibleRampaascensornoaccesible) {
		this.entreplantasAccesibleRampaascensornoaccesible = entreplantasAccesibleRampaascensornoaccesible;
	}

	/**
	 * * (entreplantas_elementosaccesibles)
	 */

	@Column(name = "entpla_ele_acc")
	public Integer getEntreplantasElementosaccesibles() {
		return this.entreplantasElementosaccesibles;
	}

	public void setEntreplantasElementosaccesibles(Integer entreplantasElementosaccesibles) {
		this.entreplantasElementosaccesibles = entreplantasElementosaccesibles;
	}

	/**
	 * * (entreplantas_elementosaccesibles_ascensornoaccesible)
	 */

	@Column(name = "entpla_ele_acc_asc_no_acc")
	public String getEntreplantasElementosaccesiblesAscensornoaccesible() {
		return this.entreplantasElementosaccesiblesAscensornoaccesible;
	}

	public void setEntreplantasElementosaccesiblesAscensornoaccesible(String entreplantasElementosaccesiblesAscensornoaccesible) {
		this.entreplantasElementosaccesiblesAscensornoaccesible = entreplantasElementosaccesiblesAscensornoaccesible;
	}

	/**
	 * * (entreplantas_elementosaccesibles_ascensornoaccesible_dimensione)
	 */

	@Column(name = "entpla_ele_acc_asc_no_acc_dim")
	public String getEntreplantasElementosaccesiblesAscensornoaccesibleDimensione() {
		return this.entreplantasElementosaccesiblesAscensornoaccesibleDimensione;
	}

	public void setEntreplantasElementosaccesiblesAscensornoaccesibleDimensione(String entreplantasElementosaccesiblesAscensornoaccesibleDimensione) {
		this.entreplantasElementosaccesiblesAscensornoaccesibleDimensione = entreplantasElementosaccesiblesAscensornoaccesibleDimensione;
	}

	/**
	 * * (entreplantas_elementosaccesibles_ascensororampaaccesible)
	 */

	@Column(name = "entpla_ele_acc_asc_ramp_acc")
	public String getEntreplantasElementosaccesiblesAscensororampaaccesible() {
		return this.entreplantasElementosaccesiblesAscensororampaaccesible;
	}

	public void setEntreplantasElementosaccesiblesAscensororampaaccesible(String entreplantasElementosaccesiblesAscensororampaaccesible) {
		this.entreplantasElementosaccesiblesAscensororampaaccesible = entreplantasElementosaccesiblesAscensororampaaccesible;
	}

	/**
	 * * (entreplantas_elementosaccesibles_rampaascensornoaccesible)
	 */

	@Column(name = "entpla_ele_acc_rampaasc_no_acc")
	public String getEntreplantasElementosaccesiblesRampaascensornoaccesible() {
		return this.entreplantasElementosaccesiblesRampaascensornoaccesible;
	}

	public void setEntreplantasElementosaccesiblesRampaascensornoaccesible(String entreplantasElementosaccesiblesRampaascensornoaccesible) {
		this.entreplantasElementosaccesiblesRampaascensornoaccesible = entreplantasElementosaccesiblesRampaascensornoaccesible;
	}

	@Column(name = "entreplantas_noaccesible")
	public Integer getEntreplantasNoaccesible() {
		return this.entreplantasNoaccesible;
	}

	public void setEntreplantasNoaccesible(Integer entreplantasNoaccesible) {
		this.entreplantasNoaccesible = entreplantasNoaccesible;
	}

	/**
	 * * (entreplantas_noaccesible_ascensornoaccesible)
	 */

	@Column(name = "entpla_no_acc_asc_no_acc")
	public String getEntreplantasNoaccesibleAscensornoaccesible() {
		return this.entreplantasNoaccesibleAscensornoaccesible;
	}

	public void setEntreplantasNoaccesibleAscensornoaccesible(String entreplantasNoaccesibleAscensornoaccesible) {
		this.entreplantasNoaccesibleAscensornoaccesible = entreplantasNoaccesibleAscensornoaccesible;
	}

	/**
	 * * (entreplantas_noaccesible_ascensornoaccesible_dimensiones)
	 */

	@Column(name = "entpla_no_acc_asc_no_acc_dim")
	public String getEntreplantasNoaccesibleAscensornoaccesibleDimensiones() {
		return this.entreplantasNoaccesibleAscensornoaccesibleDimensiones;
	}

	public void setEntreplantasNoaccesibleAscensornoaccesibleDimensiones(String entreplantasNoaccesibleAscensornoaccesibleDimensiones) {
		this.entreplantasNoaccesibleAscensornoaccesibleDimensiones = entreplantasNoaccesibleAscensornoaccesibleDimensiones;
	}

	/**
	 * * (entreplantas_noaccesible_ascensororampaaccesible)
	 */

	@Column(name = "entpla_no_acc_asc_ramp_acc")
	public String getEntreplantasNoaccesibleAscensororampaaccesible() {
		return this.entreplantasNoaccesibleAscensororampaaccesible;
	}

	public void setEntreplantasNoaccesibleAscensororampaaccesible(String entreplantasNoaccesibleAscensororampaaccesible) {
		this.entreplantasNoaccesibleAscensororampaaccesible = entreplantasNoaccesibleAscensororampaaccesible;
	}

	/**
	 * * (entreplantas_noaccesible_rampaascensornoaccesible)
	 */

	@Column(name = "entpla_no_acc_rampaasc_no_acc")
	public String getEntreplantasNoaccesibleRampaascensornoaccesible() {
		return this.entreplantasNoaccesibleRampaascensornoaccesible;
	}

	public void setEntreplantasNoaccesibleRampaascensornoaccesible(String entreplantasNoaccesibleRampaascensornoaccesible) {
		this.entreplantasNoaccesibleRampaascensornoaccesible = entreplantasNoaccesibleRampaascensornoaccesible;
	}

	@Column(name = "entreplantas_observaciones")
	public String getEntreplantasObservaciones() {
		return this.entreplantasObservaciones;
	}

	public void setEntreplantasObservaciones(String entreplantasObservaciones) {
		this.entreplantasObservaciones = entreplantasObservaciones;
	}

	@Column(name = "entreplantas_zonasusopublico")
	public Integer getEntreplantasZonasusopublico() {
		return this.entreplantasZonasusopublico;
	}

	public void setEntreplantasZonasusopublico(Integer entreplantasZonasusopublico) {
		this.entreplantasZonasusopublico = entreplantasZonasusopublico;
	}

	/**
	 * * (entreplantas_zonasusopublico_ascensornoaccesible)
	 */

	@Column(name = "entpla_zon_pub_asc_no_acc")
	public String getEntreplantasZonasusopublicoAscensornoaccesible() {
		return this.entreplantasZonasusopublicoAscensornoaccesible;
	}

	public void setEntreplantasZonasusopublicoAscensornoaccesible(String entreplantasZonasusopublicoAscensornoaccesible) {
		this.entreplantasZonasusopublicoAscensornoaccesible = entreplantasZonasusopublicoAscensornoaccesible;
	}

	/**
	 * * (entreplantas_zonasusopublico_ascensornoaccesible_dimensiones)
	 */

	@Column(name = "entpla_zon_pub_asc_no_acc_dim")
	public String getEntreplantasZonasusopublicoAscensornoaccesibleDimensiones() {
		return this.entreplantasZonasusopublicoAscensornoaccesibleDimensiones;
	}

	public void setEntreplantasZonasusopublicoAscensornoaccesibleDimensiones(String entreplantasZonasusopublicoAscensornoaccesibleDimensiones) {
		this.entreplantasZonasusopublicoAscensornoaccesibleDimensiones = entreplantasZonasusopublicoAscensornoaccesibleDimensiones;
	}

	/**
	 * * (entreplantas_zonasusopublico_ascensororampaaccesible)
	 */

	@Column(name = "entpla_zon_pub_asc_ram_acc")
	public String getEntreplantasZonasusopublicoAscensororampaaccesible() {
		return this.entreplantasZonasusopublicoAscensororampaaccesible;
	}

	public void setEntreplantasZonasusopublicoAscensororampaaccesible(String entreplantasZonasusopublicoAscensororampaaccesible) {
		this.entreplantasZonasusopublicoAscensororampaaccesible = entreplantasZonasusopublicoAscensororampaaccesible;
	}

	/**
	 * * (entreplantas_zonasusopublico_rampaascensornoaccesible)
	 */

	@Column(name = "entpla_zon_pub_rampaasc_no_acc")
	public String getEntreplantasZonasusopublicoRampaascensornoaccesible() {
		return this.entreplantasZonasusopublicoRampaascensornoaccesible;
	}

	public void setEntreplantasZonasusopublicoRampaascensornoaccesible(String entreplantasZonasusopublicoRampaascensornoaccesible) {
		this.entreplantasZonasusopublicoRampaascensornoaccesible = entreplantasZonasusopublicoRampaascensornoaccesible;
	}

	@Column(name = "es_tecnico_inspeccion")
	public Integer getEsTecnicoInspeccion() {
		return this.esTecnicoInspeccion;
	}

	public void setEsTecnicoInspeccion(Integer esTecnicoInspeccion) {
		this.esTecnicoInspeccion = esTecnicoInspeccion;
	}

	/**
	 * * (exterior_edificioitinerarioaccesible_viapublica)
	 */

	@Column(name = "exterior_edi_iti_acc_viapub")
	public Integer getExteriorEdificioitinerarioaccesibleViapublica() {
		return this.exteriorEdificioitinerarioaccesibleViapublica;
	}

	public void setExteriorEdificioitinerarioaccesibleViapublica(Integer exteriorEdificioitinerarioaccesibleViapublica) {
		this.exteriorEdificioitinerarioaccesibleViapublica = exteriorEdificioitinerarioaccesibleViapublica;
	}

	/**
	 * * (exterior_edificioitinerarioaccesible_zonascomunes)
	 */

	@Column(name = "exterior_edi_iti_acc_zonas_com")
	public Integer getExteriorEdificioitinerarioaccesibleZonascomunes() {
		return this.exteriorEdificioitinerarioaccesibleZonascomunes;
	}

	public void setExteriorEdificioitinerarioaccesibleZonascomunes(Integer exteriorEdificioitinerarioaccesibleZonascomunes) {
		this.exteriorEdificioitinerarioaccesibleZonascomunes = exteriorEdificioitinerarioaccesibleZonascomunes;
	}

	@Column(name = "exterior_observaciones")
	public String getExteriorObservaciones() {
		return this.exteriorObservaciones;
	}

	public void setExteriorObservaciones(String exteriorObservaciones) {
		this.exteriorObservaciones = exteriorObservaciones;
	}

	/**
	 * * (informacionsenalizacion_ascensores)
	 */

	@Column(name = "inf_senal_ascen")
	public String getInformacionsenalizacionAscensores() {
		return this.informacionsenalizacionAscensores;
	}

	public void setInformacionsenalizacionAscensores(String informacionsenalizacionAscensores) {
		this.informacionsenalizacionAscensores = informacionsenalizacionAscensores;
	}

	/**
	 * * (informacionsenalizacion_ascensores_brailearabigo)
	 */

	@Column(name = "inf_senal_ascen_brailearabigo")
	public String getInformacionsenalizacionAscensoresBrailearabigo() {
		return this.informacionsenalizacionAscensoresBrailearabigo;
	}

	public void setInformacionsenalizacionAscensoresBrailearabigo(String informacionsenalizacionAscensoresBrailearabigo) {
		this.informacionsenalizacionAscensoresBrailearabigo = informacionsenalizacionAscensoresBrailearabigo;
	}

	/**
	 * * (informacionsenalizacion_ascensores_numeroplanta)
	 */

	@Column(name = "inf_senal_ascen_numeroplanta")
	public String getInformacionsenalizacionAscensoresNumeroplanta() {
		return this.informacionsenalizacionAscensoresNumeroplanta;
	}

	public void setInformacionsenalizacionAscensoresNumeroplanta(String informacionsenalizacionAscensoresNumeroplanta) {
		this.informacionsenalizacionAscensoresNumeroplanta = informacionsenalizacionAscensoresNumeroplanta;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles)
	 */

	@Column(name = "inf_senal_band_vis_tac")
	public String getInformacionsenalizacionBandasvisualestactiles() {
		return this.informacionsenalizacionBandasvisualestactiles;
	}

	public void setInformacionsenalizacionBandasvisualestactiles(String informacionsenalizacionBandasvisualestactiles) {
		this.informacionsenalizacionBandasvisualestactiles = informacionsenalizacionBandasvisualestactiles;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles_arranqueescalera)
	 */

	@Column(name = "inf_senal_band_vis_tac_arr_esc")
	public String getInformacionsenalizacionBandasvisualestactilesArranqueescalera() {
		return this.informacionsenalizacionBandasvisualestactilesArranqueescalera;
	}

	public void setInformacionsenalizacionBandasvisualestactilesArranqueescalera(String informacionsenalizacionBandasvisualestactilesArranqueescalera) {
		this.informacionsenalizacionBandasvisualestactilesArranqueescalera = informacionsenalizacionBandasvisualestactilesArranqueescalera;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles_colorcontrastado)
	 */

	@Column(name = "inf_senal_band_vis_tac_col_con")
	public String getInformacionsenalizacionBandasvisualestactilesColorcontrastado() {
		return this.informacionsenalizacionBandasvisualestactilesColorcontrastado;
	}

	public void setInformacionsenalizacionBandasvisualestactilesColorcontrastado(String informacionsenalizacionBandasvisualestactilesColorcontrastado) {
		this.informacionsenalizacionBandasvisualestactilesColorcontrastado = informacionsenalizacionBandasvisualestactilesColorcontrastado;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles_itinerarioaccesi)
	 */

	@Column(name = "inf_senal_band_vis_tac_iti_acc")
	public String getInformacionsenalizacionBandasvisualestactilesItinerarioaccesi() {
		return this.informacionsenalizacionBandasvisualestactilesItinerarioaccesi;
	}

	public void setInformacionsenalizacionBandasvisualestactilesItinerarioaccesi(String informacionsenalizacionBandasvisualestactilesItinerarioaccesi) {
		this.informacionsenalizacionBandasvisualestactilesItinerarioaccesi = informacionsenalizacionBandasvisualestactilesItinerarioaccesi;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles_relieveexterior)
	 */

	@Column(name = "inf_senal_band_vis_tac_rel_ext")
	public String getInformacionsenalizacionBandasvisualestactilesRelieveexterior() {
		return this.informacionsenalizacionBandasvisualestactilesRelieveexterior;
	}

	public void setInformacionsenalizacionBandasvisualestactilesRelieveexterior(String informacionsenalizacionBandasvisualestactilesRelieveexterior) {
		this.informacionsenalizacionBandasvisualestactilesRelieveexterior = informacionsenalizacionBandasvisualestactilesRelieveexterior;
	}

	/**
	 * * (informacionsenalizacion_bandasvisualestactiles_relieveinterior)
	 */

	@Column(name = "inf_senal_band_vis_tac_rel_int")
	public String getInformacionsenalizacionBandasvisualestactilesRelieveinterior() {
		return this.informacionsenalizacionBandasvisualestactilesRelieveinterior;
	}

	public void setInformacionsenalizacionBandasvisualestactilesRelieveinterior(String informacionsenalizacionBandasvisualestactilesRelieveinterior) {
		this.informacionsenalizacionBandasvisualestactilesRelieveinterior = informacionsenalizacionBandasvisualestactilesRelieveinterior;
	}

	/**
	 * * (informacionsenalizacion_buclemagnetico)
	 */

	@Column(name = "inf_senal_buclemagnetico")
	public String getInformacionsenalizacionBuclemagnetico() {
		return this.informacionsenalizacionBuclemagnetico;
	}

	public void setInformacionsenalizacionBuclemagnetico(String informacionsenalizacionBuclemagnetico) {
		this.informacionsenalizacionBuclemagnetico = informacionsenalizacionBuclemagnetico;
	}

	/**
	 * * (informacionsenalizacion_buclemagnetico_senalizado)
	 */

	@Column(name = "inf_senal_buclemagnetico_senal")
	public String getInformacionsenalizacionBuclemagneticoSenalizado() {
		return this.informacionsenalizacionBuclemagneticoSenalizado;
	}

	public void setInformacionsenalizacionBuclemagneticoSenalizado(String informacionsenalizacionBuclemagneticoSenalizado) {
		this.informacionsenalizacionBuclemagneticoSenalizado = informacionsenalizacionBuclemagneticoSenalizado;
	}

	/**
	 * * (informacionsenalizacion_observaciones)
	 */

	@Column(name = "inf_senal_observaciones")
	public String getInformacionsenalizacionObservaciones() {
		return this.informacionsenalizacionObservaciones;
	}

	public void setInformacionsenalizacionObservaciones(String informacionsenalizacionObservaciones) {
		this.informacionsenalizacionObservaciones = informacionsenalizacionObservaciones;
	}

	/**
	 * * (informacionsenalizacion_privado_sia_aparcamiento)
	 */

	@Column(name = "inf_senal_priv_sia_aparc")
	public String getInformacionsenalizacionPrivadoSiaAparcamiento() {
		return this.informacionsenalizacionPrivadoSiaAparcamiento;
	}

	public void setInformacionsenalizacionPrivadoSiaAparcamiento(String informacionsenalizacionPrivadoSiaAparcamiento) {
		this.informacionsenalizacionPrivadoSiaAparcamiento = informacionsenalizacionPrivadoSiaAparcamiento;
	}

	/**
	 * * (informacionsenalizacion_privado_sia_ascensores)
	 */

	@Column(name = "inf_senal_priv_sia_ascen")
	public String getInformacionsenalizacionPrivadoSiaAscensores() {
		return this.informacionsenalizacionPrivadoSiaAscensores;
	}

	public void setInformacionsenalizacionPrivadoSiaAscensores(String informacionsenalizacionPrivadoSiaAscensores) {
		this.informacionsenalizacionPrivadoSiaAscensores = informacionsenalizacionPrivadoSiaAscensores;
	}

	/**
	 * * (informacionsenalizacion_privado_sia_entradas)
	 */

	@Column(name = "inf_senal_priv_sia_entradas")
	public String getInformacionsenalizacionPrivadoSiaEntradas() {
		return this.informacionsenalizacionPrivadoSiaEntradas;
	}

	public void setInformacionsenalizacionPrivadoSiaEntradas(String informacionsenalizacionPrivadoSiaEntradas) {
		this.informacionsenalizacionPrivadoSiaEntradas = informacionsenalizacionPrivadoSiaEntradas;
	}

	/**
	 * * (informacionsenalizacion_privado_sia_itinerarios)
	 */

	@Column(name = "inf_senal_priv_sia_itiner")
	public String getInformacionsenalizacionPrivadoSiaItinerarios() {
		return this.informacionsenalizacionPrivadoSiaItinerarios;
	}

	public void setInformacionsenalizacionPrivadoSiaItinerarios(String informacionsenalizacionPrivadoSiaItinerarios) {
		this.informacionsenalizacionPrivadoSiaItinerarios = informacionsenalizacionPrivadoSiaItinerarios;
	}

	/**
	 * * (informacionsenalizacion_privado_sia_plazasreservadas)
	 */

	@Column(name = "inf_senal_priv_sia_plaz_res")
	public String getInformacionsenalizacionPrivadoSiaPlazasreservadas() {
		return this.informacionsenalizacionPrivadoSiaPlazasreservadas;
	}

	public void setInformacionsenalizacionPrivadoSiaPlazasreservadas(String informacionsenalizacionPrivadoSiaPlazasreservadas) {
		this.informacionsenalizacionPrivadoSiaPlazasreservadas = informacionsenalizacionPrivadoSiaPlazasreservadas;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_aparcamiento)
	 */

	@Column(name = "inf_senal_pub_sia_aparcamiento")
	public String getInformacionsenalizacionPublicoSiaAparcamiento() {
		return this.informacionsenalizacionPublicoSiaAparcamiento;
	}

	public void setInformacionsenalizacionPublicoSiaAparcamiento(String informacionsenalizacionPublicoSiaAparcamiento) {
		this.informacionsenalizacionPublicoSiaAparcamiento = informacionsenalizacionPublicoSiaAparcamiento;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_ascensores)
	 */

	@Column(name = "inf_senal_pub_sia_ascens")
	public String getInformacionsenalizacionPublicoSiaAscensores() {
		return this.informacionsenalizacionPublicoSiaAscensores;
	}

	public void setInformacionsenalizacionPublicoSiaAscensores(String informacionsenalizacionPublicoSiaAscensores) {
		this.informacionsenalizacionPublicoSiaAscensores = informacionsenalizacionPublicoSiaAscensores;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_entradas)
	 */

	@Column(name = "inf_senal_pub_sia_entradas")
	public String getInformacionsenalizacionPublicoSiaEntradas() {
		return this.informacionsenalizacionPublicoSiaEntradas;
	}

	public void setInformacionsenalizacionPublicoSiaEntradas(String informacionsenalizacionPublicoSiaEntradas) {
		this.informacionsenalizacionPublicoSiaEntradas = informacionsenalizacionPublicoSiaEntradas;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_itinerarios)
	 */

	@Column(name = "inf_senal_pub_sia_itiner")
	public String getInformacionsenalizacionPublicoSiaItinerarios() {
		return this.informacionsenalizacionPublicoSiaItinerarios;
	}

	public void setInformacionsenalizacionPublicoSiaItinerarios(String informacionsenalizacionPublicoSiaItinerarios) {
		this.informacionsenalizacionPublicoSiaItinerarios = informacionsenalizacionPublicoSiaItinerarios;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_plazasreservadas)
	 */

	@Column(name = "inf_senal_pub_sia_plaz_res")
	public String getInformacionsenalizacionPublicoSiaPlazasreservadas() {
		return this.informacionsenalizacionPublicoSiaPlazasreservadas;
	}

	public void setInformacionsenalizacionPublicoSiaPlazasreservadas(String informacionsenalizacionPublicoSiaPlazasreservadas) {
		this.informacionsenalizacionPublicoSiaPlazasreservadas = informacionsenalizacionPublicoSiaPlazasreservadas;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_puntosatencion)
	 */

	@Column(name = "inf_senal_pub_sia_pun_aten")
	public String getInformacionsenalizacionPublicoSiaPuntosatencion() {
		return this.informacionsenalizacionPublicoSiaPuntosatencion;
	}

	public void setInformacionsenalizacionPublicoSiaPuntosatencion(String informacionsenalizacionPublicoSiaPuntosatencion) {
		this.informacionsenalizacionPublicoSiaPuntosatencion = informacionsenalizacionPublicoSiaPuntosatencion;
	}

	/**
	 * * (informacionsenalizacion_publico_sia_servicioshigienicos)
	 */

	@Column(name = "inf_senal_pub_sia_ser_hig")
	public String getInformacionsenalizacionPublicoSiaServicioshigienicos() {
		return this.informacionsenalizacionPublicoSiaServicioshigienicos;
	}

	public void setInformacionsenalizacionPublicoSiaServicioshigienicos(String informacionsenalizacionPublicoSiaServicioshigienicos) {
		this.informacionsenalizacionPublicoSiaServicioshigienicos = informacionsenalizacionPublicoSiaServicioshigienicos;
	}

	/**
	 * * (informacionsenalizacion_servicioshigienicossenalizados)
	 */

	@Column(name = "inf_senal_ser_hig_senal")
	public String getInformacionsenalizacionServicioshigienicossenalizados() {
		return this.informacionsenalizacionServicioshigienicossenalizados;
	}

	public void setInformacionsenalizacionServicioshigienicossenalizados(String informacionsenalizacionServicioshigienicossenalizados) {
		this.informacionsenalizacionServicioshigienicossenalizados = informacionsenalizacionServicioshigienicossenalizados;
	}

	/**
	 * * (informacionsenalizacion_sianorma)
	 */

	@Column(name = "inf_senal_sianorma")
	public String getInformacionsenalizacionSianorma() {
		return this.informacionsenalizacionSianorma;
	}

	public void setInformacionsenalizacionSianorma(String informacionsenalizacionSianorma) {
		this.informacionsenalizacionSianorma = informacionsenalizacionSianorma;
	}

	/**
	 * * (informacionsenalizacion_todosusos_observaciones)
	 */

	@Column(name = "inf_senal_todosusos_obs")
	public String getInformacionsenalizacionTodosusosObservaciones() {
		return this.informacionsenalizacionTodosusosObservaciones;
	}

	public void setInformacionsenalizacionTodosusosObservaciones(String informacionsenalizacionTodosusosObservaciones) {
		this.informacionsenalizacionTodosusosObservaciones = informacionsenalizacionTodosusosObservaciones;
	}

	@Column(name = "mecanismos_accesibles")
	public String getMecanismosAccesibles() {
		return this.mecanismosAccesibles;
	}

	public void setMecanismosAccesibles(String mecanismosAccesibles) {
		this.mecanismosAccesibles = mecanismosAccesibles;
	}

	@Column(name = "mecanismos_observaciones")
	public String getMecanismosObservaciones() {
		return this.mecanismosObservaciones;
	}

	public void setMecanismosObservaciones(String mecanismosObservaciones) {
		this.mecanismosObservaciones = mecanismosObservaciones;
	}

	@Column(name = "mobiliariofijo_observaciones")
	public String getMobiliariofijoObservaciones() {
		return this.mobiliariofijoObservaciones;
	}

	public void setMobiliariofijoObservaciones(String mobiliariofijoObservaciones) {
		this.mobiliariofijoObservaciones = mobiliariofijoObservaciones;
	}

	@Column(name = "mobiliariofijo_puntoaccesible")
	public String getMobiliariofijoPuntoaccesible() {
		return this.mobiliariofijoPuntoaccesible;
	}

	public void setMobiliariofijoPuntoaccesible(String mobiliariofijoPuntoaccesible) {
		this.mobiliariofijoPuntoaccesible = mobiliariofijoPuntoaccesible;
	}

	@Column(name = "nif")
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "piscinas_entradaaccesible")
	public String getPiscinasEntradaaccesible() {
		return this.piscinasEntradaaccesible;
	}

	public void setPiscinasEntradaaccesible(String piscinasEntradaaccesible) {
		this.piscinasEntradaaccesible = piscinasEntradaaccesible;
	}

	@Column(name = "piscinas_observaciones")
	public String getPiscinasObservaciones() {
		return this.piscinasObservaciones;
	}

	public void setPiscinasObservaciones(String piscinasObservaciones) {
		this.piscinasObservaciones = piscinasObservaciones;
	}

	/**
	 * * (plantas_itinerarioaccesible_elementosaccesibles)
	 */

	@Column(name = "plantas_itin_acc_elem_acc")
	public Integer getPlantasItinerarioaccesibleElementosaccesibles() {
		return this.plantasItinerarioaccesibleElementosaccesibles;
	}

	public void setPlantasItinerarioaccesibleElementosaccesibles(Integer plantasItinerarioaccesibleElementosaccesibles) {
		this.plantasItinerarioaccesibleElementosaccesibles = plantasItinerarioaccesibleElementosaccesibles;
	}

	/**
	 * * (plantas_itinerarioaccesible_entresi)
	 */

	@Column(name = "plantas_itin_acc_entresi")
	public Integer getPlantasItinerarioaccesibleEntresi() {
		return this.plantasItinerarioaccesibleEntresi;
	}

	public void setPlantasItinerarioaccesibleEntresi(Integer plantasItinerarioaccesibleEntresi) {
		this.plantasItinerarioaccesibleEntresi = plantasItinerarioaccesibleEntresi;
	}

	/**
	 * * (plantas_itinerarioaccesible_observaciones)
	 */

	@Column(name = "plantas_itin_acc_observaciones")
	public String getPlantasItinerarioaccesibleObservaciones() {
		return this.plantasItinerarioaccesibleObservaciones;
	}

	public void setPlantasItinerarioaccesibleObservaciones(String plantasItinerarioaccesibleObservaciones) {
		this.plantasItinerarioaccesibleObservaciones = plantasItinerarioaccesibleObservaciones;
	}

	/**
	 * * (plantas_itinerarioaccesible_zonasusoprivado)
	 */

	@Column(name = "plantas_itin_acc_zon_uso_priv")
	public Integer getPlantasItinerarioaccesibleZonasusoprivado() {
		return this.plantasItinerarioaccesibleZonasusoprivado;
	}

	public void setPlantasItinerarioaccesibleZonasusoprivado(Integer plantasItinerarioaccesibleZonasusoprivado) {
		this.plantasItinerarioaccesibleZonasusoprivado = plantasItinerarioaccesibleZonasusoprivado;
	}

	/**
	 * * (plantas_itinerarioaccesible_zonasusopublico)
	 */

	@Column(name = "plantas_itin_acc_zon_pub")
	public Integer getPlantasItinerarioaccesibleZonasusopublico() {
		return this.plantasItinerarioaccesibleZonasusopublico;
	}

	public void setPlantasItinerarioaccesibleZonasusopublico(Integer plantasItinerarioaccesibleZonasusopublico) {
		this.plantasItinerarioaccesibleZonasusopublico = plantasItinerarioaccesibleZonasusopublico;
	}

	/**
	 * * (plazasreservadas_discapacidadauditiva)
	 */

	@Column(name = "plaz_res_discapacidadauditiva")
	public String getPlazasreservadasDiscapacidadauditiva() {
		return this.plazasreservadasDiscapacidadauditiva;
	}

	public void setPlazasreservadasDiscapacidadauditiva(String plazasreservadasDiscapacidadauditiva) {
		this.plazasreservadasDiscapacidadauditiva = plazasreservadasDiscapacidadauditiva;
	}

	/**
	 * * (plazasreservadas_observaciones)
	 */

	@Column(name = "plaz_res_observaciones")
	public String getPlazasreservadasObservaciones() {
		return this.plazasreservadasObservaciones;
	}

	public void setPlazasreservadasObservaciones(String plazasreservadasObservaciones) {
		this.plazasreservadasObservaciones = plazasreservadasObservaciones;
	}

	@Column(name = "plazasreservadas_sillaruedas")
	public String getPlazasreservadasSillaruedas() {
		return this.plazasreservadasSillaruedas;
	}

	public void setPlazasreservadasSillaruedas(String plazasreservadasSillaruedas) {
		this.plazasreservadasSillaruedas = plazasreservadasSillaruedas;
	}

	/**
	 * * (plazasreservadas_zonaespera_sillaruedas)
	 */

	@Column(name = "plaz_res_zona_esp_sillaruedas")
	public String getPlazasreservadasZonaesperaSillaruedas() {
		return this.plazasreservadasZonaesperaSillaruedas;
	}

	public void setPlazasreservadasZonaesperaSillaruedas(String plazasreservadasZonaesperaSillaruedas) {
		this.plazasreservadasZonaesperaSillaruedas = plazasreservadasZonaesperaSillaruedas;
	}

	/**
	 * * (servicioshigienicos_aseoaccesible)
	 */

	@Column(name = "serv_hig_aseoaccesible")
	public String getServicioshigienicosAseoaccesible() {
		return this.servicioshigienicosAseoaccesible;
	}

	public void setServicioshigienicosAseoaccesible(String servicioshigienicosAseoaccesible) {
		this.servicioshigienicosAseoaccesible = servicioshigienicosAseoaccesible;
	}

	/**
	 * * (servicioshigienicos_cabinaduchaaccesibles)
	 */

	@Column(name = "serv_hig_cab_ducha_acc")
	public String getServicioshigienicosCabinaduchaaccesibles() {
		return this.servicioshigienicosCabinaduchaaccesibles;
	}

	public void setServicioshigienicosCabinaduchaaccesibles(String servicioshigienicosCabinaduchaaccesibles) {
		this.servicioshigienicosCabinaduchaaccesibles = servicioshigienicosCabinaduchaaccesibles;
	}

	/**
	 * * (servicioshigienicos_observaciones)
	 */

	@Column(name = "serv_hig_observaciones")
	public String getServicioshigienicosObservaciones() {
		return this.servicioshigienicosObservaciones;
	}

	public void setServicioshigienicosObservaciones(String servicioshigienicosObservaciones) {
		this.servicioshigienicosObservaciones = servicioshigienicosObservaciones;
	}

	@Column(name = "tecnico")
	public String getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(String tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "titulacion")
	public String getTitulacion() {
		return this.titulacion;
	}

	public void setTitulacion(String titulacion) {
		this.titulacion = titulacion;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccesibilidadPublicos))
			return false;
		AccesibilidadPublicos castOther = (AccesibilidadPublicos) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
