package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * AcusticaRuidosInterioresVerticales generated by hbm2java
 */
@Entity
@Table(name = "aed_acu_ruiintvert")
public class AcusticaRuidosInterioresVerticales extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	/**
	 * (acustica_ruidointeriorverticales_separacion_tipo_texto)
	 */
	private String ruiiIntVertSepTipoTex;
	/**
	 * (acustica_ruidointeriorverticales_tabiques_tipo_texto)
	 */
	private String ruiIntVertTabTipoTex;
	/**
	 * (caracteristicas_huecos_adosados)
	 */
	private Integer caracteristicasHuecosAdosados;
	/**
	 * (caracteristicas_huecos_adosados_revestidos)
	 */
	private Integer caracteristicasHuecosAdosadosRevestidos;
	/**
	 * (caracteristicas_huecos_adosados_ruido_molesto)
	 */
	private Integer caracteristicasHuecosAdosadosRuidoMolesto;
	/**
	 * (caracteristicas_instalaciones_atraviesan_recintos)
	 */
	private Integer caracteristicasInstalacionesAtraviesanRecintos;
	/**
	 * (caracteristicas_instalaciones_conectan_recintos)
	 */
	private Integer caracteristicasInstalacionesConectanRecintos;
	/**
	 * (caracteristicas_pilares_conectan_recintos)
	 */
	private Integer caracteristicasPilaresConectanRecintos;
	/**
	 * (caracteristicas_pilares_conectan_recintos_revestidos)
	 */
	private Integer caracteristicasPilaresConectanRecintosRevestidos;
	/**
	 * (caracteristicas_tuberias_ancladas)
	 */
	private Integer caracteristicasTuberiasAncladas;
	private String deficienciasObservaciones;
	private Integer estadoSeparacionBueno;
	private String observaciones;
	/**
	 * (separacion_entramado_autoportante)
	 */
	private Integer separacionEntramadoAutoportante;
	/**
	 * (separacion_entramado_autoportante_absorbente)
	 */
	private Integer separacionEntramadoAutoportanteAbsorbente;
	/**
	 * (separacion_entramado_autoportante_doshojas)
	 */
	private Integer separacionEntramadoAutoportanteDoshojas;
	/**
	 * (separacion_entramado_autoportante_doshojas_espesor)
	 */
	private String separacionEntramadoAutoportanteDoshojasEspesor;
	/**
	 * (separacion_entramado_autoportante_unahoja)
	 */
	private Integer separacionEntramadoAutoportanteUnahoja;
	/**
	 * (separacion_entramado_autoportante_unahoja_espesor)
	 */
	private String separacionEntramadoAutoportanteUnahojaEspesor;
	private Integer separacionEntramadoMadera;
	/**
	 * (separacion_entramado_madera_espesor)
	 */
	private Integer separacionEntramadoMaderaEspesor;
	/**
	 * (separacion_entramado_madera_revestido)
	 */
	private Integer separacionEntramadoMaderaRevestido;
	private Integer separacionFabrica;
	private Integer separacionFabricaRevestido;
	private Integer separacionOtros;
	private String separacionOtrosTexto;
	/**
	 * (tabiques_entramado_autoportante_metalico)
	 */
	private Integer tabiquesEntramadoAutoportanteMetalico;
	/**
	 * (tabiques_entramado_autoportante_metalico_espesor)
	 */
	private String tabiquesEntramadoAutoportanteMetalicoEspesor;
	/**
	 * (tabiques_entramado_madera_relleno)
	 */
	private Integer tabiquesEntramadoMaderaRelleno;
	/**
	 * (tabiques_entramado_madera_relleno_espesor)
	 */
	private String tabiquesEntramadoMaderaRellenoEspesor;
	private Integer tabiquesFabrica;
	private Integer zonaComunHallPuerta;
	/**
	 * (zona_comun_puertas_acusticamente_favorables)
	 */
	private Integer zonaComunPuertasAcusticamenteFavorables;

	public AcusticaRuidosInterioresVerticales() {
	}

	public AcusticaRuidosInterioresVerticales(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public AcusticaRuidosInterioresVerticales(Inspeccion inspeccion, String ruiiIntVertSepTipoTex, String ruiIntVertTabTipoTex, Integer caracteristicasHuecosAdosados, Integer caracteristicasHuecosAdosadosRevestidos, Integer caracteristicasHuecosAdosadosRuidoMolesto, Integer caracteristicasInstalacionesAtraviesanRecintos, Integer caracteristicasInstalacionesConectanRecintos, Integer caracteristicasPilaresConectanRecintos, Integer caracteristicasPilaresConectanRecintosRevestidos, Integer caracteristicasTuberiasAncladas, String deficienciasObservaciones, Integer estadoSeparacionBueno, String observaciones, Integer separacionEntramadoAutoportante, Integer separacionEntramadoAutoportanteAbsorbente, Integer separacionEntramadoAutoportanteDoshojas, String separacionEntramadoAutoportanteDoshojasEspesor, Integer separacionEntramadoAutoportanteUnahoja, String separacionEntramadoAutoportanteUnahojaEspesor, Integer separacionEntramadoMadera, Integer separacionEntramadoMaderaEspesor, Integer separacionEntramadoMaderaRevestido, Integer separacionFabrica, Integer separacionFabricaRevestido, Integer separacionOtros, String separacionOtrosTexto, Integer tabiquesEntramadoAutoportanteMetalico, String tabiquesEntramadoAutoportanteMetalicoEspesor, Integer tabiquesEntramadoMaderaRelleno, String tabiquesEntramadoMaderaRellenoEspesor, Integer tabiquesFabrica, Integer zonaComunHallPuerta, Integer zonaComunPuertasAcusticamenteFavorables) {
		this.inspeccion = inspeccion;
		this.ruiiIntVertSepTipoTex = ruiiIntVertSepTipoTex;
		this.ruiIntVertTabTipoTex = ruiIntVertTabTipoTex;
		this.caracteristicasHuecosAdosados = caracteristicasHuecosAdosados;
		this.caracteristicasHuecosAdosadosRevestidos = caracteristicasHuecosAdosadosRevestidos;
		this.caracteristicasHuecosAdosadosRuidoMolesto = caracteristicasHuecosAdosadosRuidoMolesto;
		this.caracteristicasInstalacionesAtraviesanRecintos = caracteristicasInstalacionesAtraviesanRecintos;
		this.caracteristicasInstalacionesConectanRecintos = caracteristicasInstalacionesConectanRecintos;
		this.caracteristicasPilaresConectanRecintos = caracteristicasPilaresConectanRecintos;
		this.caracteristicasPilaresConectanRecintosRevestidos = caracteristicasPilaresConectanRecintosRevestidos;
		this.caracteristicasTuberiasAncladas = caracteristicasTuberiasAncladas;
		this.deficienciasObservaciones = deficienciasObservaciones;
		this.estadoSeparacionBueno = estadoSeparacionBueno;
		this.observaciones = observaciones;
		this.separacionEntramadoAutoportante = separacionEntramadoAutoportante;
		this.separacionEntramadoAutoportanteAbsorbente = separacionEntramadoAutoportanteAbsorbente;
		this.separacionEntramadoAutoportanteDoshojas = separacionEntramadoAutoportanteDoshojas;
		this.separacionEntramadoAutoportanteDoshojasEspesor = separacionEntramadoAutoportanteDoshojasEspesor;
		this.separacionEntramadoAutoportanteUnahoja = separacionEntramadoAutoportanteUnahoja;
		this.separacionEntramadoAutoportanteUnahojaEspesor = separacionEntramadoAutoportanteUnahojaEspesor;
		this.separacionEntramadoMadera = separacionEntramadoMadera;
		this.separacionEntramadoMaderaEspesor = separacionEntramadoMaderaEspesor;
		this.separacionEntramadoMaderaRevestido = separacionEntramadoMaderaRevestido;
		this.separacionFabrica = separacionFabrica;
		this.separacionFabricaRevestido = separacionFabricaRevestido;
		this.separacionOtros = separacionOtros;
		this.separacionOtrosTexto = separacionOtrosTexto;
		this.tabiquesEntramadoAutoportanteMetalico = tabiquesEntramadoAutoportanteMetalico;
		this.tabiquesEntramadoAutoportanteMetalicoEspesor = tabiquesEntramadoAutoportanteMetalicoEspesor;
		this.tabiquesEntramadoMaderaRelleno = tabiquesEntramadoMaderaRelleno;
		this.tabiquesEntramadoMaderaRellenoEspesor = tabiquesEntramadoMaderaRellenoEspesor;
		this.tabiquesFabrica = tabiquesFabrica;
		this.zonaComunHallPuerta = zonaComunHallPuerta;
		this.zonaComunPuertasAcusticamenteFavorables = zonaComunPuertasAcusticamenteFavorables;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (acustica_ruidointeriorverticales_separacion_tipo_texto)
	 */

	@Column(name = "acu_ruii_int_vert_sep_tipo_tex")
	public String getRuiiIntVertSepTipoTex() {
		return this.ruiiIntVertSepTipoTex;
	}

	public void setRuiiIntVertSepTipoTex(String ruiiIntVertSepTipoTex) {
		this.ruiiIntVertSepTipoTex = ruiiIntVertSepTipoTex;
	}

	/**
	 * * (acustica_ruidointeriorverticales_tabiques_tipo_texto)
	 */

	@Column(name = "acu_rui_int_vert_tab_tipo_tex")
	public String getRuiIntVertTabTipoTex() {
		return this.ruiIntVertTabTipoTex;
	}

	public void setRuiIntVertTabTipoTex(String ruiIntVertTabTipoTex) {
		this.ruiIntVertTabTipoTex = ruiIntVertTabTipoTex;
	}

	/**
	 * * (caracteristicas_huecos_adosados)
	 */

	@Column(name = "cars_huecos_adosados")
	public Integer getCaracteristicasHuecosAdosados() {
		return this.caracteristicasHuecosAdosados;
	}

	public void setCaracteristicasHuecosAdosados(Integer caracteristicasHuecosAdosados) {
		this.caracteristicasHuecosAdosados = caracteristicasHuecosAdosados;
	}

	/**
	 * * (caracteristicas_huecos_adosados_revestidos)
	 */

	@Column(name = "cars_huecos_adosados_revestido")
	public Integer getCaracteristicasHuecosAdosadosRevestidos() {
		return this.caracteristicasHuecosAdosadosRevestidos;
	}

	public void setCaracteristicasHuecosAdosadosRevestidos(Integer caracteristicasHuecosAdosadosRevestidos) {
		this.caracteristicasHuecosAdosadosRevestidos = caracteristicasHuecosAdosadosRevestidos;
	}

	/**
	 * * (caracteristicas_huecos_adosados_ruido_molesto)
	 */

	@Column(name = "cars_huecos_adosados_rui_moles")
	public Integer getCaracteristicasHuecosAdosadosRuidoMolesto() {
		return this.caracteristicasHuecosAdosadosRuidoMolesto;
	}

	public void setCaracteristicasHuecosAdosadosRuidoMolesto(Integer caracteristicasHuecosAdosadosRuidoMolesto) {
		this.caracteristicasHuecosAdosadosRuidoMolesto = caracteristicasHuecosAdosadosRuidoMolesto;
	}

	/**
	 * * (caracteristicas_instalaciones_atraviesan_recintos)
	 */

	@Column(name = "cars_instal_atraviesan_rec")
	public Integer getCaracteristicasInstalacionesAtraviesanRecintos() {
		return this.caracteristicasInstalacionesAtraviesanRecintos;
	}

	public void setCaracteristicasInstalacionesAtraviesanRecintos(Integer caracteristicasInstalacionesAtraviesanRecintos) {
		this.caracteristicasInstalacionesAtraviesanRecintos = caracteristicasInstalacionesAtraviesanRecintos;
	}

	/**
	 * * (caracteristicas_instalaciones_conectan_recintos)
	 */

	@Column(name = "cars_instal_conectan_rec")
	public Integer getCaracteristicasInstalacionesConectanRecintos() {
		return this.caracteristicasInstalacionesConectanRecintos;
	}

	public void setCaracteristicasInstalacionesConectanRecintos(Integer caracteristicasInstalacionesConectanRecintos) {
		this.caracteristicasInstalacionesConectanRecintos = caracteristicasInstalacionesConectanRecintos;
	}

	/**
	 * * (caracteristicas_pilares_conectan_recintos)
	 */

	@Column(name = "cars_pilares_conectan_rec")
	public Integer getCaracteristicasPilaresConectanRecintos() {
		return this.caracteristicasPilaresConectanRecintos;
	}

	public void setCaracteristicasPilaresConectanRecintos(Integer caracteristicasPilaresConectanRecintos) {
		this.caracteristicasPilaresConectanRecintos = caracteristicasPilaresConectanRecintos;
	}

	/**
	 * * (caracteristicas_pilares_conectan_recintos_revestidos)
	 */

	@Column(name = "cars_pilares_conecta_rec_reves")
	public Integer getCaracteristicasPilaresConectanRecintosRevestidos() {
		return this.caracteristicasPilaresConectanRecintosRevestidos;
	}

	public void setCaracteristicasPilaresConectanRecintosRevestidos(Integer caracteristicasPilaresConectanRecintosRevestidos) {
		this.caracteristicasPilaresConectanRecintosRevestidos = caracteristicasPilaresConectanRecintosRevestidos;
	}

	/**
	 * * (caracteristicas_tuberias_ancladas)
	 */

	@Column(name = "caracteristicas_tuberias_ancl")
	public Integer getCaracteristicasTuberiasAncladas() {
		return this.caracteristicasTuberiasAncladas;
	}

	public void setCaracteristicasTuberiasAncladas(Integer caracteristicasTuberiasAncladas) {
		this.caracteristicasTuberiasAncladas = caracteristicasTuberiasAncladas;
	}

	@Column(name = "deficiencias_observaciones")
	public String getDeficienciasObservaciones() {
		return this.deficienciasObservaciones;
	}

	public void setDeficienciasObservaciones(String deficienciasObservaciones) {
		this.deficienciasObservaciones = deficienciasObservaciones;
	}

	@Column(name = "estado_separacion_bueno")
	public Integer getEstadoSeparacionBueno() {
		return this.estadoSeparacionBueno;
	}

	public void setEstadoSeparacionBueno(Integer estadoSeparacionBueno) {
		this.estadoSeparacionBueno = estadoSeparacionBueno;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * * (separacion_entramado_autoportante)
	 */

	@Column(name = "sep_entramado_autoportante")
	public Integer getSeparacionEntramadoAutoportante() {
		return this.separacionEntramadoAutoportante;
	}

	public void setSeparacionEntramadoAutoportante(Integer separacionEntramadoAutoportante) {
		this.separacionEntramadoAutoportante = separacionEntramadoAutoportante;
	}

	/**
	 * * (separacion_entramado_autoportante_absorbente)
	 */

	@Column(name = "sep_entr_autopor_absor")
	public Integer getSeparacionEntramadoAutoportanteAbsorbente() {
		return this.separacionEntramadoAutoportanteAbsorbente;
	}

	public void setSeparacionEntramadoAutoportanteAbsorbente(Integer separacionEntramadoAutoportanteAbsorbente) {
		this.separacionEntramadoAutoportanteAbsorbente = separacionEntramadoAutoportanteAbsorbente;
	}

	/**
	 * * (separacion_entramado_autoportante_doshojas)
	 */

	@Column(name = "sep_entr_autopor_doshojas")
	public Integer getSeparacionEntramadoAutoportanteDoshojas() {
		return this.separacionEntramadoAutoportanteDoshojas;
	}

	public void setSeparacionEntramadoAutoportanteDoshojas(Integer separacionEntramadoAutoportanteDoshojas) {
		this.separacionEntramadoAutoportanteDoshojas = separacionEntramadoAutoportanteDoshojas;
	}

	/**
	 * * (separacion_entramado_autoportante_doshojas_espesor)
	 */

	@Column(name = "sep_entr_autopor_doshojas_esp")
	public String getSeparacionEntramadoAutoportanteDoshojasEspesor() {
		return this.separacionEntramadoAutoportanteDoshojasEspesor;
	}

	public void setSeparacionEntramadoAutoportanteDoshojasEspesor(String separacionEntramadoAutoportanteDoshojasEspesor) {
		this.separacionEntramadoAutoportanteDoshojasEspesor = separacionEntramadoAutoportanteDoshojasEspesor;
	}

	/**
	 * * (separacion_entramado_autoportante_unahoja)
	 */

	@Column(name = "sep_entr_autopor_unahoja")
	public Integer getSeparacionEntramadoAutoportanteUnahoja() {
		return this.separacionEntramadoAutoportanteUnahoja;
	}

	public void setSeparacionEntramadoAutoportanteUnahoja(Integer separacionEntramadoAutoportanteUnahoja) {
		this.separacionEntramadoAutoportanteUnahoja = separacionEntramadoAutoportanteUnahoja;
	}

	/**
	 * * (separacion_entramado_autoportante_unahoja_espesor)
	 */

	@Column(name = "sep_entr_autopor_unahoja_esp")
	public String getSeparacionEntramadoAutoportanteUnahojaEspesor() {
		return this.separacionEntramadoAutoportanteUnahojaEspesor;
	}

	public void setSeparacionEntramadoAutoportanteUnahojaEspesor(String separacionEntramadoAutoportanteUnahojaEspesor) {
		this.separacionEntramadoAutoportanteUnahojaEspesor = separacionEntramadoAutoportanteUnahojaEspesor;
	}

	@Column(name = "separacion_entramado_madera")
	public Integer getSeparacionEntramadoMadera() {
		return this.separacionEntramadoMadera;
	}

	public void setSeparacionEntramadoMadera(Integer separacionEntramadoMadera) {
		this.separacionEntramadoMadera = separacionEntramadoMadera;
	}

	/**
	 * * (separacion_entramado_madera_espesor)
	 */

	@Column(name = "sep_entramado_madera_espesor")
	public Integer getSeparacionEntramadoMaderaEspesor() {
		return this.separacionEntramadoMaderaEspesor;
	}

	public void setSeparacionEntramadoMaderaEspesor(Integer separacionEntramadoMaderaEspesor) {
		this.separacionEntramadoMaderaEspesor = separacionEntramadoMaderaEspesor;
	}

	/**
	 * * (separacion_entramado_madera_revestido)
	 */

	@Column(name = "sep_entramado_madera_revestido")
	public Integer getSeparacionEntramadoMaderaRevestido() {
		return this.separacionEntramadoMaderaRevestido;
	}

	public void setSeparacionEntramadoMaderaRevestido(Integer separacionEntramadoMaderaRevestido) {
		this.separacionEntramadoMaderaRevestido = separacionEntramadoMaderaRevestido;
	}

	@Column(name = "separacion_fabrica")
	public Integer getSeparacionFabrica() {
		return this.separacionFabrica;
	}

	public void setSeparacionFabrica(Integer separacionFabrica) {
		this.separacionFabrica = separacionFabrica;
	}

	@Column(name = "separacion_fabrica_revestido")
	public Integer getSeparacionFabricaRevestido() {
		return this.separacionFabricaRevestido;
	}

	public void setSeparacionFabricaRevestido(Integer separacionFabricaRevestido) {
		this.separacionFabricaRevestido = separacionFabricaRevestido;
	}

	@Column(name = "separacion_otros")
	public Integer getSeparacionOtros() {
		return this.separacionOtros;
	}

	public void setSeparacionOtros(Integer separacionOtros) {
		this.separacionOtros = separacionOtros;
	}

	@Column(name = "separacion_otros_texto")
	public String getSeparacionOtrosTexto() {
		return this.separacionOtrosTexto;
	}

	public void setSeparacionOtrosTexto(String separacionOtrosTexto) {
		this.separacionOtrosTexto = separacionOtrosTexto;
	}

	/**
	 * * (tabiques_entramado_autoportante_metalico)
	 */

	@Column(name = "tab_entr_autopor_metalico")
	public Integer getTabiquesEntramadoAutoportanteMetalico() {
		return this.tabiquesEntramadoAutoportanteMetalico;
	}

	public void setTabiquesEntramadoAutoportanteMetalico(Integer tabiquesEntramadoAutoportanteMetalico) {
		this.tabiquesEntramadoAutoportanteMetalico = tabiquesEntramadoAutoportanteMetalico;
	}

	/**
	 * * (tabiques_entramado_autoportante_metalico_espesor)
	 */

	@Column(name = "tab_entr_autopor_metalico_esp")
	public String getTabiquesEntramadoAutoportanteMetalicoEspesor() {
		return this.tabiquesEntramadoAutoportanteMetalicoEspesor;
	}

	public void setTabiquesEntramadoAutoportanteMetalicoEspesor(String tabiquesEntramadoAutoportanteMetalicoEspesor) {
		this.tabiquesEntramadoAutoportanteMetalicoEspesor = tabiquesEntramadoAutoportanteMetalicoEspesor;
	}

	/**
	 * * (tabiques_entramado_madera_relleno)
	 */

	@Column(name = "tab_entr_madera_relleno")
	public Integer getTabiquesEntramadoMaderaRelleno() {
		return this.tabiquesEntramadoMaderaRelleno;
	}

	public void setTabiquesEntramadoMaderaRelleno(Integer tabiquesEntramadoMaderaRelleno) {
		this.tabiquesEntramadoMaderaRelleno = tabiquesEntramadoMaderaRelleno;
	}

	/**
	 * * (tabiques_entramado_madera_relleno_espesor)
	 */

	@Column(name = "tab_entr_madera_relleno_esp")
	public String getTabiquesEntramadoMaderaRellenoEspesor() {
		return this.tabiquesEntramadoMaderaRellenoEspesor;
	}

	public void setTabiquesEntramadoMaderaRellenoEspesor(String tabiquesEntramadoMaderaRellenoEspesor) {
		this.tabiquesEntramadoMaderaRellenoEspesor = tabiquesEntramadoMaderaRellenoEspesor;
	}

	@Column(name = "tabiques_fabrica")
	public Integer getTabiquesFabrica() {
		return this.tabiquesFabrica;
	}

	public void setTabiquesFabrica(Integer tabiquesFabrica) {
		this.tabiquesFabrica = tabiquesFabrica;
	}

	@Column(name = "zona_comun_hall_puerta")
	public Integer getZonaComunHallPuerta() {
		return this.zonaComunHallPuerta;
	}

	public void setZonaComunHallPuerta(Integer zonaComunHallPuerta) {
		this.zonaComunHallPuerta = zonaComunHallPuerta;
	}

	/**
	 * * (zona_comun_puertas_acusticamente_favorables)
	 */

	@Column(name = "zona_comun_puertas_acument_fav")
	public Integer getZonaComunPuertasAcusticamenteFavorables() {
		return this.zonaComunPuertasAcusticamenteFavorables;
	}

	public void setZonaComunPuertasAcusticamenteFavorables(Integer zonaComunPuertasAcusticamenteFavorables) {
		this.zonaComunPuertasAcusticamenteFavorables = zonaComunPuertasAcusticamenteFavorables;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcusticaRuidosInterioresVerticales))
			return false;
		AcusticaRuidosInterioresVerticales castOther = (AcusticaRuidosInterioresVerticales) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
