package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * AcusticaDatosGenerales generated by hbm2java
 */
@Entity
@Table(name = "aed_acu_datgen")
public class AcusticaDatosGenerales extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	private Integer estudioEspecifico;
	/**
	 * (existen_recintos_instalaciones)
	 */
	private String existenRecintosInstalaciones;
	private Integer fachadasNoExpuestasRuido;
	private Integer indiceRuidoDia;
	private Integer objetivoCalidadAcustica;
	private String observaciones;
	/**
	 * (recintos_instalaciones_recintos_habitables)
	 */
	private String recintosInstalacionesRecintosHabitables;
	/**
	 * (recintos_instalaciones_zonas_comunes)
	 */
	private String recintosInstalacionesZonasComunes;
	private Integer recintosProtegidosAscensor;
	/**
	 * (recintos_protegidos_recintos_habitables)
	 */
	private Integer recintosProtegidosRecintosHabitables;
	/**
	 * (recintos_protegidos_recintos_instalaciones)
	 */
	private Integer recintosProtegidosRecintosInstalaciones;
	/**
	 * (recintos_protegidos_recintos_protegidos)
	 */
	private Integer recintosProtegidosRecintosProtegidos;
	private Integer recintosProtegidosZonaComun;
	private String tipoAreaAcustica;
	private Integer zonaRuidoAeronaves;

	public AcusticaDatosGenerales() {
	}

	public AcusticaDatosGenerales(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public AcusticaDatosGenerales(Inspeccion inspeccion, Integer estudioEspecifico, String existenRecintosInstalaciones, Integer fachadasNoExpuestasRuido, Integer indiceRuidoDia, Integer objetivoCalidadAcustica, String observaciones, String recintosInstalacionesRecintosHabitables, String recintosInstalacionesZonasComunes, Integer recintosProtegidosAscensor, Integer recintosProtegidosRecintosHabitables, Integer recintosProtegidosRecintosInstalaciones, Integer recintosProtegidosRecintosProtegidos, Integer recintosProtegidosZonaComun, String tipoAreaAcustica, Integer zonaRuidoAeronaves) {
		this.inspeccion = inspeccion;
		this.estudioEspecifico = estudioEspecifico;
		this.existenRecintosInstalaciones = existenRecintosInstalaciones;
		this.fachadasNoExpuestasRuido = fachadasNoExpuestasRuido;
		this.indiceRuidoDia = indiceRuidoDia;
		this.objetivoCalidadAcustica = objetivoCalidadAcustica;
		this.observaciones = observaciones;
		this.recintosInstalacionesRecintosHabitables = recintosInstalacionesRecintosHabitables;
		this.recintosInstalacionesZonasComunes = recintosInstalacionesZonasComunes;
		this.recintosProtegidosAscensor = recintosProtegidosAscensor;
		this.recintosProtegidosRecintosHabitables = recintosProtegidosRecintosHabitables;
		this.recintosProtegidosRecintosInstalaciones = recintosProtegidosRecintosInstalaciones;
		this.recintosProtegidosRecintosProtegidos = recintosProtegidosRecintosProtegidos;
		this.recintosProtegidosZonaComun = recintosProtegidosZonaComun;
		this.tipoAreaAcustica = tipoAreaAcustica;
		this.zonaRuidoAeronaves = zonaRuidoAeronaves;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "estudio_especifico")
	public Integer getEstudioEspecifico() {
		return this.estudioEspecifico;
	}

	public void setEstudioEspecifico(Integer estudioEspecifico) {
		this.estudioEspecifico = estudioEspecifico;
	}

	/**
	 * * (existen_recintos_instalaciones)
	 */

	@Column(name = "existen_recintos_instal")
	public String getExistenRecintosInstalaciones() {
		return this.existenRecintosInstalaciones;
	}

	public void setExistenRecintosInstalaciones(String existenRecintosInstalaciones) {
		this.existenRecintosInstalaciones = existenRecintosInstalaciones;
	}

	@Column(name = "fachadas_no_expuestas_ruido")
	public Integer getFachadasNoExpuestasRuido() {
		return this.fachadasNoExpuestasRuido;
	}

	public void setFachadasNoExpuestasRuido(Integer fachadasNoExpuestasRuido) {
		this.fachadasNoExpuestasRuido = fachadasNoExpuestasRuido;
	}

	@Column(name = "indice_ruido_dia")
	public Integer getIndiceRuidoDia() {
		return this.indiceRuidoDia;
	}

	public void setIndiceRuidoDia(Integer indiceRuidoDia) {
		this.indiceRuidoDia = indiceRuidoDia;
	}

	@Column(name = "objetivo_calidad_acustica")
	public Integer getObjetivoCalidadAcustica() {
		return this.objetivoCalidadAcustica;
	}

	public void setObjetivoCalidadAcustica(Integer objetivoCalidadAcustica) {
		this.objetivoCalidadAcustica = objetivoCalidadAcustica;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	/**
	 * * (recintos_instalaciones_recintos_habitables)
	 */

	@Column(name = "recintos_instal_recintos_hab")
	public String getRecintosInstalacionesRecintosHabitables() {
		return this.recintosInstalacionesRecintosHabitables;
	}

	public void setRecintosInstalacionesRecintosHabitables(String recintosInstalacionesRecintosHabitables) {
		this.recintosInstalacionesRecintosHabitables = recintosInstalacionesRecintosHabitables;
	}

	/**
	 * * (recintos_instalaciones_zonas_comunes)
	 */

	@Column(name = "recintos_instal_zonas_comunes")
	public String getRecintosInstalacionesZonasComunes() {
		return this.recintosInstalacionesZonasComunes;
	}

	public void setRecintosInstalacionesZonasComunes(String recintosInstalacionesZonasComunes) {
		this.recintosInstalacionesZonasComunes = recintosInstalacionesZonasComunes;
	}

	@Column(name = "recintos_protegidos_ascensor")
	public Integer getRecintosProtegidosAscensor() {
		return this.recintosProtegidosAscensor;
	}

	public void setRecintosProtegidosAscensor(Integer recintosProtegidosAscensor) {
		this.recintosProtegidosAscensor = recintosProtegidosAscensor;
	}

	/**
	 * * (recintos_protegidos_recintos_habitables)
	 */

	@Column(name = "recintos_protegidos_habitables")
	public Integer getRecintosProtegidosRecintosHabitables() {
		return this.recintosProtegidosRecintosHabitables;
	}

	public void setRecintosProtegidosRecintosHabitables(Integer recintosProtegidosRecintosHabitables) {
		this.recintosProtegidosRecintosHabitables = recintosProtegidosRecintosHabitables;
	}

	/**
	 * * (recintos_protegidos_recintos_instalaciones)
	 */

	@Column(name = "recintos_protegidos_instal")
	public Integer getRecintosProtegidosRecintosInstalaciones() {
		return this.recintosProtegidosRecintosInstalaciones;
	}

	public void setRecintosProtegidosRecintosInstalaciones(Integer recintosProtegidosRecintosInstalaciones) {
		this.recintosProtegidosRecintosInstalaciones = recintosProtegidosRecintosInstalaciones;
	}

	/**
	 * * (recintos_protegidos_recintos_protegidos)
	 */

	@Column(name = "recintos_protegidos_protegidos")
	public Integer getRecintosProtegidosRecintosProtegidos() {
		return this.recintosProtegidosRecintosProtegidos;
	}

	public void setRecintosProtegidosRecintosProtegidos(Integer recintosProtegidosRecintosProtegidos) {
		this.recintosProtegidosRecintosProtegidos = recintosProtegidosRecintosProtegidos;
	}

	@Column(name = "recintos_protegidos_zona_comun")
	public Integer getRecintosProtegidosZonaComun() {
		return this.recintosProtegidosZonaComun;
	}

	public void setRecintosProtegidosZonaComun(Integer recintosProtegidosZonaComun) {
		this.recintosProtegidosZonaComun = recintosProtegidosZonaComun;
	}

	@Column(name = "tipo_area_acustica")
	public String getTipoAreaAcustica() {
		return this.tipoAreaAcustica;
	}

	public void setTipoAreaAcustica(String tipoAreaAcustica) {
		this.tipoAreaAcustica = tipoAreaAcustica;
	}

	@Column(name = "zona_ruido_aeronaves")
	public Integer getZonaRuidoAeronaves() {
		return this.zonaRuidoAeronaves;
	}

	public void setZonaRuidoAeronaves(Integer zonaRuidoAeronaves) {
		this.zonaRuidoAeronaves = zonaRuidoAeronaves;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcusticaDatosGenerales))
			return false;
		AcusticaDatosGenerales castOther = (AcusticaDatosGenerales) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
