package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * AcusticaRuidoInstalaciones generated by hbm2java
 */
@Entity
@Table(name = "aed_acu_ruidoinstalaciones")
public class AcusticaRuidoInstalaciones extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	/**
	 * (equipos_instalaciones_colindantes)
	 */
	private Integer equiposInstalacionesColindantes;
	/**
	 * (equipos_instalaciones_conductos_anclados)
	 */
	private Integer equiposInstalacionesConductosAnclados;
	/**
	 * (equipos_instalaciones_conectores_flexibles)
	 */
	private Integer equiposInstalacionesConectoresFlexibles;
	/**
	 * (equipos_instalaciones_holguras_selladas)
	 */
	private Integer equiposInstalacionesHolgurasSelladas;
	/**
	 * (equipos_instalaciones_ruido_molesto)
	 */
	private Integer equiposInstalacionesRuidoMolesto;
	/**
	 * (equipos_instalaciones_ruido_molesto_tipo_localizacion)
	 */
	private String equiposInstalacionesRuidoMolestoTipoLocalizacion;
	/**
	 * (equipos_instalaciones_sistema_amortiguante)
	 */
	private Integer equiposInstalacionesSistemaAmortiguante;
	/**
	 * (equipos_instalaciones_zonas_exteriores)
	 */
	private Integer equiposInstalacionesZonasExteriores;
	/**
	 * (equipos_instalaciones_zonas_exteriores_pantallas)
	 */
	private Integer equiposInstalacionesZonasExterioresPantallas;
	private String observaciones;
	private Integer otrasAscensoresColindantes;
	/**
	 * (otras_ascensores_cuadro_maniobras)
	 */
	private Integer otrasAscensoresCuadroManiobras;
	/**
	 * (otras_ascensores_cuarto_maquinas)
	 */
	private Integer otrasAscensoresCuartoMaquinas;
	private Integer otrasAscensoresRuidoMolesto;
	/**
	 * (otras_ascensores_ruido_molesto_tipo_localizacion)
	 */
	private String otrasAscensoresRuidoMolestoTipoLocalizacion;
	/**
	 * (otras_ascensores_sistema_amortiguante)
	 */
	private Integer otrasAscensoresSistemaAmortiguante;
	private Integer otrasAscensoresTrasdosado;
	/**
	 * (otras_cuartos_humedos_aire_acondicionado)
	 */
	private Integer otrasCuartosHumedosAireAcondicionado;
	/**
	 * (otras_cuartos_humedos_luminarias_empotradas)
	 */
	private Integer otrasCuartosHumedosLuminariasEmpotradas;
	/**
	 * (otras_cuartos_humedos_ruido_molesto)
	 */
	private Integer otrasCuartosHumedosRuidoMolesto;
	/**
	 * (otras_cuartos_humedos_ruido_molesto_tipo_localizacion)
	 */
	private String otrasCuartosHumedosRuidoMolestoTipoLocalizacion;
	/**
	 * (otras_cuartos_humedos_saneamiento)
	 */
	private Integer otrasCuartosHumedosSaneamiento;
	/**
	 * (otras_cuartos_humedos_saneamiento_conectores_flexibles)
	 */
	private Integer otrasCuartosHumedosSaneamientoConectoresFlexibles;
	/**
	 * (otras_cuartos_humedos_saneamiento_lana_mineral)
	 */
	private Integer otrasCuartosHumedosSaneamientoLanaMineral;
	/**
	 * (otras_cuartos_humedos_saneamiento_material_elastico)
	 */
	private Integer otrasCuartosHumedosSaneamientoMaterialElastico;
	/**
	 * (otras_cuartos_humedos_saneamiento_techo_sellado)
	 */
	private Integer otrasCuartosHumedosSaneamientoTechoSellado;
	private Integer otrasPuertasGarajeAncladas;
	/**
	 * (otras_puertas_garaje_ancladas_marco_amortiguadores)
	 */
	private Integer otrasPuertasGarajeAncladasMarcoAmortiguadores;
	/**
	 * (otras_puertas_garaje_ancladas_motores_amortiguadores)
	 */
	private Integer otrasPuertasGarajeAncladasMotoresAmortiguadores;
	/**
	 * (otras_puertas_garaje_ancladas_ruido_puerta)
	 */
	private Integer otrasPuertasGarajeAncladasRuidoPuerta;
	private Integer recintosActividadRevestido;
	/**
	 * (recintos_actividad_ruido_molesto)
	 */
	private Integer recintosActividadRuidoMolesto;
	/**
	 * (recintos_actividad_ruido_molesto_tipo_localizacion)
	 */
	private String recintosActividadRuidoMolestoTipoLocalizacion;
	/**
	 * (recintos_actividad_suelo_flotante)
	 */
	private Integer recintosActividadSueloFlotante;
	/**
	 * (recintos_actividad_techo_suspendido)
	 */
	private Integer recintosActividadTechoSuspendido;
	/**
	 * (recintos_actividad_techo_suspendido_absorvente)
	 */
	private Integer recintosActividadTechoSuspendidoAbsorvente;
	/**
	 * (recintos_actividad_techo_suspendido_amortiguadores)
	 */
	private Integer recintosActividadTechoSuspendidoAmortiguadores;
	private Integer recintosActividadTiene;
	/**
	 * (recintos_actividad_tipo_localizacion)
	 */
	private String recintosActividadTipoLocalizacion;
	private Integer recintosActividadTrasdosados;
	/**
	 * (recintos_actividad_trasdosados_amortiguadores)
	 */
	private Integer recintosActividadTrasdosadosAmortiguadores;
	/**
	 * (recintos_actividad_tratamiento_absorvente)
	 */
	private Integer recintosActividadTratamientoAbsorvente;
	/**
	 * (redes_agua_ruido_molesto_tipo_localizacion)
	 */
	private String redesAguaRuidoMolestoTipoLocalizacion;
	/**
	 * (redes_aire_acondicionado_falso_techo)
	 */
	private Integer redesAireAcondicionadoFalsoTecho;
	/**
	 * (redes_aire_acondicionado_ruido_molesto)
	 */
	private Integer redesAireAcondicionadoRuidoMolesto;
	/**
	 * (redes_saneamiento_bajantes_abrazaderas)
	 */
	private Integer redesSaneamientoBajantesAbrazaderas;
	/**
	 * (redes_saneamiento_bajantes_forradas)
	 */
	private Integer redesSaneamientoBajantesForradas;
	/**
	 * (redes_saneamiento_bajantes_revestidas)
	 */
	private Integer redesSaneamientoBajantesRevestidas;
	private Integer redesSaneamientoCodoBajante;
	/**
	 * (redes_saneamiento_ruido_molesto)
	 */
	private Integer redesSaneamientoRuidoMolesto;
	/**
	 * (redes_saneamiento_ruido_molesto_tipo_localizacion)
	 */
	private String redesSaneamientoRuidoMolestoTipoLocalizacion;
	/**
	 * (redes_suministro_agua_ruido_golpe_ariete)
	 */
	private Integer redesSuministroAguaRuidoGolpeAriete;
	/**
	 * (redes_suministro_agua_ruido_molesto)
	 */
	private Integer redesSuministroAguaRuidoMolesto;
	/**
	 * (redes_suministro_agua_tuberias_forradas)
	 */
	private Integer redesSuministroAguaTuberiasForradas;
	/**
	 * (redes_ventilacion_conducto_individual)
	 */
	private Integer redesVentilacionConductoIndividual;
	/**
	 * (redes_ventilacion_conductos_shunt)
	 */
	private Integer redesVentilacionConductosShunt;
	/**
	 * (redes_ventilacion_ruido_viviendas_colindantes)
	 */
	private Integer redesVentilacionRuidoViviendasColindantes;

	public AcusticaRuidoInstalaciones() {
	}

	public AcusticaRuidoInstalaciones(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public AcusticaRuidoInstalaciones(Inspeccion inspeccion, Integer equiposInstalacionesColindantes, Integer equiposInstalacionesConductosAnclados, Integer equiposInstalacionesConectoresFlexibles, Integer equiposInstalacionesHolgurasSelladas, Integer equiposInstalacionesRuidoMolesto, String equiposInstalacionesRuidoMolestoTipoLocalizacion, Integer equiposInstalacionesSistemaAmortiguante, Integer equiposInstalacionesZonasExteriores, Integer equiposInstalacionesZonasExterioresPantallas, String observaciones, Integer otrasAscensoresColindantes, Integer otrasAscensoresCuadroManiobras, Integer otrasAscensoresCuartoMaquinas, Integer otrasAscensoresRuidoMolesto, String otrasAscensoresRuidoMolestoTipoLocalizacion, Integer otrasAscensoresSistemaAmortiguante, Integer otrasAscensoresTrasdosado, Integer otrasCuartosHumedosAireAcondicionado, Integer otrasCuartosHumedosLuminariasEmpotradas, Integer otrasCuartosHumedosRuidoMolesto, String otrasCuartosHumedosRuidoMolestoTipoLocalizacion, Integer otrasCuartosHumedosSaneamiento, Integer otrasCuartosHumedosSaneamientoConectoresFlexibles, Integer otrasCuartosHumedosSaneamientoLanaMineral, Integer otrasCuartosHumedosSaneamientoMaterialElastico, Integer otrasCuartosHumedosSaneamientoTechoSellado, Integer otrasPuertasGarajeAncladas, Integer otrasPuertasGarajeAncladasMarcoAmortiguadores, Integer otrasPuertasGarajeAncladasMotoresAmortiguadores, Integer otrasPuertasGarajeAncladasRuidoPuerta, Integer recintosActividadRevestido, Integer recintosActividadRuidoMolesto, String recintosActividadRuidoMolestoTipoLocalizacion, Integer recintosActividadSueloFlotante, Integer recintosActividadTechoSuspendido, Integer recintosActividadTechoSuspendidoAbsorvente, Integer recintosActividadTechoSuspendidoAmortiguadores, Integer recintosActividadTiene, String recintosActividadTipoLocalizacion, Integer recintosActividadTrasdosados, Integer recintosActividadTrasdosadosAmortiguadores, Integer recintosActividadTratamientoAbsorvente, String redesAguaRuidoMolestoTipoLocalizacion, Integer redesAireAcondicionadoFalsoTecho, Integer redesAireAcondicionadoRuidoMolesto, Integer redesSaneamientoBajantesAbrazaderas, Integer redesSaneamientoBajantesForradas, Integer redesSaneamientoBajantesRevestidas, Integer redesSaneamientoCodoBajante, Integer redesSaneamientoRuidoMolesto, String redesSaneamientoRuidoMolestoTipoLocalizacion, Integer redesSuministroAguaRuidoGolpeAriete, Integer redesSuministroAguaRuidoMolesto, Integer redesSuministroAguaTuberiasForradas, Integer redesVentilacionConductoIndividual, Integer redesVentilacionConductosShunt, Integer redesVentilacionRuidoViviendasColindantes) {
		this.inspeccion = inspeccion;
		this.equiposInstalacionesColindantes = equiposInstalacionesColindantes;
		this.equiposInstalacionesConductosAnclados = equiposInstalacionesConductosAnclados;
		this.equiposInstalacionesConectoresFlexibles = equiposInstalacionesConectoresFlexibles;
		this.equiposInstalacionesHolgurasSelladas = equiposInstalacionesHolgurasSelladas;
		this.equiposInstalacionesRuidoMolesto = equiposInstalacionesRuidoMolesto;
		this.equiposInstalacionesRuidoMolestoTipoLocalizacion = equiposInstalacionesRuidoMolestoTipoLocalizacion;
		this.equiposInstalacionesSistemaAmortiguante = equiposInstalacionesSistemaAmortiguante;
		this.equiposInstalacionesZonasExteriores = equiposInstalacionesZonasExteriores;
		this.equiposInstalacionesZonasExterioresPantallas = equiposInstalacionesZonasExterioresPantallas;
		this.observaciones = observaciones;
		this.otrasAscensoresColindantes = otrasAscensoresColindantes;
		this.otrasAscensoresCuadroManiobras = otrasAscensoresCuadroManiobras;
		this.otrasAscensoresCuartoMaquinas = otrasAscensoresCuartoMaquinas;
		this.otrasAscensoresRuidoMolesto = otrasAscensoresRuidoMolesto;
		this.otrasAscensoresRuidoMolestoTipoLocalizacion = otrasAscensoresRuidoMolestoTipoLocalizacion;
		this.otrasAscensoresSistemaAmortiguante = otrasAscensoresSistemaAmortiguante;
		this.otrasAscensoresTrasdosado = otrasAscensoresTrasdosado;
		this.otrasCuartosHumedosAireAcondicionado = otrasCuartosHumedosAireAcondicionado;
		this.otrasCuartosHumedosLuminariasEmpotradas = otrasCuartosHumedosLuminariasEmpotradas;
		this.otrasCuartosHumedosRuidoMolesto = otrasCuartosHumedosRuidoMolesto;
		this.otrasCuartosHumedosRuidoMolestoTipoLocalizacion = otrasCuartosHumedosRuidoMolestoTipoLocalizacion;
		this.otrasCuartosHumedosSaneamiento = otrasCuartosHumedosSaneamiento;
		this.otrasCuartosHumedosSaneamientoConectoresFlexibles = otrasCuartosHumedosSaneamientoConectoresFlexibles;
		this.otrasCuartosHumedosSaneamientoLanaMineral = otrasCuartosHumedosSaneamientoLanaMineral;
		this.otrasCuartosHumedosSaneamientoMaterialElastico = otrasCuartosHumedosSaneamientoMaterialElastico;
		this.otrasCuartosHumedosSaneamientoTechoSellado = otrasCuartosHumedosSaneamientoTechoSellado;
		this.otrasPuertasGarajeAncladas = otrasPuertasGarajeAncladas;
		this.otrasPuertasGarajeAncladasMarcoAmortiguadores = otrasPuertasGarajeAncladasMarcoAmortiguadores;
		this.otrasPuertasGarajeAncladasMotoresAmortiguadores = otrasPuertasGarajeAncladasMotoresAmortiguadores;
		this.otrasPuertasGarajeAncladasRuidoPuerta = otrasPuertasGarajeAncladasRuidoPuerta;
		this.recintosActividadRevestido = recintosActividadRevestido;
		this.recintosActividadRuidoMolesto = recintosActividadRuidoMolesto;
		this.recintosActividadRuidoMolestoTipoLocalizacion = recintosActividadRuidoMolestoTipoLocalizacion;
		this.recintosActividadSueloFlotante = recintosActividadSueloFlotante;
		this.recintosActividadTechoSuspendido = recintosActividadTechoSuspendido;
		this.recintosActividadTechoSuspendidoAbsorvente = recintosActividadTechoSuspendidoAbsorvente;
		this.recintosActividadTechoSuspendidoAmortiguadores = recintosActividadTechoSuspendidoAmortiguadores;
		this.recintosActividadTiene = recintosActividadTiene;
		this.recintosActividadTipoLocalizacion = recintosActividadTipoLocalizacion;
		this.recintosActividadTrasdosados = recintosActividadTrasdosados;
		this.recintosActividadTrasdosadosAmortiguadores = recintosActividadTrasdosadosAmortiguadores;
		this.recintosActividadTratamientoAbsorvente = recintosActividadTratamientoAbsorvente;
		this.redesAguaRuidoMolestoTipoLocalizacion = redesAguaRuidoMolestoTipoLocalizacion;
		this.redesAireAcondicionadoFalsoTecho = redesAireAcondicionadoFalsoTecho;
		this.redesAireAcondicionadoRuidoMolesto = redesAireAcondicionadoRuidoMolesto;
		this.redesSaneamientoBajantesAbrazaderas = redesSaneamientoBajantesAbrazaderas;
		this.redesSaneamientoBajantesForradas = redesSaneamientoBajantesForradas;
		this.redesSaneamientoBajantesRevestidas = redesSaneamientoBajantesRevestidas;
		this.redesSaneamientoCodoBajante = redesSaneamientoCodoBajante;
		this.redesSaneamientoRuidoMolesto = redesSaneamientoRuidoMolesto;
		this.redesSaneamientoRuidoMolestoTipoLocalizacion = redesSaneamientoRuidoMolestoTipoLocalizacion;
		this.redesSuministroAguaRuidoGolpeAriete = redesSuministroAguaRuidoGolpeAriete;
		this.redesSuministroAguaRuidoMolesto = redesSuministroAguaRuidoMolesto;
		this.redesSuministroAguaTuberiasForradas = redesSuministroAguaTuberiasForradas;
		this.redesVentilacionConductoIndividual = redesVentilacionConductoIndividual;
		this.redesVentilacionConductosShunt = redesVentilacionConductosShunt;
		this.redesVentilacionRuidoViviendasColindantes = redesVentilacionRuidoViviendasColindantes;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (equipos_instalaciones_colindantes)
	 */

	@Column(name = "equipos_instal_colindantes")
	public Integer getEquiposInstalacionesColindantes() {
		return this.equiposInstalacionesColindantes;
	}

	public void setEquiposInstalacionesColindantes(Integer equiposInstalacionesColindantes) {
		this.equiposInstalacionesColindantes = equiposInstalacionesColindantes;
	}

	/**
	 * * (equipos_instalaciones_conductos_anclados)
	 */

	@Column(name = "equi_instal_conductos_anclados")
	public Integer getEquiposInstalacionesConductosAnclados() {
		return this.equiposInstalacionesConductosAnclados;
	}

	public void setEquiposInstalacionesConductosAnclados(Integer equiposInstalacionesConductosAnclados) {
		this.equiposInstalacionesConductosAnclados = equiposInstalacionesConductosAnclados;
	}

	/**
	 * * (equipos_instalaciones_conectores_flexibles)
	 */

	@Column(name = "equi_instal_conectores_flex")
	public Integer getEquiposInstalacionesConectoresFlexibles() {
		return this.equiposInstalacionesConectoresFlexibles;
	}

	public void setEquiposInstalacionesConectoresFlexibles(Integer equiposInstalacionesConectoresFlexibles) {
		this.equiposInstalacionesConectoresFlexibles = equiposInstalacionesConectoresFlexibles;
	}

	/**
	 * * (equipos_instalaciones_holguras_selladas)
	 */

	@Column(name = "equi_instal_holguras_selladas")
	public Integer getEquiposInstalacionesHolgurasSelladas() {
		return this.equiposInstalacionesHolgurasSelladas;
	}

	public void setEquiposInstalacionesHolgurasSelladas(Integer equiposInstalacionesHolgurasSelladas) {
		this.equiposInstalacionesHolgurasSelladas = equiposInstalacionesHolgurasSelladas;
	}

	/**
	 * * (equipos_instalaciones_ruido_molesto)
	 */

	@Column(name = "equipos_instal_ruido_molesto")
	public Integer getEquiposInstalacionesRuidoMolesto() {
		return this.equiposInstalacionesRuidoMolesto;
	}

	public void setEquiposInstalacionesRuidoMolesto(Integer equiposInstalacionesRuidoMolesto) {
		this.equiposInstalacionesRuidoMolesto = equiposInstalacionesRuidoMolesto;
	}

	/**
	 * * (equipos_instalaciones_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "equi_instal_rui_moles_tipo_loc")
	public String getEquiposInstalacionesRuidoMolestoTipoLocalizacion() {
		return this.equiposInstalacionesRuidoMolestoTipoLocalizacion;
	}

	public void setEquiposInstalacionesRuidoMolestoTipoLocalizacion(String equiposInstalacionesRuidoMolestoTipoLocalizacion) {
		this.equiposInstalacionesRuidoMolestoTipoLocalizacion = equiposInstalacionesRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (equipos_instalaciones_sistema_amortiguante)
	 */

	@Column(name = "equi_instal_sistema_amortiguan")
	public Integer getEquiposInstalacionesSistemaAmortiguante() {
		return this.equiposInstalacionesSistemaAmortiguante;
	}

	public void setEquiposInstalacionesSistemaAmortiguante(Integer equiposInstalacionesSistemaAmortiguante) {
		this.equiposInstalacionesSistemaAmortiguante = equiposInstalacionesSistemaAmortiguante;
	}

	/**
	 * * (equipos_instalaciones_zonas_exteriores)
	 */

	@Column(name = "equi_instal_zonas_exteriores")
	public Integer getEquiposInstalacionesZonasExteriores() {
		return this.equiposInstalacionesZonasExteriores;
	}

	public void setEquiposInstalacionesZonasExteriores(Integer equiposInstalacionesZonasExteriores) {
		this.equiposInstalacionesZonasExteriores = equiposInstalacionesZonasExteriores;
	}

	/**
	 * * (equipos_instalaciones_zonas_exteriores_pantallas)
	 */

	@Column(name = "equi_instal_zonas_ext_pantalla")
	public Integer getEquiposInstalacionesZonasExterioresPantallas() {
		return this.equiposInstalacionesZonasExterioresPantallas;
	}

	public void setEquiposInstalacionesZonasExterioresPantallas(Integer equiposInstalacionesZonasExterioresPantallas) {
		this.equiposInstalacionesZonasExterioresPantallas = equiposInstalacionesZonasExterioresPantallas;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "otras_ascensores_colindantes")
	public Integer getOtrasAscensoresColindantes() {
		return this.otrasAscensoresColindantes;
	}

	public void setOtrasAscensoresColindantes(Integer otrasAscensoresColindantes) {
		this.otrasAscensoresColindantes = otrasAscensoresColindantes;
	}

	/**
	 * * (otras_ascensores_cuadro_maniobras)
	 */

	@Column(name = "otr_ascensores_cuadro_maniob")
	public Integer getOtrasAscensoresCuadroManiobras() {
		return this.otrasAscensoresCuadroManiobras;
	}

	public void setOtrasAscensoresCuadroManiobras(Integer otrasAscensoresCuadroManiobras) {
		this.otrasAscensoresCuadroManiobras = otrasAscensoresCuadroManiobras;
	}

	/**
	 * * (otras_ascensores_cuarto_maquinas)
	 */

	@Column(name = "otr_ascensores_cuarto_maquin")
	public Integer getOtrasAscensoresCuartoMaquinas() {
		return this.otrasAscensoresCuartoMaquinas;
	}

	public void setOtrasAscensoresCuartoMaquinas(Integer otrasAscensoresCuartoMaquinas) {
		this.otrasAscensoresCuartoMaquinas = otrasAscensoresCuartoMaquinas;
	}

	@Column(name = "otras_ascensores_ruido_molesto")
	public Integer getOtrasAscensoresRuidoMolesto() {
		return this.otrasAscensoresRuidoMolesto;
	}

	public void setOtrasAscensoresRuidoMolesto(Integer otrasAscensoresRuidoMolesto) {
		this.otrasAscensoresRuidoMolesto = otrasAscensoresRuidoMolesto;
	}

	/**
	 * * (otras_ascensores_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "otr_ascen_rui_moles_tipo_loc")
	public String getOtrasAscensoresRuidoMolestoTipoLocalizacion() {
		return this.otrasAscensoresRuidoMolestoTipoLocalizacion;
	}

	public void setOtrasAscensoresRuidoMolestoTipoLocalizacion(String otrasAscensoresRuidoMolestoTipoLocalizacion) {
		this.otrasAscensoresRuidoMolestoTipoLocalizacion = otrasAscensoresRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (otras_ascensores_sistema_amortiguante)
	 */

	@Column(name = "otr_ascen_sistema_amortiguan")
	public Integer getOtrasAscensoresSistemaAmortiguante() {
		return this.otrasAscensoresSistemaAmortiguante;
	}

	public void setOtrasAscensoresSistemaAmortiguante(Integer otrasAscensoresSistemaAmortiguante) {
		this.otrasAscensoresSistemaAmortiguante = otrasAscensoresSistemaAmortiguante;
	}

	@Column(name = "otras_ascensores_trasdosado")
	public Integer getOtrasAscensoresTrasdosado() {
		return this.otrasAscensoresTrasdosado;
	}

	public void setOtrasAscensoresTrasdosado(Integer otrasAscensoresTrasdosado) {
		this.otrasAscensoresTrasdosado = otrasAscensoresTrasdosado;
	}

	/**
	 * * (otras_cuartos_humedos_aire_acondicionado)
	 */

	@Column(name = "otr_cuartos_humedos_aacc")
	public Integer getOtrasCuartosHumedosAireAcondicionado() {
		return this.otrasCuartosHumedosAireAcondicionado;
	}

	public void setOtrasCuartosHumedosAireAcondicionado(Integer otrasCuartosHumedosAireAcondicionado) {
		this.otrasCuartosHumedosAireAcondicionado = otrasCuartosHumedosAireAcondicionado;
	}

	/**
	 * * (otras_cuartos_humedos_luminarias_empotradas)
	 */

	@Column(name = "otr_cuartos_humedos_lum_emp")
	public Integer getOtrasCuartosHumedosLuminariasEmpotradas() {
		return this.otrasCuartosHumedosLuminariasEmpotradas;
	}

	public void setOtrasCuartosHumedosLuminariasEmpotradas(Integer otrasCuartosHumedosLuminariasEmpotradas) {
		this.otrasCuartosHumedosLuminariasEmpotradas = otrasCuartosHumedosLuminariasEmpotradas;
	}

	/**
	 * * (otras_cuartos_humedos_ruido_molesto)
	 */

	@Column(name = "otr_cuartos_humedos_rui_mole")
	public Integer getOtrasCuartosHumedosRuidoMolesto() {
		return this.otrasCuartosHumedosRuidoMolesto;
	}

	public void setOtrasCuartosHumedosRuidoMolesto(Integer otrasCuartosHumedosRuidoMolesto) {
		this.otrasCuartosHumedosRuidoMolesto = otrasCuartosHumedosRuidoMolesto;
	}

	/**
	 * * (otras_cuartos_humedos_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "otr_cua_hum_rui_mole_tipo_loc")
	public String getOtrasCuartosHumedosRuidoMolestoTipoLocalizacion() {
		return this.otrasCuartosHumedosRuidoMolestoTipoLocalizacion;
	}

	public void setOtrasCuartosHumedosRuidoMolestoTipoLocalizacion(String otrasCuartosHumedosRuidoMolestoTipoLocalizacion) {
		this.otrasCuartosHumedosRuidoMolestoTipoLocalizacion = otrasCuartosHumedosRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (otras_cuartos_humedos_saneamiento)
	 */

	@Column(name = "otr_cuar_hum_saneamiento")
	public Integer getOtrasCuartosHumedosSaneamiento() {
		return this.otrasCuartosHumedosSaneamiento;
	}

	public void setOtrasCuartosHumedosSaneamiento(Integer otrasCuartosHumedosSaneamiento) {
		this.otrasCuartosHumedosSaneamiento = otrasCuartosHumedosSaneamiento;
	}

	/**
	 * * (otras_cuartos_humedos_saneamiento_conectores_flexibles)
	 */

	@Column(name = "otr_cuar_hum_sanea_conec_flex")
	public Integer getOtrasCuartosHumedosSaneamientoConectoresFlexibles() {
		return this.otrasCuartosHumedosSaneamientoConectoresFlexibles;
	}

	public void setOtrasCuartosHumedosSaneamientoConectoresFlexibles(Integer otrasCuartosHumedosSaneamientoConectoresFlexibles) {
		this.otrasCuartosHumedosSaneamientoConectoresFlexibles = otrasCuartosHumedosSaneamientoConectoresFlexibles;
	}

	/**
	 * * (otras_cuartos_humedos_saneamiento_lana_mineral)
	 */

	@Column(name = "otr_cuar_hum_sanea_lana_minera")
	public Integer getOtrasCuartosHumedosSaneamientoLanaMineral() {
		return this.otrasCuartosHumedosSaneamientoLanaMineral;
	}

	public void setOtrasCuartosHumedosSaneamientoLanaMineral(Integer otrasCuartosHumedosSaneamientoLanaMineral) {
		this.otrasCuartosHumedosSaneamientoLanaMineral = otrasCuartosHumedosSaneamientoLanaMineral;
	}

	/**
	 * * (otras_cuartos_humedos_saneamiento_material_elastico)
	 */

	@Column(name = "otr_cuar_hum_sanea_mater_elast")
	public Integer getOtrasCuartosHumedosSaneamientoMaterialElastico() {
		return this.otrasCuartosHumedosSaneamientoMaterialElastico;
	}

	public void setOtrasCuartosHumedosSaneamientoMaterialElastico(Integer otrasCuartosHumedosSaneamientoMaterialElastico) {
		this.otrasCuartosHumedosSaneamientoMaterialElastico = otrasCuartosHumedosSaneamientoMaterialElastico;
	}

	/**
	 * * (otras_cuartos_humedos_saneamiento_techo_sellado)
	 */

	@Column(name = "otr_cuar_hum_sanea_techo_sella")
	public Integer getOtrasCuartosHumedosSaneamientoTechoSellado() {
		return this.otrasCuartosHumedosSaneamientoTechoSellado;
	}

	public void setOtrasCuartosHumedosSaneamientoTechoSellado(Integer otrasCuartosHumedosSaneamientoTechoSellado) {
		this.otrasCuartosHumedosSaneamientoTechoSellado = otrasCuartosHumedosSaneamientoTechoSellado;
	}

	@Column(name = "otras_puertas_garaje_ancladas")
	public Integer getOtrasPuertasGarajeAncladas() {
		return this.otrasPuertasGarajeAncladas;
	}

	public void setOtrasPuertasGarajeAncladas(Integer otrasPuertasGarajeAncladas) {
		this.otrasPuertasGarajeAncladas = otrasPuertasGarajeAncladas;
	}

	/**
	 * * (otras_puertas_garaje_ancladas_marco_amortiguadores)
	 */

	@Column(name = "otr_puert_gar_ancl_marc_amorti")
	public Integer getOtrasPuertasGarajeAncladasMarcoAmortiguadores() {
		return this.otrasPuertasGarajeAncladasMarcoAmortiguadores;
	}

	public void setOtrasPuertasGarajeAncladasMarcoAmortiguadores(Integer otrasPuertasGarajeAncladasMarcoAmortiguadores) {
		this.otrasPuertasGarajeAncladasMarcoAmortiguadores = otrasPuertasGarajeAncladasMarcoAmortiguadores;
	}

	/**
	 * * (otras_puertas_garaje_ancladas_motores_amortiguadores)
	 */

	@Column(name = "otr_puert_gar_ancl_motor_amort")
	public Integer getOtrasPuertasGarajeAncladasMotoresAmortiguadores() {
		return this.otrasPuertasGarajeAncladasMotoresAmortiguadores;
	}

	public void setOtrasPuertasGarajeAncladasMotoresAmortiguadores(Integer otrasPuertasGarajeAncladasMotoresAmortiguadores) {
		this.otrasPuertasGarajeAncladasMotoresAmortiguadores = otrasPuertasGarajeAncladasMotoresAmortiguadores;
	}

	/**
	 * * (otras_puertas_garaje_ancladas_ruido_puerta)
	 */

	@Column(name = "otr_puert_gar_ancl_rui_puerta")
	public Integer getOtrasPuertasGarajeAncladasRuidoPuerta() {
		return this.otrasPuertasGarajeAncladasRuidoPuerta;
	}

	public void setOtrasPuertasGarajeAncladasRuidoPuerta(Integer otrasPuertasGarajeAncladasRuidoPuerta) {
		this.otrasPuertasGarajeAncladasRuidoPuerta = otrasPuertasGarajeAncladasRuidoPuerta;
	}

	@Column(name = "recintos_actividad_revestido")
	public Integer getRecintosActividadRevestido() {
		return this.recintosActividadRevestido;
	}

	public void setRecintosActividadRevestido(Integer recintosActividadRevestido) {
		this.recintosActividadRevestido = recintosActividadRevestido;
	}

	/**
	 * * (recintos_actividad_ruido_molesto)
	 */

	@Column(name = "recintos_actividad_rui_molesto")
	public Integer getRecintosActividadRuidoMolesto() {
		return this.recintosActividadRuidoMolesto;
	}

	public void setRecintosActividadRuidoMolesto(Integer recintosActividadRuidoMolesto) {
		this.recintosActividadRuidoMolesto = recintosActividadRuidoMolesto;
	}

	/**
	 * * (recintos_actividad_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "rec_act_rui_molesto_tipo_loc")
	public String getRecintosActividadRuidoMolestoTipoLocalizacion() {
		return this.recintosActividadRuidoMolestoTipoLocalizacion;
	}

	public void setRecintosActividadRuidoMolestoTipoLocalizacion(String recintosActividadRuidoMolestoTipoLocalizacion) {
		this.recintosActividadRuidoMolestoTipoLocalizacion = recintosActividadRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (recintos_actividad_suelo_flotante)
	 */

	@Column(name = "rec_act_suelo_flotante")
	public Integer getRecintosActividadSueloFlotante() {
		return this.recintosActividadSueloFlotante;
	}

	public void setRecintosActividadSueloFlotante(Integer recintosActividadSueloFlotante) {
		this.recintosActividadSueloFlotante = recintosActividadSueloFlotante;
	}

	/**
	 * * (recintos_actividad_techo_suspendido)
	 */

	@Column(name = "rec_act_techo_suspendido")
	public Integer getRecintosActividadTechoSuspendido() {
		return this.recintosActividadTechoSuspendido;
	}

	public void setRecintosActividadTechoSuspendido(Integer recintosActividadTechoSuspendido) {
		this.recintosActividadTechoSuspendido = recintosActividadTechoSuspendido;
	}

	/**
	 * * (recintos_actividad_techo_suspendido_absorvente)
	 */

	@Column(name = "rec_act_techo_susp_absorvente")
	public Integer getRecintosActividadTechoSuspendidoAbsorvente() {
		return this.recintosActividadTechoSuspendidoAbsorvente;
	}

	public void setRecintosActividadTechoSuspendidoAbsorvente(Integer recintosActividadTechoSuspendidoAbsorvente) {
		this.recintosActividadTechoSuspendidoAbsorvente = recintosActividadTechoSuspendidoAbsorvente;
	}

	/**
	 * * (recintos_actividad_techo_suspendido_amortiguadores)
	 */

	@Column(name = "rec_act_techo_susp_amortigua")
	public Integer getRecintosActividadTechoSuspendidoAmortiguadores() {
		return this.recintosActividadTechoSuspendidoAmortiguadores;
	}

	public void setRecintosActividadTechoSuspendidoAmortiguadores(Integer recintosActividadTechoSuspendidoAmortiguadores) {
		this.recintosActividadTechoSuspendidoAmortiguadores = recintosActividadTechoSuspendidoAmortiguadores;
	}

	@Column(name = "recintos_actividad_tiene")
	public Integer getRecintosActividadTiene() {
		return this.recintosActividadTiene;
	}

	public void setRecintosActividadTiene(Integer recintosActividadTiene) {
		this.recintosActividadTiene = recintosActividadTiene;
	}

	/**
	 * * (recintos_actividad_tipo_localizacion)
	 */

	@Column(name = "recintos_actividad_tipo_loc")
	public String getRecintosActividadTipoLocalizacion() {
		return this.recintosActividadTipoLocalizacion;
	}

	public void setRecintosActividadTipoLocalizacion(String recintosActividadTipoLocalizacion) {
		this.recintosActividadTipoLocalizacion = recintosActividadTipoLocalizacion;
	}

	@Column(name = "recintos_actividad_trasdosados")
	public Integer getRecintosActividadTrasdosados() {
		return this.recintosActividadTrasdosados;
	}

	public void setRecintosActividadTrasdosados(Integer recintosActividadTrasdosados) {
		this.recintosActividadTrasdosados = recintosActividadTrasdosados;
	}

	/**
	 * * (recintos_actividad_trasdosados_amortiguadores)
	 */

	@Column(name = "rec_act_trasdosados_amortigua")
	public Integer getRecintosActividadTrasdosadosAmortiguadores() {
		return this.recintosActividadTrasdosadosAmortiguadores;
	}

	public void setRecintosActividadTrasdosadosAmortiguadores(Integer recintosActividadTrasdosadosAmortiguadores) {
		this.recintosActividadTrasdosadosAmortiguadores = recintosActividadTrasdosadosAmortiguadores;
	}

	/**
	 * * (recintos_actividad_tratamiento_absorvente)
	 */

	@Column(name = "rec_act_tratamiento_absorvente")
	public Integer getRecintosActividadTratamientoAbsorvente() {
		return this.recintosActividadTratamientoAbsorvente;
	}

	public void setRecintosActividadTratamientoAbsorvente(Integer recintosActividadTratamientoAbsorvente) {
		this.recintosActividadTratamientoAbsorvente = recintosActividadTratamientoAbsorvente;
	}

	/**
	 * * (redes_agua_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "red_agua_rui_molesto_tipo_loc")
	public String getRedesAguaRuidoMolestoTipoLocalizacion() {
		return this.redesAguaRuidoMolestoTipoLocalizacion;
	}

	public void setRedesAguaRuidoMolestoTipoLocalizacion(String redesAguaRuidoMolestoTipoLocalizacion) {
		this.redesAguaRuidoMolestoTipoLocalizacion = redesAguaRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (redes_aire_acondicionado_falso_techo)
	 */

	@Column(name = "red_aacc_falso_techo")
	public Integer getRedesAireAcondicionadoFalsoTecho() {
		return this.redesAireAcondicionadoFalsoTecho;
	}

	public void setRedesAireAcondicionadoFalsoTecho(Integer redesAireAcondicionadoFalsoTecho) {
		this.redesAireAcondicionadoFalsoTecho = redesAireAcondicionadoFalsoTecho;
	}

	/**
	 * * (redes_aire_acondicionado_ruido_molesto)
	 */

	@Column(name = "red_aacc_rui_molesto")
	public Integer getRedesAireAcondicionadoRuidoMolesto() {
		return this.redesAireAcondicionadoRuidoMolesto;
	}

	public void setRedesAireAcondicionadoRuidoMolesto(Integer redesAireAcondicionadoRuidoMolesto) {
		this.redesAireAcondicionadoRuidoMolesto = redesAireAcondicionadoRuidoMolesto;
	}

	/**
	 * * (redes_saneamiento_bajantes_abrazaderas)
	 */

	@Column(name = "red_sanea_bajantes_abrazaderas")
	public Integer getRedesSaneamientoBajantesAbrazaderas() {
		return this.redesSaneamientoBajantesAbrazaderas;
	}

	public void setRedesSaneamientoBajantesAbrazaderas(Integer redesSaneamientoBajantesAbrazaderas) {
		this.redesSaneamientoBajantesAbrazaderas = redesSaneamientoBajantesAbrazaderas;
	}

	/**
	 * * (redes_saneamiento_bajantes_forradas)
	 */

	@Column(name = "red_sanea_bajantes_forradas")
	public Integer getRedesSaneamientoBajantesForradas() {
		return this.redesSaneamientoBajantesForradas;
	}

	public void setRedesSaneamientoBajantesForradas(Integer redesSaneamientoBajantesForradas) {
		this.redesSaneamientoBajantesForradas = redesSaneamientoBajantesForradas;
	}

	/**
	 * * (redes_saneamiento_bajantes_revestidas)
	 */

	@Column(name = "red_sanea_bajantes_revestidas")
	public Integer getRedesSaneamientoBajantesRevestidas() {
		return this.redesSaneamientoBajantesRevestidas;
	}

	public void setRedesSaneamientoBajantesRevestidas(Integer redesSaneamientoBajantesRevestidas) {
		this.redesSaneamientoBajantesRevestidas = redesSaneamientoBajantesRevestidas;
	}

	@Column(name = "redes_saneamiento_codo_bajante")
	public Integer getRedesSaneamientoCodoBajante() {
		return this.redesSaneamientoCodoBajante;
	}

	public void setRedesSaneamientoCodoBajante(Integer redesSaneamientoCodoBajante) {
		this.redesSaneamientoCodoBajante = redesSaneamientoCodoBajante;
	}

	/**
	 * * (redes_saneamiento_ruido_molesto)
	 */

	@Column(name = "redes_saneamiento_rui_molesto")
	public Integer getRedesSaneamientoRuidoMolesto() {
		return this.redesSaneamientoRuidoMolesto;
	}

	public void setRedesSaneamientoRuidoMolesto(Integer redesSaneamientoRuidoMolesto) {
		this.redesSaneamientoRuidoMolesto = redesSaneamientoRuidoMolesto;
	}

	/**
	 * * (redes_saneamiento_ruido_molesto_tipo_localizacion)
	 */

	@Column(name = "red_sanea_rui_molesto_tipo_loc")
	public String getRedesSaneamientoRuidoMolestoTipoLocalizacion() {
		return this.redesSaneamientoRuidoMolestoTipoLocalizacion;
	}

	public void setRedesSaneamientoRuidoMolestoTipoLocalizacion(String redesSaneamientoRuidoMolestoTipoLocalizacion) {
		this.redesSaneamientoRuidoMolestoTipoLocalizacion = redesSaneamientoRuidoMolestoTipoLocalizacion;
	}

	/**
	 * * (redes_suministro_agua_ruido_golpe_ariete)
	 */

	@Column(name = "red_sum_agua_rui_golpe_ariete")
	public Integer getRedesSuministroAguaRuidoGolpeAriete() {
		return this.redesSuministroAguaRuidoGolpeAriete;
	}

	public void setRedesSuministroAguaRuidoGolpeAriete(Integer redesSuministroAguaRuidoGolpeAriete) {
		this.redesSuministroAguaRuidoGolpeAriete = redesSuministroAguaRuidoGolpeAriete;
	}

	/**
	 * * (redes_suministro_agua_ruido_molesto)
	 */

	@Column(name = "red_sum_agua_rui_molesto")
	public Integer getRedesSuministroAguaRuidoMolesto() {
		return this.redesSuministroAguaRuidoMolesto;
	}

	public void setRedesSuministroAguaRuidoMolesto(Integer redesSuministroAguaRuidoMolesto) {
		this.redesSuministroAguaRuidoMolesto = redesSuministroAguaRuidoMolesto;
	}

	/**
	 * * (redes_suministro_agua_tuberias_forradas)
	 */

	@Column(name = "red_sum_agua_tuberias_forradas")
	public Integer getRedesSuministroAguaTuberiasForradas() {
		return this.redesSuministroAguaTuberiasForradas;
	}

	public void setRedesSuministroAguaTuberiasForradas(Integer redesSuministroAguaTuberiasForradas) {
		this.redesSuministroAguaTuberiasForradas = redesSuministroAguaTuberiasForradas;
	}

	/**
	 * * (redes_ventilacion_conducto_individual)
	 */

	@Column(name = "red_vent_conducto_individual")
	public Integer getRedesVentilacionConductoIndividual() {
		return this.redesVentilacionConductoIndividual;
	}

	public void setRedesVentilacionConductoIndividual(Integer redesVentilacionConductoIndividual) {
		this.redesVentilacionConductoIndividual = redesVentilacionConductoIndividual;
	}

	/**
	 * * (redes_ventilacion_conductos_shunt)
	 */

	@Column(name = "red_vent_conductos_shunt")
	public Integer getRedesVentilacionConductosShunt() {
		return this.redesVentilacionConductosShunt;
	}

	public void setRedesVentilacionConductosShunt(Integer redesVentilacionConductosShunt) {
		this.redesVentilacionConductosShunt = redesVentilacionConductosShunt;
	}

	/**
	 * * (redes_ventilacion_ruido_viviendas_colindantes)
	 */

	@Column(name = "red_vent_rui_viv_colindantes")
	public Integer getRedesVentilacionRuidoViviendasColindantes() {
		return this.redesVentilacionRuidoViviendasColindantes;
	}

	public void setRedesVentilacionRuidoViviendasColindantes(Integer redesVentilacionRuidoViviendasColindantes) {
		this.redesVentilacionRuidoViviendasColindantes = redesVentilacionRuidoViviendasColindantes;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcusticaRuidoInstalaciones))
			return false;
		AcusticaRuidoInstalaciones castOther = (AcusticaRuidoInstalaciones) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
