package es.caib.avaedi.common.model;
// Generated 16-dic-2016 12:11:55

import es.caib.avaedi.at4forms.common.basedao.BaseId;
import es.caib.avaedi.at4forms.common.util.FormData2Java;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import org.directwebremoting.annotations.DataTransferObject;

/**
 * AcusticaMejorasAcusticasId generated by hbm2java
 */
@Embeddable
@DataTransferObject
public class AcusticaMejorasAcusticasId extends BaseId implements java.io.Serializable {


	/** serialVersionUID */ 
	private static final long serialVersionUID = 1L;


     private long claveInforme;
     private long mejorasOrden;

    public AcusticaMejorasAcusticasId() {
    }

    public AcusticaMejorasAcusticasId(long claveInforme, long mejorasOrden) {
       this.claveInforme = claveInforme;
       this.mejorasOrden = mejorasOrden;
    }
   

    @Column(name="CLAVE_INFORME", nullable=false, precision=22, scale=0)
    public long getClaveInforme() {
        return this.claveInforme;
    }
    
    public void setClaveInforme(long claveInforme) {
        this.claveInforme = claveInforme;
    }

    @Column(name="MEJORAS_ORDEN", nullable=false, precision=22, scale=0)
    public long getMejorasOrden() {
        return this.mejorasOrden;
    }
    
    public void setMejorasOrden(long mejorasOrden) {
        this.mejorasOrden = mejorasOrden;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  	StringBuffer buffer = new StringBuffer();

		buffer.append(FormData2Java.toString(getClaveInforme()));			
		buffer.append("|"); 
		buffer.append(FormData2Java.toString(getMejorasOrden()));			
      
      return buffer.toString();
     }

    /**
     * fromString
     * @return AcusticaMejorasAcusticasId
     */
     public static AcusticaMejorasAcusticasId fromString(String id) {
     
	    AcusticaMejorasAcusticasId ret = new AcusticaMejorasAcusticasId();
	    String[] codi = id.split("\\|");
	    String val;
	    
	    val = codi[0];
	    ret.setClaveInforme( FormData2Java.toLong(val) );
	    val = codi[1];
	    ret.setMejorasOrden( FormData2Java.toLong(val) );
	    
	    return ret;
     
      
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AcusticaMejorasAcusticasId) ) return false;
		 AcusticaMejorasAcusticasId castOther = ( AcusticaMejorasAcusticasId ) other; 
         
		 return (this.getClaveInforme()==castOther.getClaveInforme())
 && (this.getMejorasOrden()==castOther.getMejorasOrden());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getClaveInforme();
         result = 37 * result + (int) this.getMejorasOrden();
         return result;
   }   


}


