package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Conservacion generated by hbm2java
 */
@Entity
@Table(name = "aed_conservacion")
public class Conservacion extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	private Integer esTecnicoInspeccion;
	/**
	 * (conservacion_valoraciones_tipo_id)
	 */
	private Integer conservacionValoracionesTipoId;
	private String impedimentosVisita;
	/**
	 * (fecha_emision_informe_valoracion)
	 */
	private String fechaEmisionInformeValoracion;
	private String medidasSeguridadVisita;
	private String mediosInspeccion;
	private String nif;
	private Integer numLocalesInspeccionados;
	private Integer numViviendasInspeccionadas;
	private String observaciones;
	private String pruebasRealizadas;
	private String tecnico;
	private String titulacion;
	private Integer existePeligroInminente;
	private String descripcionPeligroInminente;
	private String fechaLimiteActuacion;
	private String medidas;

	public Conservacion() {
	}

	public Conservacion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public Conservacion(Inspeccion inspeccion, Integer esTecnicoInspeccion, Integer conservacionValoracionesTipoId, String impedimentosVisita, String fechaEmisionInformeValoracion, String medidasSeguridadVisita, String mediosInspeccion, String nif, Integer numLocalesInspeccionados, Integer numViviendasInspeccionadas, String observaciones, String pruebasRealizadas, String tecnico, String titulacion, Integer existePeligroInminente, String descripcionPeligroInminente, String fechaLimiteActuacion, String medidas) {
		this.inspeccion = inspeccion;
		this.esTecnicoInspeccion = esTecnicoInspeccion;
		this.conservacionValoracionesTipoId = conservacionValoracionesTipoId;
		this.impedimentosVisita = impedimentosVisita;
		this.fechaEmisionInformeValoracion = fechaEmisionInformeValoracion;
		this.medidasSeguridadVisita = medidasSeguridadVisita;
		this.mediosInspeccion = mediosInspeccion;
		this.nif = nif;
		this.numLocalesInspeccionados = numLocalesInspeccionados;
		this.numViviendasInspeccionadas = numViviendasInspeccionadas;
		this.observaciones = observaciones;
		this.pruebasRealizadas = pruebasRealizadas;
		this.tecnico = tecnico;
		this.titulacion = titulacion;
		this.existePeligroInminente = existePeligroInminente;
		this.descripcionPeligroInminente = descripcionPeligroInminente;
		this.fechaLimiteActuacion = fechaLimiteActuacion;
		this.medidas = medidas;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "es_tecnico_inspeccion")
	public Integer getEsTecnicoInspeccion() {
		return this.esTecnicoInspeccion;
	}

	public void setEsTecnicoInspeccion(Integer esTecnicoInspeccion) {
		this.esTecnicoInspeccion = esTecnicoInspeccion;
	}

	/**
	 * * (conservacion_valoraciones_tipo_id)
	 */

	@Column(name = "cons_valoraciones_tipo_id")
	public Integer getConservacionValoracionesTipoId() {
		return this.conservacionValoracionesTipoId;
	}

	public void setConservacionValoracionesTipoId(Integer conservacionValoracionesTipoId) {
		this.conservacionValoracionesTipoId = conservacionValoracionesTipoId;
	}

	@Column(name = "impedimentos_visita")
	public String getImpedimentosVisita() {
		return this.impedimentosVisita;
	}

	public void setImpedimentosVisita(String impedimentosVisita) {
		this.impedimentosVisita = impedimentosVisita;
	}

	/**
	 * * (fecha_emision_informe_valoracion)
	 */

	@Column(name = "fecha_emision_informe_valorac")
	public String getFechaEmisionInformeValoracion() {
		return this.fechaEmisionInformeValoracion;
	}

	public void setFechaEmisionInformeValoracion(String fechaEmisionInformeValoracion) {
		this.fechaEmisionInformeValoracion = fechaEmisionInformeValoracion;
	}

	@Column(name = "medidas_seguridad_visita")
	public String getMedidasSeguridadVisita() {
		return this.medidasSeguridadVisita;
	}

	public void setMedidasSeguridadVisita(String medidasSeguridadVisita) {
		this.medidasSeguridadVisita = medidasSeguridadVisita;
	}

	@Column(name = "medios_inspeccion")
	public String getMediosInspeccion() {
		return this.mediosInspeccion;
	}

	public void setMediosInspeccion(String mediosInspeccion) {
		this.mediosInspeccion = mediosInspeccion;
	}

	@Column(name = "nif")
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "num_locales_inspeccionados")
	public Integer getNumLocalesInspeccionados() {
		return this.numLocalesInspeccionados;
	}

	public void setNumLocalesInspeccionados(Integer numLocalesInspeccionados) {
		this.numLocalesInspeccionados = numLocalesInspeccionados;
	}

	@Column(name = "num_viviendas_inspeccionadas")
	public Integer getNumViviendasInspeccionadas() {
		return this.numViviendasInspeccionadas;
	}

	public void setNumViviendasInspeccionadas(Integer numViviendasInspeccionadas) {
		this.numViviendasInspeccionadas = numViviendasInspeccionadas;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "pruebas_realizadas")
	public String getPruebasRealizadas() {
		return this.pruebasRealizadas;
	}

	public void setPruebasRealizadas(String pruebasRealizadas) {
		this.pruebasRealizadas = pruebasRealizadas;
	}

	@Column(name = "tecnico")
	public String getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(String tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "titulacion")
	public String getTitulacion() {
		return this.titulacion;
	}

	public void setTitulacion(String titulacion) {
		this.titulacion = titulacion;
	}

	@Column(name = "existe_peligro_inminente")
	public Integer getExistePeligroInminente() {
		return this.existePeligroInminente;
	}

	public void setExistePeligroInminente(Integer existePeligroInminente) {
		this.existePeligroInminente = existePeligroInminente;
	}

	@Column(name = "descripcion_peligro_inminente")
	public String getDescripcionPeligroInminente() {
		return this.descripcionPeligroInminente;
	}

	public void setDescripcionPeligroInminente(String descripcionPeligroInminente) {
		this.descripcionPeligroInminente = descripcionPeligroInminente;
	}

	@Column(name = "fecha_limite_actuacion")
	public String getFechaLimiteActuacion() {
		return this.fechaLimiteActuacion;
	}

	public void setFechaLimiteActuacion(String fechaLimiteActuacion) {
		this.fechaLimiteActuacion = fechaLimiteActuacion;
	}

	@Column(name = "medidas")
	public String getMedidas() {
		return this.medidas;
	}

	public void setMedidas(String medidas) {
		this.medidas = medidas;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Conservacion))
			return false;
		Conservacion castOther = (Conservacion) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
