package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Deficiencia generated by hbm2java
 */
@Entity
@Table(name = "aed_deficiencia")
public class Deficiencia extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private Long id;
	private DeficienciaTipo deficienciaTipo;
	private Inspeccion inspeccion;
	/**
	 * (conservacion_sistemasconstructivos_tipo_id)
	 */
	private Integer conservacionSistemasconstructivosTipoId;
	private String descripcionDeficiencia;
	private Integer esGrave;
	private String localizacionDeficiencia;
	private String nombreDeficiencia;
	private String observaciones;
	private String pruebasEnsayosRealizados;

	public Deficiencia() {
	}

	public Deficiencia(DeficienciaTipo deficienciaTipo, Inspeccion inspeccion) {
		this.deficienciaTipo = deficienciaTipo;
		this.inspeccion = inspeccion;
	}

	public Deficiencia(DeficienciaTipo deficienciaTipo, Inspeccion inspeccion, Integer conservacionSistemasconstructivosTipoId, String descripcionDeficiencia, Integer esGrave, String localizacionDeficiencia, String nombreDeficiencia, String observaciones, String pruebasEnsayosRealizados) {
		this.deficienciaTipo = deficienciaTipo;
		this.inspeccion = inspeccion;
		this.conservacionSistemasconstructivosTipoId = conservacionSistemasconstructivosTipoId;
		this.descripcionDeficiencia = descripcionDeficiencia;
		this.esGrave = esGrave;
		this.localizacionDeficiencia = localizacionDeficiencia;
		this.nombreDeficiencia = nombreDeficiencia;
		this.observaciones = observaciones;
		this.pruebasEnsayosRealizados = pruebasEnsayosRealizados;
	}

	@SequenceGenerator(name = "generator", sequenceName = "AED_DEFICIENCIA_SEQ", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_deficiencia", nullable = false)
	public DeficienciaTipo getDeficienciaTipo() {
		return this.deficienciaTipo;
	}

	public void setDeficienciaTipo(DeficienciaTipo deficienciaTipo) {
		this.deficienciaTipo = deficienciaTipo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (conservacion_sistemasconstructivos_tipo_id)
	 */

	@Column(name = "cons_sistemas_construc_tipo_id")
	public Integer getConservacionSistemasconstructivosTipoId() {
		return this.conservacionSistemasconstructivosTipoId;
	}

	public void setConservacionSistemasconstructivosTipoId(Integer conservacionSistemasconstructivosTipoId) {
		this.conservacionSistemasconstructivosTipoId = conservacionSistemasconstructivosTipoId;
	}

	@Column(name = "descripcion_deficiencia")
	public String getDescripcionDeficiencia() {
		return this.descripcionDeficiencia;
	}

	public void setDescripcionDeficiencia(String descripcionDeficiencia) {
		this.descripcionDeficiencia = descripcionDeficiencia;
	}

	@Column(name = "es_grave")
	public Integer getEsGrave() {
		return this.esGrave;
	}

	public void setEsGrave(Integer esGrave) {
		this.esGrave = esGrave;
	}

	@Column(name = "localizacion_deficiencia")
	public String getLocalizacionDeficiencia() {
		return this.localizacionDeficiencia;
	}

	public void setLocalizacionDeficiencia(String localizacionDeficiencia) {
		this.localizacionDeficiencia = localizacionDeficiencia;
	}

	@Column(name = "nombre_deficiencia")
	public String getNombreDeficiencia() {
		return this.nombreDeficiencia;
	}

	public void setNombreDeficiencia(String nombreDeficiencia) {
		this.nombreDeficiencia = nombreDeficiencia;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "pruebas_ensayos_realizados")
	public String getPruebasEnsayosRealizados() {
		return this.pruebasEnsayosRealizados;
	}

	public void setPruebasEnsayosRealizados(String pruebasEnsayosRealizados) {
		this.pruebasEnsayosRealizados = pruebasEnsayosRealizados;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Deficiencia))
			return false;
		Deficiencia castOther = (Deficiencia) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		return result;
	}

}
