package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * EficienciasEnergeticas generated by hbm2java
 */
@Entity
@Table(name = "aed_eficienciasenergeticas")
public class EficienciasEnergeticas extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	private Integer ambitoAplicacion;
	private String demandaGlobalCalefaccion;
	/**
	 * (demanda_global_calefaccion_calificacion_tipo_id)
	 */
	private Integer demandaGlobalCalefaccionCalificacionTipoId;
	private String demandaGlobalRefrigeracion;
	/**
	 * (demanda_global_refrigeracion_calificacion_tipo_id)
	 */
	private Integer demandaGlobalRefrigeracionCalificacionTipoId;
	private Integer esTecnicoInspeccion;
	/**
	 * (indicador_global_calificacion_tipo_id)
	 */
	private Integer indicadorGlobalCalificacionTipoId;
	private String indicadorGlobalEmisiones;
	/**
	 * (indicador_global_primaria_calificacion_tipo_id)
	 */
	private Integer indicadorGlobalPrimariaCalificacionTipoId;
	/**
	 * (indicador_global_primaria_consumo)
	 */
	private String indicadorGlobalPrimariaConsumo;
	/**
	 * (indicador_parcial_emisiones_acs)
	 */
	private String indicadorParcialEmisionesAcs;
	/**
	 * (indicador_parcial_emisiones_calefaccion)
	 */
	private String indicadorParcialEmisionesCalefaccion;
	/**
	 * (indicador_parcial_emisiones_refrigeracion)
	 */
	private String indicadorParcialEmisionesRefrigeracion;
	private String indicadorParcialPrimariaAcs;
	/**
	 * (indicador_parcial_primaria_calefaccion)
	 */
	private String indicadorParcialPrimariaCalefaccion;
	/**
	 * (indicador_parcial_primaria_refrigeracion)
	 */
	private String indicadorParcialPrimariaRefrigeracion;
	private String nif;
	private String observaciones;
	private String tecnico;
	private String titulacion;

	public EficienciasEnergeticas() {
	}

	public EficienciasEnergeticas(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public EficienciasEnergeticas(Inspeccion inspeccion, Integer ambitoAplicacion, String demandaGlobalCalefaccion, Integer demandaGlobalCalefaccionCalificacionTipoId, String demandaGlobalRefrigeracion, Integer demandaGlobalRefrigeracionCalificacionTipoId, Integer esTecnicoInspeccion, Integer indicadorGlobalCalificacionTipoId, String indicadorGlobalEmisiones, Integer indicadorGlobalPrimariaCalificacionTipoId, String indicadorGlobalPrimariaConsumo, String indicadorParcialEmisionesAcs, String indicadorParcialEmisionesCalefaccion, String indicadorParcialEmisionesRefrigeracion, String indicadorParcialPrimariaAcs, String indicadorParcialPrimariaCalefaccion, String indicadorParcialPrimariaRefrigeracion, String nif, String observaciones, String tecnico, String titulacion) {
		this.inspeccion = inspeccion;
		this.ambitoAplicacion = ambitoAplicacion;
		this.demandaGlobalCalefaccion = demandaGlobalCalefaccion;
		this.demandaGlobalCalefaccionCalificacionTipoId = demandaGlobalCalefaccionCalificacionTipoId;
		this.demandaGlobalRefrigeracion = demandaGlobalRefrigeracion;
		this.demandaGlobalRefrigeracionCalificacionTipoId = demandaGlobalRefrigeracionCalificacionTipoId;
		this.esTecnicoInspeccion = esTecnicoInspeccion;
		this.indicadorGlobalCalificacionTipoId = indicadorGlobalCalificacionTipoId;
		this.indicadorGlobalEmisiones = indicadorGlobalEmisiones;
		this.indicadorGlobalPrimariaCalificacionTipoId = indicadorGlobalPrimariaCalificacionTipoId;
		this.indicadorGlobalPrimariaConsumo = indicadorGlobalPrimariaConsumo;
		this.indicadorParcialEmisionesAcs = indicadorParcialEmisionesAcs;
		this.indicadorParcialEmisionesCalefaccion = indicadorParcialEmisionesCalefaccion;
		this.indicadorParcialEmisionesRefrigeracion = indicadorParcialEmisionesRefrigeracion;
		this.indicadorParcialPrimariaAcs = indicadorParcialPrimariaAcs;
		this.indicadorParcialPrimariaCalefaccion = indicadorParcialPrimariaCalefaccion;
		this.indicadorParcialPrimariaRefrigeracion = indicadorParcialPrimariaRefrigeracion;
		this.nif = nif;
		this.observaciones = observaciones;
		this.tecnico = tecnico;
		this.titulacion = titulacion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "ambito_aplicacion")
	public Integer getAmbitoAplicacion() {
		return this.ambitoAplicacion;
	}

	public void setAmbitoAplicacion(Integer ambitoAplicacion) {
		this.ambitoAplicacion = ambitoAplicacion;
	}

	@Column(name = "demanda_global_calefaccion")
	public String getDemandaGlobalCalefaccion() {
		return this.demandaGlobalCalefaccion;
	}

	public void setDemandaGlobalCalefaccion(String demandaGlobalCalefaccion) {
		this.demandaGlobalCalefaccion = demandaGlobalCalefaccion;
	}

	/**
	 * * (demanda_global_calefaccion_calificacion_tipo_id)
	 */

	@Column(name = "deman_glob_calef_calif_tip_id")
	public Integer getDemandaGlobalCalefaccionCalificacionTipoId() {
		return this.demandaGlobalCalefaccionCalificacionTipoId;
	}

	public void setDemandaGlobalCalefaccionCalificacionTipoId(Integer demandaGlobalCalefaccionCalificacionTipoId) {
		this.demandaGlobalCalefaccionCalificacionTipoId = demandaGlobalCalefaccionCalificacionTipoId;
	}

	@Column(name = "demanda_global_refrigeracion")
	public String getDemandaGlobalRefrigeracion() {
		return this.demandaGlobalRefrigeracion;
	}

	public void setDemandaGlobalRefrigeracion(String demandaGlobalRefrigeracion) {
		this.demandaGlobalRefrigeracion = demandaGlobalRefrigeracion;
	}

	/**
	 * * (demanda_global_refrigeracion_calificacion_tipo_id)
	 */

	@Column(name = "deman_glob_refrig_calif_tip_id")
	public Integer getDemandaGlobalRefrigeracionCalificacionTipoId() {
		return this.demandaGlobalRefrigeracionCalificacionTipoId;
	}

	public void setDemandaGlobalRefrigeracionCalificacionTipoId(Integer demandaGlobalRefrigeracionCalificacionTipoId) {
		this.demandaGlobalRefrigeracionCalificacionTipoId = demandaGlobalRefrigeracionCalificacionTipoId;
	}

	@Column(name = "es_tecnico_inspeccion")
	public Integer getEsTecnicoInspeccion() {
		return this.esTecnicoInspeccion;
	}

	public void setEsTecnicoInspeccion(Integer esTecnicoInspeccion) {
		this.esTecnicoInspeccion = esTecnicoInspeccion;
	}

	/**
	 * * (indicador_global_calificacion_tipo_id)
	 */

	@Column(name = "ind_global_calificacion_tip_id")
	public Integer getIndicadorGlobalCalificacionTipoId() {
		return this.indicadorGlobalCalificacionTipoId;
	}

	public void setIndicadorGlobalCalificacionTipoId(Integer indicadorGlobalCalificacionTipoId) {
		this.indicadorGlobalCalificacionTipoId = indicadorGlobalCalificacionTipoId;
	}

	@Column(name = "indicador_global_emisiones")
	public String getIndicadorGlobalEmisiones() {
		return this.indicadorGlobalEmisiones;
	}

	public void setIndicadorGlobalEmisiones(String indicadorGlobalEmisiones) {
		this.indicadorGlobalEmisiones = indicadorGlobalEmisiones;
	}

	/**
	 * * (indicador_global_primaria_calificacion_tipo_id)
	 */

	@Column(name = "ind_glob_primaria_calif_tip_id")
	public Integer getIndicadorGlobalPrimariaCalificacionTipoId() {
		return this.indicadorGlobalPrimariaCalificacionTipoId;
	}

	public void setIndicadorGlobalPrimariaCalificacionTipoId(Integer indicadorGlobalPrimariaCalificacionTipoId) {
		this.indicadorGlobalPrimariaCalificacionTipoId = indicadorGlobalPrimariaCalificacionTipoId;
	}

	/**
	 * * (indicador_global_primaria_consumo)
	 */

	@Column(name = "ind_global_primaria_consumo")
	public String getIndicadorGlobalPrimariaConsumo() {
		return this.indicadorGlobalPrimariaConsumo;
	}

	public void setIndicadorGlobalPrimariaConsumo(String indicadorGlobalPrimariaConsumo) {
		this.indicadorGlobalPrimariaConsumo = indicadorGlobalPrimariaConsumo;
	}

	/**
	 * * (indicador_parcial_emisiones_acs)
	 */

	@Column(name = "ind_parcial_emisiones_acs")
	public String getIndicadorParcialEmisionesAcs() {
		return this.indicadorParcialEmisionesAcs;
	}

	public void setIndicadorParcialEmisionesAcs(String indicadorParcialEmisionesAcs) {
		this.indicadorParcialEmisionesAcs = indicadorParcialEmisionesAcs;
	}

	/**
	 * * (indicador_parcial_emisiones_calefaccion)
	 */

	@Column(name = "ind_parcial_emisiones_calef")
	public String getIndicadorParcialEmisionesCalefaccion() {
		return this.indicadorParcialEmisionesCalefaccion;
	}

	public void setIndicadorParcialEmisionesCalefaccion(String indicadorParcialEmisionesCalefaccion) {
		this.indicadorParcialEmisionesCalefaccion = indicadorParcialEmisionesCalefaccion;
	}

	/**
	 * * (indicador_parcial_emisiones_refrigeracion)
	 */

	@Column(name = "ind_parcial_emisiones_refrig")
	public String getIndicadorParcialEmisionesRefrigeracion() {
		return this.indicadorParcialEmisionesRefrigeracion;
	}

	public void setIndicadorParcialEmisionesRefrigeracion(String indicadorParcialEmisionesRefrigeracion) {
		this.indicadorParcialEmisionesRefrigeracion = indicadorParcialEmisionesRefrigeracion;
	}

	@Column(name = "indicador_parcial_primaria_acs")
	public String getIndicadorParcialPrimariaAcs() {
		return this.indicadorParcialPrimariaAcs;
	}

	public void setIndicadorParcialPrimariaAcs(String indicadorParcialPrimariaAcs) {
		this.indicadorParcialPrimariaAcs = indicadorParcialPrimariaAcs;
	}

	/**
	 * * (indicador_parcial_primaria_calefaccion)
	 */

	@Column(name = "ind_parcial_primaria_calef")
	public String getIndicadorParcialPrimariaCalefaccion() {
		return this.indicadorParcialPrimariaCalefaccion;
	}

	public void setIndicadorParcialPrimariaCalefaccion(String indicadorParcialPrimariaCalefaccion) {
		this.indicadorParcialPrimariaCalefaccion = indicadorParcialPrimariaCalefaccion;
	}

	/**
	 * * (indicador_parcial_primaria_refrigeracion)
	 */

	@Column(name = "ind_parcial_primaria_refrig")
	public String getIndicadorParcialPrimariaRefrigeracion() {
		return this.indicadorParcialPrimariaRefrigeracion;
	}

	public void setIndicadorParcialPrimariaRefrigeracion(String indicadorParcialPrimariaRefrigeracion) {
		this.indicadorParcialPrimariaRefrigeracion = indicadorParcialPrimariaRefrigeracion;
	}

	@Column(name = "nif")
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "tecnico")
	public String getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(String tecnico) {
		this.tecnico = tecnico;
	}

	@Column(name = "titulacion")
	public String getTitulacion() {
		return this.titulacion;
	}

	public void setTitulacion(String titulacion) {
		this.titulacion = titulacion;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EficienciasEnergeticas))
			return false;
		EficienciasEnergeticas castOther = (EficienciasEnergeticas) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
