package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Estructura generated by hbm2java
 */
@Entity
@Table(name = "aed_estructura")
public class Estructura extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	/**
	 * (cubierta_forjadoinclinado_texto)
	 */
	private String cubiertaForjadoinclinadoTexto;
	private String cubiertaOtrosTexto;
	/**
	 * (horizontalplantatipo_otros_texto)
	 */
	private String horizontalplantatipoOtrosTexto;
	private String horizontalsueloOtrosTexto;
	private String observaciones;
	private String verticalOtros;
	private String verticalOtrosTexto;

	public Estructura() {
	}

	public Estructura(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public Estructura(Inspeccion inspeccion, String cubiertaForjadoinclinadoTexto, String cubiertaOtrosTexto, String horizontalplantatipoOtrosTexto, String horizontalsueloOtrosTexto, String observaciones, String verticalOtros, String verticalOtrosTexto) {
		this.inspeccion = inspeccion;
		this.cubiertaForjadoinclinadoTexto = cubiertaForjadoinclinadoTexto;
		this.cubiertaOtrosTexto = cubiertaOtrosTexto;
		this.horizontalplantatipoOtrosTexto = horizontalplantatipoOtrosTexto;
		this.horizontalsueloOtrosTexto = horizontalsueloOtrosTexto;
		this.observaciones = observaciones;
		this.verticalOtros = verticalOtros;
		this.verticalOtrosTexto = verticalOtrosTexto;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (cubierta_forjadoinclinado_texto)
	 */

	@Column(name = "cubierta_forjinclinado_texto")
	public String getCubiertaForjadoinclinadoTexto() {
		return this.cubiertaForjadoinclinadoTexto;
	}

	public void setCubiertaForjadoinclinadoTexto(String cubiertaForjadoinclinadoTexto) {
		this.cubiertaForjadoinclinadoTexto = cubiertaForjadoinclinadoTexto;
	}

	@Column(name = "cubierta_otros_texto")
	public String getCubiertaOtrosTexto() {
		return this.cubiertaOtrosTexto;
	}

	public void setCubiertaOtrosTexto(String cubiertaOtrosTexto) {
		this.cubiertaOtrosTexto = cubiertaOtrosTexto;
	}

	/**
	 * * (horizontalplantatipo_otros_texto)
	 */

	@Column(name = "horplantatipo_otros_texto")
	public String getHorizontalplantatipoOtrosTexto() {
		return this.horizontalplantatipoOtrosTexto;
	}

	public void setHorizontalplantatipoOtrosTexto(String horizontalplantatipoOtrosTexto) {
		this.horizontalplantatipoOtrosTexto = horizontalplantatipoOtrosTexto;
	}

	@Column(name = "horizontalsuelo_otros_texto")
	public String getHorizontalsueloOtrosTexto() {
		return this.horizontalsueloOtrosTexto;
	}

	public void setHorizontalsueloOtrosTexto(String horizontalsueloOtrosTexto) {
		this.horizontalsueloOtrosTexto = horizontalsueloOtrosTexto;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "vertical_otros", length = 1)
	public String getVerticalOtros() {
		return this.verticalOtros;
	}

	public void setVerticalOtros(String verticalOtros) {
		this.verticalOtros = verticalOtros;
	}

	@Column(name = "vertical_otros_texto")
	public String getVerticalOtrosTexto() {
		return this.verticalOtrosTexto;
	}

	public void setVerticalOtrosTexto(String verticalOtrosTexto) {
		this.verticalOtrosTexto = verticalOtrosTexto;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Estructura))
			return false;
		Estructura castOther = (Estructura) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
