package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Historico generated by hbm2java
 */
@Entity
@Table(name = "aed_historico")
public class Historico extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Inspeccion inspeccion;
	private String fechaInspeccion;
	/**
	 * (grado_ejecucion_efectividad_obras)
	 */
	private String gradoEjecucionEfectividadObras;
	private String observaciones;
	private String resultado;
	private String tecnico;

	public Historico() {
	}

	public Historico(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public Historico(Inspeccion inspeccion, String fechaInspeccion, String gradoEjecucionEfectividadObras, String observaciones, String resultado, String tecnico) {
		this.inspeccion = inspeccion;
		this.fechaInspeccion = fechaInspeccion;
		this.gradoEjecucionEfectividadObras = gradoEjecucionEfectividadObras;
		this.observaciones = observaciones;
		this.resultado = resultado;
		this.tecnico = tecnico;
	}

	@SequenceGenerator(name = "generator", sequenceName = "AED_HISTORICO_SEQ", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "fecha_inspeccion")
	public String getFechaInspeccion() {
		return this.fechaInspeccion;
	}

	public void setFechaInspeccion(String fechaInspeccion) {
		this.fechaInspeccion = fechaInspeccion;
	}

	/**
	 * * (grado_ejecucion_efectividad_obras)
	 */

	@Column(name = "grado_ejecucion_efectiv_obras")
	public String getGradoEjecucionEfectividadObras() {
		return this.gradoEjecucionEfectividadObras;
	}

	public void setGradoEjecucionEfectividadObras(String gradoEjecucionEfectividadObras) {
		this.gradoEjecucionEfectividadObras = gradoEjecucionEfectividadObras;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "resultado")
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "tecnico")
	public String getTecnico() {
		return this.tecnico;
	}

	public void setTecnico(String tecnico) {
		this.tecnico = tecnico;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Historico))
			return false;
		Historico castOther = (Historico) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		return result;
	}

}
