package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Inspeccion generated by hbm2java
 */
@Entity
@Table(name = "aed_inspeccion")
public class Inspeccion extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int id;
	private Informe informe;
	/**
	 * (accesibilidad_ajustesrazonables_costes)
	 */
	private String accesibilidadAjustesrazonablesCostes;
	/**
	 * (conservacion_datosgenerales_archivos)
	 */
	private String conservacionDatosgeneralesArchivos;
	private Integer ieeCompleta;
	private BigDecimal alturaSobreRasante;
	private Integer anoConstruccion;
	private String anoConstruccionReferencia;
	private Integer anoRehabilitacion;
	private String anoRehabilitacionReferencia;
	/**
	 * (inspeccion_datosedificio_nucleosescaleras_tipo_id)
	 */
	private Integer inspeccionDatosedificioNucleosescalerasTipoId;
	/**
	 * (inspeccion_datosedificio_parcela_tipo_id)
	 */
	private Integer inspeccionDatosedificioParcelaTipoId;
	/**
	 * (inspeccion_datosedificio_unnucleoescaleras_tipo_id)
	 */
	private Integer inspeccionDatosedificioUnnucleoescalerasTipoId;
	/**
	 * (inspeccion_datosedificio_uso_tipo_id)
	 */
	private Integer inspeccionDatosedificioUsoTipoId;
	private Integer mediaViviendasPorPlanta;
	private Integer numAparcamientos;
	private Integer numLocales;
	private Integer numTrasteros;
	private Integer numViviendas;
	/**
	 * (plantas_bajo_rasante_uso_principal)
	 */
	private Integer plantasBajoRasanteUsoPrincipal;
	/**
	 * (plantas_bajo_rasante_usos_secundarios)
	 */
	private Integer plantasBajoRasanteUsosSecundarios;
	/**
	 * (plantas_bajo_rasante_usos_secundarios_tipo)
	 */
	private String plantasBajoRasanteUsosSecundariosTipo;
	/**
	 * (plantas_sobre_rasante_uso_principal)
	 */
	private Integer plantasSobreRasanteUsoPrincipal;
	/**
	 * (plantas_sobre_rasante_usos_secundarios)
	 */
	private Integer plantasSobreRasanteUsosSecundarios;
	/**
	 * (plantas_sobre_rasante_usos_secundarios_tipo)
	 */
	private String plantasSobreRasanteUsosSecundariosTipo;
	private BigDecimal superficieConstruida;
	private BigDecimal superficieMediaAparcamientos;
	private BigDecimal superficieMediaLocales;
	private BigDecimal superficieMediaTrasteros;
	private BigDecimal superficieMediaViviendas;
	private BigDecimal superficieParcela;
	private String totalAscensores;
	private String totalEscaleras;
	/**
	 * (total_viviendas_con_acceso_varios_nucleos)
	 */
	private String totalViviendasConAccesoVariosNucleos;
	/**
	 * (total_viviendas_sin_acceso_ascensor)
	 */
	private String totalViviendasSinAccesoAscensor;
	private String usoTexto;
	private Integer numero;
	private String tipoVia;
	private String via;
	private Boolean principal;
	private String referenciaCatastral;
	private String edificioCodigoPostal;
	private String edificioComunTexto;
	/**
	 * (edificio_inspeccion_identificacionedificio_comunes_tipo_id)
	 */
	private Integer edificioInspeccionIdentificacionedificioComunesTipoId;
	/**
	 * (edificio_inspeccion_identificacionedificio_objeto_tipo_id)
	 */
	private Integer edificioInspeccionIdentificacionedificioObjetoTipoId;
	/**
	 * (edificio_inspeccion_propiedad_regimen_tipo_id)
	 */
	private Integer edificioInspeccionPropiedadRegimenTipoId;
	private String edificioNumeroManual;
	private String edificioObjetoTexto;
	private String edificioObservaciones;
	private String edificioPisoLetra;
	private String edificioPoblacion;
	private String edificioProvincia;
	private Integer edificioProvinciaId;
	private String edificioRegimenTexto;
	private String edificioTipoViaManual;
	private String edificioViaManual;
	private String propiedadNif;
	private String propiedadTitular;
	private String representanteCodigoPostal;
	private String representanteCondicion;
	private String representanteDireccion;
	private String representanteEmail;
	private String representanteNif;
	private String representanteNombre;
	private String representantePoblacion;
	private String representanteProvincia;
	private String representanteTelefonoFijo;
	private String representanteTelefonoMovil;
	private String tecnicoNif;
	private String tecnicoTecnico;
	private String tecnicoTitulacion;
	private AccesibilidadPublicos accesibilidadPublicos;
	private AcusticaRuidosInterioresUniones acusticaRuidosInterioresUniones;
	private Set<FechaVisita> fechasVisitas = new HashSet<FechaVisita>(0);
	private AcusticaValoracionFinal acusticaValoracionFinal;
	private AcusticaRuidosInterioresVerticales acusticaRuidosInterioresVerticales;
	private AcusticaComprobaciones acusticaComprobaciones;
	private Instalaciones instalaciones;
	private CerramientosCubiertas cerramientosCubiertas;
	private Set<ValoracionParcial> valoracionesParciales = new HashSet<ValoracionParcial>(0);
	private AccesibilidadValoracionFinales accesibilidadValoracionFinales;
	private AcusticaRuidoInstalaciones acusticaRuidoInstalaciones;
	private Estructura estructura;
	private Cimentaciones cimentaciones;
	private AccesibilidadAjustesRazonables accesibilidadAjustesRazonables;
	private EficienciasEnergeticas eficienciasEnergeticas;
	private Set<DocumentacionOtro> documentacionOtros = new HashSet<DocumentacionOtro>(0);
	private AcusticaRuidosExteriores acusticaRuidosExteriores;
    private Set<AcusticaMejorasAcusticas> acusticaMejorasAcusticas = new HashSet<AcusticaMejorasAcusticas>(0);
	private AcusticaRuidosInterioresHorizontales acusticaRuidosInterioresHorizontales;
	private AcusticaDatosGenerales acusticaDatosGenerales;
	private Acusticas acusticas;
	private Set<Deficiencia> deficiencias = new HashSet<Deficiencia>(0);
	private Set<Valor> valores = new LinkedHashSet<Valor>(0);
	private Conservacion conservacion;
	private Set<Historico> historicos = new HashSet<Historico>(0);

	public Inspeccion() {
	}

	public Inspeccion(Informe informe) {
		this.informe = informe;
	}

	public Inspeccion(Informe informe, String accesibilidadAjustesrazonablesCostes, String conservacionDatosgeneralesArchivos, Integer ieeCompleta, BigDecimal alturaSobreRasante, Integer anoConstruccion, String anoConstruccionReferencia, Integer anoRehabilitacion, String anoRehabilitacionReferencia, Integer inspeccionDatosedificioNucleosescalerasTipoId, Integer inspeccionDatosedificioParcelaTipoId, Integer inspeccionDatosedificioUnnucleoescalerasTipoId, Integer inspeccionDatosedificioUsoTipoId, Integer mediaViviendasPorPlanta, Integer numAparcamientos, Integer numLocales, Integer numTrasteros, Integer numViviendas, Integer plantasBajoRasanteUsoPrincipal, Integer plantasBajoRasanteUsosSecundarios, String plantasBajoRasanteUsosSecundariosTipo, Integer plantasSobreRasanteUsoPrincipal, Integer plantasSobreRasanteUsosSecundarios, String plantasSobreRasanteUsosSecundariosTipo, BigDecimal superficieConstruida, BigDecimal superficieMediaAparcamientos, BigDecimal superficieMediaLocales, BigDecimal superficieMediaTrasteros, BigDecimal superficieMediaViviendas, BigDecimal superficieParcela, String totalAscensores, String totalEscaleras, String totalViviendasConAccesoVariosNucleos, String totalViviendasSinAccesoAscensor, String usoTexto, Integer numero, String tipoVia, String via, Boolean principal, String referenciaCatastral, String edificioCodigoPostal, String edificioComunTexto, Integer edificioInspeccionIdentificacionedificioComunesTipoId, Integer edificioInspeccionIdentificacionedificioObjetoTipoId, Integer edificioInspeccionPropiedadRegimenTipoId, String edificioNumeroManual, String edificioObjetoTexto, String edificioObservaciones, String edificioPisoLetra, String edificioPoblacion, String edificioProvincia, Integer edificioProvinciaId, String edificioRegimenTexto, String edificioTipoViaManual, String edificioViaManual, String propiedadNif, String propiedadTitular, String representanteCodigoPostal, String representanteCondicion, String representanteDireccion, String representanteEmail, String representanteNif, String representanteNombre, String representantePoblacion, String representanteProvincia, String representanteTelefonoFijo, String representanteTelefonoMovil, String tecnicoNif, String tecnicoTecnico, String tecnicoTitulacion, AccesibilidadPublicos accesibilidadPublicos, AcusticaRuidosInterioresUniones acusticaRuidosInterioresUniones, Set<FechaVisita> fechasVisitas, AcusticaValoracionFinal acusticaValoracionFinal, AcusticaRuidosInterioresVerticales acusticaRuidosInterioresVerticales, AcusticaComprobaciones acusticaComprobaciones, Instalaciones instalaciones, CerramientosCubiertas cerramientosCubiertas, Set<ValoracionParcial> valoracionesParciales, AccesibilidadValoracionFinales accesibilidadValoracionFinales, AcusticaRuidoInstalaciones acusticaRuidoInstalaciones, Estructura estructura, Cimentaciones cimentaciones, AccesibilidadAjustesRazonables accesibilidadAjustesRazonables, EficienciasEnergeticas eficienciasEnergeticas, Set<DocumentacionOtro> documentacionOtros, AcusticaRuidosExteriores acusticaRuidosExteriores, AcusticaRuidosInterioresHorizontales acusticaRuidosInterioresHorizontales, AcusticaDatosGenerales acusticaDatosGenerales, Acusticas acusticas, Set<Deficiencia> deficiencias, Set<Valor> valores, Conservacion conservacion, Set<Historico> historicos) {
		this.informe = informe;
		this.accesibilidadAjustesrazonablesCostes = accesibilidadAjustesrazonablesCostes;
		this.conservacionDatosgeneralesArchivos = conservacionDatosgeneralesArchivos;
		this.ieeCompleta = ieeCompleta;
		this.alturaSobreRasante = alturaSobreRasante;
		this.anoConstruccion = anoConstruccion;
		this.anoConstruccionReferencia = anoConstruccionReferencia;
		this.anoRehabilitacion = anoRehabilitacion;
		this.anoRehabilitacionReferencia = anoRehabilitacionReferencia;
		this.inspeccionDatosedificioNucleosescalerasTipoId = inspeccionDatosedificioNucleosescalerasTipoId;
		this.inspeccionDatosedificioParcelaTipoId = inspeccionDatosedificioParcelaTipoId;
		this.inspeccionDatosedificioUnnucleoescalerasTipoId = inspeccionDatosedificioUnnucleoescalerasTipoId;
		this.inspeccionDatosedificioUsoTipoId = inspeccionDatosedificioUsoTipoId;
		this.mediaViviendasPorPlanta = mediaViviendasPorPlanta;
		this.numAparcamientos = numAparcamientos;
		this.numLocales = numLocales;
		this.numTrasteros = numTrasteros;
		this.numViviendas = numViviendas;
		this.plantasBajoRasanteUsoPrincipal = plantasBajoRasanteUsoPrincipal;
		this.plantasBajoRasanteUsosSecundarios = plantasBajoRasanteUsosSecundarios;
		this.plantasBajoRasanteUsosSecundariosTipo = plantasBajoRasanteUsosSecundariosTipo;
		this.plantasSobreRasanteUsoPrincipal = plantasSobreRasanteUsoPrincipal;
		this.plantasSobreRasanteUsosSecundarios = plantasSobreRasanteUsosSecundarios;
		this.plantasSobreRasanteUsosSecundariosTipo = plantasSobreRasanteUsosSecundariosTipo;
		this.superficieConstruida = superficieConstruida;
		this.superficieMediaAparcamientos = superficieMediaAparcamientos;
		this.superficieMediaLocales = superficieMediaLocales;
		this.superficieMediaTrasteros = superficieMediaTrasteros;
		this.superficieMediaViviendas = superficieMediaViviendas;
		this.superficieParcela = superficieParcela;
		this.totalAscensores = totalAscensores;
		this.totalEscaleras = totalEscaleras;
		this.totalViviendasConAccesoVariosNucleos = totalViviendasConAccesoVariosNucleos;
		this.totalViviendasSinAccesoAscensor = totalViviendasSinAccesoAscensor;
		this.usoTexto = usoTexto;
		this.numero = numero;
		this.tipoVia = tipoVia;
		this.via = via;
		this.principal = principal;
		this.referenciaCatastral = referenciaCatastral;
		this.edificioCodigoPostal = edificioCodigoPostal;
		this.edificioComunTexto = edificioComunTexto;
		this.edificioInspeccionIdentificacionedificioComunesTipoId = edificioInspeccionIdentificacionedificioComunesTipoId;
		this.edificioInspeccionIdentificacionedificioObjetoTipoId = edificioInspeccionIdentificacionedificioObjetoTipoId;
		this.edificioInspeccionPropiedadRegimenTipoId = edificioInspeccionPropiedadRegimenTipoId;
		this.edificioNumeroManual = edificioNumeroManual;
		this.edificioObjetoTexto = edificioObjetoTexto;
		this.edificioObservaciones = edificioObservaciones;
		this.edificioPisoLetra = edificioPisoLetra;
		this.edificioPoblacion = edificioPoblacion;
		this.edificioProvincia = edificioProvincia;
		this.edificioProvinciaId = edificioProvinciaId;
		this.edificioRegimenTexto = edificioRegimenTexto;
		this.edificioTipoViaManual = edificioTipoViaManual;
		this.edificioViaManual = edificioViaManual;
		this.propiedadNif = propiedadNif;
		this.propiedadTitular = propiedadTitular;
		this.representanteCodigoPostal = representanteCodigoPostal;
		this.representanteCondicion = representanteCondicion;
		this.representanteDireccion = representanteDireccion;
		this.representanteEmail = representanteEmail;
		this.representanteNif = representanteNif;
		this.representanteNombre = representanteNombre;
		this.representantePoblacion = representantePoblacion;
		this.representanteProvincia = representanteProvincia;
		this.representanteTelefonoFijo = representanteTelefonoFijo;
		this.representanteTelefonoMovil = representanteTelefonoMovil;
		this.tecnicoNif = tecnicoNif;
		this.tecnicoTecnico = tecnicoTecnico;
		this.tecnicoTitulacion = tecnicoTitulacion;
		this.accesibilidadPublicos = accesibilidadPublicos;
		this.acusticaRuidosInterioresUniones = acusticaRuidosInterioresUniones;
		this.fechasVisitas = fechasVisitas;
		this.acusticaValoracionFinal = acusticaValoracionFinal;
		this.acusticaRuidosInterioresVerticales = acusticaRuidosInterioresVerticales;
		this.acusticaComprobaciones = acusticaComprobaciones;
		this.instalaciones = instalaciones;
		this.cerramientosCubiertas = cerramientosCubiertas;
		this.valoracionesParciales = valoracionesParciales;
		this.accesibilidadValoracionFinales = accesibilidadValoracionFinales;
		this.acusticaRuidoInstalaciones = acusticaRuidoInstalaciones;
		this.estructura = estructura;
		this.cimentaciones = cimentaciones;
		this.accesibilidadAjustesRazonables = accesibilidadAjustesRazonables;
		this.eficienciasEnergeticas = eficienciasEnergeticas;
		this.documentacionOtros = documentacionOtros;
		this.acusticaRuidosExteriores = acusticaRuidosExteriores;
		this.acusticaRuidosInterioresHorizontales = acusticaRuidosInterioresHorizontales;
		this.acusticaDatosGenerales = acusticaDatosGenerales;
		this.acusticas = acusticas;
		this.deficiencias = deficiencias;
		this.valores = valores;
		this.conservacion = conservacion;
		this.historicos = historicos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "informe"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Informe getInforme() {
		return this.informe;
	}

	public void setInforme(Informe informe) {
		this.informe = informe;
	}

	/**
	 * * (accesibilidad_ajustesrazonables_costes)
	 */

	@Column(name = "acc_ajustesrazonables_costes")
	public String getAccesibilidadAjustesrazonablesCostes() {
		return this.accesibilidadAjustesrazonablesCostes;
	}

	public void setAccesibilidadAjustesrazonablesCostes(String accesibilidadAjustesrazonablesCostes) {
		this.accesibilidadAjustesrazonablesCostes = accesibilidadAjustesrazonablesCostes;
	}

	/**
	 * * (conservacion_datosgenerales_archivos)
	 */

	@Column(name = "cons_datosgenerales_archivos")
	public String getConservacionDatosgeneralesArchivos() {
		return this.conservacionDatosgeneralesArchivos;
	}

	public void setConservacionDatosgeneralesArchivos(String conservacionDatosgeneralesArchivos) {
		this.conservacionDatosgeneralesArchivos = conservacionDatosgeneralesArchivos;
	}

	@Column(name = "iee_completa")
	public Integer getIeeCompleta() {
		return this.ieeCompleta;
	}

	public void setIeeCompleta(Integer ieeCompleta) {
		this.ieeCompleta = ieeCompleta;
	}

	@Column(name = "altura_sobre_rasante", precision = 20, scale = 10)
	public BigDecimal getAlturaSobreRasante() {
		return this.alturaSobreRasante;
	}

	public void setAlturaSobreRasante(BigDecimal alturaSobreRasante) {
		this.alturaSobreRasante = alturaSobreRasante;
	}

	@Column(name = "ano_construccion")
	public Integer getAnoConstruccion() {
		return this.anoConstruccion;
	}

	public void setAnoConstruccion(Integer anoConstruccion) {
		this.anoConstruccion = anoConstruccion;
	}

	@Column(name = "ano_construccion_referencia")
	public String getAnoConstruccionReferencia() {
		return this.anoConstruccionReferencia;
	}

	public void setAnoConstruccionReferencia(String anoConstruccionReferencia) {
		this.anoConstruccionReferencia = anoConstruccionReferencia;
	}

	@Column(name = "ano_rehabilitacion")
	public Integer getAnoRehabilitacion() {
		return this.anoRehabilitacion;
	}

	public void setAnoRehabilitacion(Integer anoRehabilitacion) {
		this.anoRehabilitacion = anoRehabilitacion;
	}

	@Column(name = "ano_rehabilitacion_referencia")
	public String getAnoRehabilitacionReferencia() {
		return this.anoRehabilitacionReferencia;
	}

	public void setAnoRehabilitacionReferencia(String anoRehabilitacionReferencia) {
		this.anoRehabilitacionReferencia = anoRehabilitacionReferencia;
	}

	/**
	 * * (inspeccion_datosedificio_nucleosescaleras_tipo_id)
	 */

	@Column(name = "insp_dat_edi_nucl_escal_tip_id")
	public Integer getInspeccionDatosedificioNucleosescalerasTipoId() {
		return this.inspeccionDatosedificioNucleosescalerasTipoId;
	}

	public void setInspeccionDatosedificioNucleosescalerasTipoId(Integer inspeccionDatosedificioNucleosescalerasTipoId) {
		this.inspeccionDatosedificioNucleosescalerasTipoId = inspeccionDatosedificioNucleosescalerasTipoId;
	}

	/**
	 * * (inspeccion_datosedificio_parcela_tipo_id)
	 */

	@Column(name = "insp_dat_edi_parcela_tipo_id")
	public Integer getInspeccionDatosedificioParcelaTipoId() {
		return this.inspeccionDatosedificioParcelaTipoId;
	}

	public void setInspeccionDatosedificioParcelaTipoId(Integer inspeccionDatosedificioParcelaTipoId) {
		this.inspeccionDatosedificioParcelaTipoId = inspeccionDatosedificioParcelaTipoId;
	}

	/**
	 * * (inspeccion_datosedificio_unnucleoescaleras_tipo_id)
	 */

	@Column(name = "insp_dat_edi_un_nuc_esc_tip_id")
	public Integer getInspeccionDatosedificioUnnucleoescalerasTipoId() {
		return this.inspeccionDatosedificioUnnucleoescalerasTipoId;
	}

	public void setInspeccionDatosedificioUnnucleoescalerasTipoId(Integer inspeccionDatosedificioUnnucleoescalerasTipoId) {
		this.inspeccionDatosedificioUnnucleoescalerasTipoId = inspeccionDatosedificioUnnucleoescalerasTipoId;
	}

	/**
	 * * (inspeccion_datosedificio_uso_tipo_id)
	 */

	@Column(name = "insp_dat_edi_uso_tipo_id")
	public Integer getInspeccionDatosedificioUsoTipoId() {
		return this.inspeccionDatosedificioUsoTipoId;
	}

	public void setInspeccionDatosedificioUsoTipoId(Integer inspeccionDatosedificioUsoTipoId) {
		this.inspeccionDatosedificioUsoTipoId = inspeccionDatosedificioUsoTipoId;
	}

	@Column(name = "media_viviendas_por_planta")
	public Integer getMediaViviendasPorPlanta() {
		return this.mediaViviendasPorPlanta;
	}

	public void setMediaViviendasPorPlanta(Integer mediaViviendasPorPlanta) {
		this.mediaViviendasPorPlanta = mediaViviendasPorPlanta;
	}

	@Column(name = "num_aparcamientos")
	public Integer getNumAparcamientos() {
		return this.numAparcamientos;
	}

	public void setNumAparcamientos(Integer numAparcamientos) {
		this.numAparcamientos = numAparcamientos;
	}

	@Column(name = "num_locales")
	public Integer getNumLocales() {
		return this.numLocales;
	}

	public void setNumLocales(Integer numLocales) {
		this.numLocales = numLocales;
	}

	@Column(name = "num_trasteros")
	public Integer getNumTrasteros() {
		return this.numTrasteros;
	}

	public void setNumTrasteros(Integer numTrasteros) {
		this.numTrasteros = numTrasteros;
	}

	@Column(name = "num_viviendas")
	public Integer getNumViviendas() {
		return this.numViviendas;
	}

	public void setNumViviendas(Integer numViviendas) {
		this.numViviendas = numViviendas;
	}

	/**
	 * * (plantas_bajo_rasante_uso_principal)
	 */

	@Column(name = "plantas_bajo_rasante_uso_princ")
	public Integer getPlantasBajoRasanteUsoPrincipal() {
		return this.plantasBajoRasanteUsoPrincipal;
	}

	public void setPlantasBajoRasanteUsoPrincipal(Integer plantasBajoRasanteUsoPrincipal) {
		this.plantasBajoRasanteUsoPrincipal = plantasBajoRasanteUsoPrincipal;
	}

	/**
	 * * (plantas_bajo_rasante_usos_secundarios)
	 */

	@Column(name = "plantas_bajo_rasante_uso_secun")
	public Integer getPlantasBajoRasanteUsosSecundarios() {
		return this.plantasBajoRasanteUsosSecundarios;
	}

	public void setPlantasBajoRasanteUsosSecundarios(Integer plantasBajoRasanteUsosSecundarios) {
		this.plantasBajoRasanteUsosSecundarios = plantasBajoRasanteUsosSecundarios;
	}

	/**
	 * * (plantas_bajo_rasante_usos_secundarios_tipo)
	 */

	@Column(name = "plantas_bajo_rasan_uso_sec_tip")
	public String getPlantasBajoRasanteUsosSecundariosTipo() {
		return this.plantasBajoRasanteUsosSecundariosTipo;
	}

	public void setPlantasBajoRasanteUsosSecundariosTipo(String plantasBajoRasanteUsosSecundariosTipo) {
		this.plantasBajoRasanteUsosSecundariosTipo = plantasBajoRasanteUsosSecundariosTipo;
	}

	/**
	 * * (plantas_sobre_rasante_uso_principal)
	 */

	@Column(name = "plantas_sobre_rasan_uso_princi")
	public Integer getPlantasSobreRasanteUsoPrincipal() {
		return this.plantasSobreRasanteUsoPrincipal;
	}

	public void setPlantasSobreRasanteUsoPrincipal(Integer plantasSobreRasanteUsoPrincipal) {
		this.plantasSobreRasanteUsoPrincipal = plantasSobreRasanteUsoPrincipal;
	}

	/**
	 * * (plantas_sobre_rasante_usos_secundarios)
	 */

	@Column(name = "plantas_sobre_rasan_uso_secun")
	public Integer getPlantasSobreRasanteUsosSecundarios() {
		return this.plantasSobreRasanteUsosSecundarios;
	}

	public void setPlantasSobreRasanteUsosSecundarios(Integer plantasSobreRasanteUsosSecundarios) {
		this.plantasSobreRasanteUsosSecundarios = plantasSobreRasanteUsosSecundarios;
	}

	/**
	 * * (plantas_sobre_rasante_usos_secundarios_tipo)
	 */

	@Column(name = "plantas_sobre_ras_uso_sec_tip")
	public String getPlantasSobreRasanteUsosSecundariosTipo() {
		return this.plantasSobreRasanteUsosSecundariosTipo;
	}

	public void setPlantasSobreRasanteUsosSecundariosTipo(String plantasSobreRasanteUsosSecundariosTipo) {
		this.plantasSobreRasanteUsosSecundariosTipo = plantasSobreRasanteUsosSecundariosTipo;
	}

	@Column(name = "superficie_construida", precision = 20, scale = 10)
	public BigDecimal getSuperficieConstruida() {
		return this.superficieConstruida;
	}

	public void setSuperficieConstruida(BigDecimal superficieConstruida) {
		this.superficieConstruida = superficieConstruida;
	}

	@Column(name = "superficie_media_aparcamientos", precision = 20, scale = 10)
	public BigDecimal getSuperficieMediaAparcamientos() {
		return this.superficieMediaAparcamientos;
	}

	public void setSuperficieMediaAparcamientos(BigDecimal superficieMediaAparcamientos) {
		this.superficieMediaAparcamientos = superficieMediaAparcamientos;
	}

	@Column(name = "superficie_media_locales", precision = 20, scale = 10)
	public BigDecimal getSuperficieMediaLocales() {
		return this.superficieMediaLocales;
	}

	public void setSuperficieMediaLocales(BigDecimal superficieMediaLocales) {
		this.superficieMediaLocales = superficieMediaLocales;
	}

	@Column(name = "superficie_media_trasteros", precision = 20, scale = 10)
	public BigDecimal getSuperficieMediaTrasteros() {
		return this.superficieMediaTrasteros;
	}

	public void setSuperficieMediaTrasteros(BigDecimal superficieMediaTrasteros) {
		this.superficieMediaTrasteros = superficieMediaTrasteros;
	}

	@Column(name = "superficie_media_viviendas", precision = 20, scale = 10)
	public BigDecimal getSuperficieMediaViviendas() {
		return this.superficieMediaViviendas;
	}

	public void setSuperficieMediaViviendas(BigDecimal superficieMediaViviendas) {
		this.superficieMediaViviendas = superficieMediaViviendas;
	}

	@Column(name = "superficie_parcela", precision = 20, scale = 10)
	public BigDecimal getSuperficieParcela() {
		return this.superficieParcela;
	}

	public void setSuperficieParcela(BigDecimal superficieParcela) {
		this.superficieParcela = superficieParcela;
	}

	@Column(name = "total_ascensores")
	public String getTotalAscensores() {
		return this.totalAscensores;
	}

	public void setTotalAscensores(String totalAscensores) {
		this.totalAscensores = totalAscensores;
	}

	@Column(name = "total_escaleras")
	public String getTotalEscaleras() {
		return this.totalEscaleras;
	}

	public void setTotalEscaleras(String totalEscaleras) {
		this.totalEscaleras = totalEscaleras;
	}

	/**
	 * * (total_viviendas_con_acceso_varios_nucleos)
	 */

	@Column(name = "total_viv_con_acceso_vari_nucl")
	public String getTotalViviendasConAccesoVariosNucleos() {
		return this.totalViviendasConAccesoVariosNucleos;
	}

	public void setTotalViviendasConAccesoVariosNucleos(String totalViviendasConAccesoVariosNucleos) {
		this.totalViviendasConAccesoVariosNucleos = totalViviendasConAccesoVariosNucleos;
	}

	/**
	 * * (total_viviendas_sin_acceso_ascensor)
	 */

	@Column(name = "total_viv_sin_acceso_ascensor")
	public String getTotalViviendasSinAccesoAscensor() {
		return this.totalViviendasSinAccesoAscensor;
	}

	public void setTotalViviendasSinAccesoAscensor(String totalViviendasSinAccesoAscensor) {
		this.totalViviendasSinAccesoAscensor = totalViviendasSinAccesoAscensor;
	}

	@Column(name = "uso_texto")
	public String getUsoTexto() {
		return this.usoTexto;
	}

	public void setUsoTexto(String usoTexto) {
		this.usoTexto = usoTexto;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "tipo_via")
	public String getTipoVia() {
		return this.tipoVia;
	}

	public void setTipoVia(String tipoVia) {
		this.tipoVia = tipoVia;
	}

	@Column(name = "via")
	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	@Column(name = "principal")
	public Boolean getPrincipal() {
		return this.principal;
	}

	public void setPrincipal(Boolean principal) {
		this.principal = principal;
	}

	@Column(name = "referencia_catastral")
	public String getReferenciaCatastral() {
		return this.referenciaCatastral;
	}

	public void setReferenciaCatastral(String referenciaCatastral) {
		this.referenciaCatastral = referenciaCatastral;
	}

	@Column(name = "edificio_codigo_postal")
	public String getEdificioCodigoPostal() {
		return this.edificioCodigoPostal;
	}

	public void setEdificioCodigoPostal(String edificioCodigoPostal) {
		this.edificioCodigoPostal = edificioCodigoPostal;
	}

	@Column(name = "edificio_comun_texto")
	public String getEdificioComunTexto() {
		return this.edificioComunTexto;
	}

	public void setEdificioComunTexto(String edificioComunTexto) {
		this.edificioComunTexto = edificioComunTexto;
	}

	/**
	 * * (edificio_inspeccion_identificacionedificio_comunes_tipo_id)
	 */

	@Column(name = "edi_insp_id_edi_comunes_tip_id")
	public Integer getEdificioInspeccionIdentificacionedificioComunesTipoId() {
		return this.edificioInspeccionIdentificacionedificioComunesTipoId;
	}

	public void setEdificioInspeccionIdentificacionedificioComunesTipoId(Integer edificioInspeccionIdentificacionedificioComunesTipoId) {
		this.edificioInspeccionIdentificacionedificioComunesTipoId = edificioInspeccionIdentificacionedificioComunesTipoId;
	}

	/**
	 * * (edificio_inspeccion_identificacionedificio_objeto_tipo_id)
	 */

	@Column(name = "edi_insp_id_edi_objeto_tipo_id")
	public Integer getEdificioInspeccionIdentificacionedificioObjetoTipoId() {
		return this.edificioInspeccionIdentificacionedificioObjetoTipoId;
	}

	public void setEdificioInspeccionIdentificacionedificioObjetoTipoId(Integer edificioInspeccionIdentificacionedificioObjetoTipoId) {
		this.edificioInspeccionIdentificacionedificioObjetoTipoId = edificioInspeccionIdentificacionedificioObjetoTipoId;
	}

	/**
	 * * (edificio_inspeccion_propiedad_regimen_tipo_id)
	 */

	@Column(name = "edi_insp_propied_regim_tip_id")
	public Integer getEdificioInspeccionPropiedadRegimenTipoId() {
		return this.edificioInspeccionPropiedadRegimenTipoId;
	}

	public void setEdificioInspeccionPropiedadRegimenTipoId(Integer edificioInspeccionPropiedadRegimenTipoId) {
		this.edificioInspeccionPropiedadRegimenTipoId = edificioInspeccionPropiedadRegimenTipoId;
	}

	@Column(name = "edificio_numero_manual")
	public String getEdificioNumeroManual() {
		return this.edificioNumeroManual;
	}

	public void setEdificioNumeroManual(String edificioNumeroManual) {
		this.edificioNumeroManual = edificioNumeroManual;
	}

	@Column(name = "edificio_objeto_texto")
	public String getEdificioObjetoTexto() {
		return this.edificioObjetoTexto;
	}

	public void setEdificioObjetoTexto(String edificioObjetoTexto) {
		this.edificioObjetoTexto = edificioObjetoTexto;
	}

	@Column(name = "edificio_observaciones")
	public String getEdificioObservaciones() {
		return this.edificioObservaciones;
	}

	public void setEdificioObservaciones(String edificioObservaciones) {
		this.edificioObservaciones = edificioObservaciones;
	}

	@Column(name = "edificio_piso_letra")
	public String getEdificioPisoLetra() {
		return this.edificioPisoLetra;
	}

	public void setEdificioPisoLetra(String edificioPisoLetra) {
		this.edificioPisoLetra = edificioPisoLetra;
	}

	@Column(name = "edificio_poblacion")
	public String getEdificioPoblacion() {
		return this.edificioPoblacion;
	}

	public void setEdificioPoblacion(String edificioPoblacion) {
		this.edificioPoblacion = edificioPoblacion;
	}

	@Column(name = "edificio_provincia")
	public String getEdificioProvincia() {
		return this.edificioProvincia;
	}

	public void setEdificioProvincia(String edificioProvincia) {
		this.edificioProvincia = edificioProvincia;
	}

	@Column(name = "edificio_provincia_id")
	public Integer getEdificioProvinciaId() {
		return this.edificioProvinciaId;
	}

	public void setEdificioProvinciaId(Integer edificioProvinciaId) {
		this.edificioProvinciaId = edificioProvinciaId;
	}

	@Column(name = "edificio_regimen_texto")
	public String getEdificioRegimenTexto() {
		return this.edificioRegimenTexto;
	}

	public void setEdificioRegimenTexto(String edificioRegimenTexto) {
		this.edificioRegimenTexto = edificioRegimenTexto;
	}

	@Column(name = "edificio_tipo_via_manual")
	public String getEdificioTipoViaManual() {
		return this.edificioTipoViaManual;
	}

	public void setEdificioTipoViaManual(String edificioTipoViaManual) {
		this.edificioTipoViaManual = edificioTipoViaManual;
	}

	@Column(name = "edificio_via_manual")
	public String getEdificioViaManual() {
		return this.edificioViaManual;
	}

	public void setEdificioViaManual(String edificioViaManual) {
		this.edificioViaManual = edificioViaManual;
	}

	@Column(name = "propiedad_nif")
	public String getPropiedadNif() {
		return this.propiedadNif;
	}

	public void setPropiedadNif(String propiedadNif) {
		this.propiedadNif = propiedadNif;
	}

	@Column(name = "propiedad_titular")
	public String getPropiedadTitular() {
		return this.propiedadTitular;
	}

	public void setPropiedadTitular(String propiedadTitular) {
		this.propiedadTitular = propiedadTitular;
	}

	@Column(name = "representante_codigo_postal")
	public String getRepresentanteCodigoPostal() {
		return this.representanteCodigoPostal;
	}

	public void setRepresentanteCodigoPostal(String representanteCodigoPostal) {
		this.representanteCodigoPostal = representanteCodigoPostal;
	}

	@Column(name = "representante_condicion")
	public String getRepresentanteCondicion() {
		return this.representanteCondicion;
	}

	public void setRepresentanteCondicion(String representanteCondicion) {
		this.representanteCondicion = representanteCondicion;
	}

	@Column(name = "representante_direccion")
	public String getRepresentanteDireccion() {
		return this.representanteDireccion;
	}

	public void setRepresentanteDireccion(String representanteDireccion) {
		this.representanteDireccion = representanteDireccion;
	}

	@Column(name = "representante_email")
	public String getRepresentanteEmail() {
		return this.representanteEmail;
	}

	public void setRepresentanteEmail(String representanteEmail) {
		this.representanteEmail = representanteEmail;
	}

	@Column(name = "representante_nif")
	public String getRepresentanteNif() {
		return this.representanteNif;
	}

	public void setRepresentanteNif(String representanteNif) {
		this.representanteNif = representanteNif;
	}

	@Column(name = "representante_nombre")
	public String getRepresentanteNombre() {
		return this.representanteNombre;
	}

	public void setRepresentanteNombre(String representanteNombre) {
		this.representanteNombre = representanteNombre;
	}

	@Column(name = "representante_poblacion")
	public String getRepresentantePoblacion() {
		return this.representantePoblacion;
	}

	public void setRepresentantePoblacion(String representantePoblacion) {
		this.representantePoblacion = representantePoblacion;
	}

	@Column(name = "representante_provincia")
	public String getRepresentanteProvincia() {
		return this.representanteProvincia;
	}

	public void setRepresentanteProvincia(String representanteProvincia) {
		this.representanteProvincia = representanteProvincia;
	}

	@Column(name = "representante_telefono_fijo")
	public String getRepresentanteTelefonoFijo() {
		return this.representanteTelefonoFijo;
	}

	public void setRepresentanteTelefonoFijo(String representanteTelefonoFijo) {
		this.representanteTelefonoFijo = representanteTelefonoFijo;
	}

	@Column(name = "representante_telefono_movil")
	public String getRepresentanteTelefonoMovil() {
		return this.representanteTelefonoMovil;
	}

	public void setRepresentanteTelefonoMovil(String representanteTelefonoMovil) {
		this.representanteTelefonoMovil = representanteTelefonoMovil;
	}

	@Column(name = "tecnico_nif")
	public String getTecnicoNif() {
		return this.tecnicoNif;
	}

	public void setTecnicoNif(String tecnicoNif) {
		this.tecnicoNif = tecnicoNif;
	}

	@Column(name = "tecnico_tecnico")
	public String getTecnicoTecnico() {
		return this.tecnicoTecnico;
	}

	public void setTecnicoTecnico(String tecnicoTecnico) {
		this.tecnicoTecnico = tecnicoTecnico;
	}

	@Column(name = "tecnico_titulacion")
	public String getTecnicoTitulacion() {
		return this.tecnicoTitulacion;
	}

	public void setTecnicoTitulacion(String tecnicoTitulacion) {
		this.tecnicoTitulacion = tecnicoTitulacion;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AccesibilidadPublicos getAccesibilidadPublicos() {
		return this.accesibilidadPublicos;
	}

	public void setAccesibilidadPublicos(AccesibilidadPublicos accesibilidadPublicos) {
		this.accesibilidadPublicos = accesibilidadPublicos;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaRuidosInterioresUniones getAcusticaRuidosInterioresUniones() {
		return this.acusticaRuidosInterioresUniones;
	}

	public void setAcusticaRuidosInterioresUniones(AcusticaRuidosInterioresUniones acusticaRuidosInterioresUniones) {
		this.acusticaRuidosInterioresUniones = acusticaRuidosInterioresUniones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspeccion")
	public Set<FechaVisita> getFechasVisitas() {
		return this.fechasVisitas;
	}

	public void setFechasVisitas(Set<FechaVisita> fechasVisitas) {
		this.fechasVisitas = fechasVisitas;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaValoracionFinal getAcusticaValoracionFinal() {
		return this.acusticaValoracionFinal;
	}

	public void setAcusticaValoracionFinal(AcusticaValoracionFinal acusticaValoracionFinal) {
		this.acusticaValoracionFinal = acusticaValoracionFinal;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaRuidosInterioresVerticales getAcusticaRuidosInterioresVerticales() {
		return this.acusticaRuidosInterioresVerticales;
	}

	public void setAcusticaRuidosInterioresVerticales(AcusticaRuidosInterioresVerticales acusticaRuidosInterioresVerticales) {
		this.acusticaRuidosInterioresVerticales = acusticaRuidosInterioresVerticales;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaComprobaciones getAcusticaComprobaciones() {
		return this.acusticaComprobaciones;
	}

	public void setAcusticaComprobaciones(AcusticaComprobaciones acusticaComprobaciones) {
		this.acusticaComprobaciones = acusticaComprobaciones;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public Instalaciones getInstalaciones() {
		return this.instalaciones;
	}

	public void setInstalaciones(Instalaciones instalaciones) {
		this.instalaciones = instalaciones;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public CerramientosCubiertas getCerramientosCubiertas() {
		return this.cerramientosCubiertas;
	}

	public void setCerramientosCubiertas(CerramientosCubiertas cerramientosCubiertas) {
		this.cerramientosCubiertas = cerramientosCubiertas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspeccion")
	public Set<ValoracionParcial> getValoracionesParciales() {
		return this.valoracionesParciales;
	}

	public void setValoracionesParciales(Set<ValoracionParcial> valoracionesParciales) {
		this.valoracionesParciales = valoracionesParciales;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AccesibilidadValoracionFinales getAccesibilidadValoracionFinales() {
		return this.accesibilidadValoracionFinales;
	}

	public void setAccesibilidadValoracionFinales(AccesibilidadValoracionFinales accesibilidadValoracionFinales) {
		this.accesibilidadValoracionFinales = accesibilidadValoracionFinales;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaRuidoInstalaciones getAcusticaRuidoInstalaciones() {
		return this.acusticaRuidoInstalaciones;
	}

	public void setAcusticaRuidoInstalaciones(AcusticaRuidoInstalaciones acusticaRuidoInstalaciones) {
		this.acusticaRuidoInstalaciones = acusticaRuidoInstalaciones;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public Estructura getEstructura() {
		return this.estructura;
	}

	public void setEstructura(Estructura estructura) {
		this.estructura = estructura;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public Cimentaciones getCimentaciones() {
		return this.cimentaciones;
	}

	public void setCimentaciones(Cimentaciones cimentaciones) {
		this.cimentaciones = cimentaciones;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AccesibilidadAjustesRazonables getAccesibilidadAjustesRazonables() {
		return this.accesibilidadAjustesRazonables;
	}

	public void setAccesibilidadAjustesRazonables(AccesibilidadAjustesRazonables accesibilidadAjustesRazonables) {
		this.accesibilidadAjustesRazonables = accesibilidadAjustesRazonables;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public EficienciasEnergeticas getEficienciasEnergeticas() {
		return this.eficienciasEnergeticas;
	}

	public void setEficienciasEnergeticas(EficienciasEnergeticas eficienciasEnergeticas) {
		this.eficienciasEnergeticas = eficienciasEnergeticas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspeccion")
	public Set<DocumentacionOtro> getDocumentacionOtros() {
		return this.documentacionOtros;
	}

	public void setDocumentacionOtros(Set<DocumentacionOtro> documentacionOtros) {
		this.documentacionOtros = documentacionOtros;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaRuidosExteriores getAcusticaRuidosExteriores() {
		return this.acusticaRuidosExteriores;
	}

	public void setAcusticaRuidosExteriores(AcusticaRuidosExteriores acusticaRuidosExteriores) {
		this.acusticaRuidosExteriores = acusticaRuidosExteriores;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="inspeccion")
    public Set<AcusticaMejorasAcusticas> getAcusticaMejorasAcusticas() {
        return this.acusticaMejorasAcusticas;
    }
    
    public void setAcusticaMejorasAcusticas(Set<AcusticaMejorasAcusticas> acusticaMejorasAcusticas) {
        this.acusticaMejorasAcusticas = acusticaMejorasAcusticas;
    }

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaRuidosInterioresHorizontales getAcusticaRuidosInterioresHorizontales() {
		return this.acusticaRuidosInterioresHorizontales;
	}

	public void setAcusticaRuidosInterioresHorizontales(AcusticaRuidosInterioresHorizontales acusticaRuidosInterioresHorizontales) {
		this.acusticaRuidosInterioresHorizontales = acusticaRuidosInterioresHorizontales;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public AcusticaDatosGenerales getAcusticaDatosGenerales() {
		return this.acusticaDatosGenerales;
	}

	public void setAcusticaDatosGenerales(AcusticaDatosGenerales acusticaDatosGenerales) {
		this.acusticaDatosGenerales = acusticaDatosGenerales;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public Acusticas getAcusticas() {
		return this.acusticas;
	}

	public void setAcusticas(Acusticas acusticas) {
		this.acusticas = acusticas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspeccion")
	public Set<Deficiencia> getDeficiencias() {
		return this.deficiencias;
	}

	public void setDeficiencias(Set<Deficiencia> deficiencias) {
		this.deficiencias = deficiencias;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "aed_ins_val", joinColumns = { @JoinColumn(name = "clave_informe", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "caracteristica", nullable = false, updatable = false), @JoinColumn(name = "id_valor", nullable = false, updatable = false) })
    @OrderBy("caracteristica ASC")
	public Set<Valor> getValores() {
		return this.valores;
	}

	public void setValores(Set<Valor> valores) {
		this.valores = valores;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true)
	public Conservacion getConservacion() {
		return this.conservacion;
	}

	public void setConservacion(Conservacion conservacion) {
		this.conservacion = conservacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inspeccion")
	public Set<Historico> getHistoricos() {
		return this.historicos;
	}

	public void setHistoricos(Set<Historico> historicos) {
		this.historicos = historicos;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("accesibilidadPublicos").append("='").append(getAccesibilidadPublicos()).append("' ");
		buffer.append("acusticaRuidosInterioresUniones").append("='").append(getAcusticaRuidosInterioresUniones()).append("' ");
		buffer.append("acusticaValoracionFinal").append("='").append(getAcusticaValoracionFinal()).append("' ");
		buffer.append("acusticaRuidosInterioresVerticales").append("='").append(getAcusticaRuidosInterioresVerticales()).append("' ");
		buffer.append("acusticaComprobaciones").append("='").append(getAcusticaComprobaciones()).append("' ");
		buffer.append("instalaciones").append("='").append(getInstalaciones()).append("' ");
		buffer.append("cerramientosCubiertas").append("='").append(getCerramientosCubiertas()).append("' ");
		buffer.append("accesibilidadValoracionFinales").append("='").append(getAccesibilidadValoracionFinales()).append("' ");
		buffer.append("acusticaRuidoInstalaciones").append("='").append(getAcusticaRuidoInstalaciones()).append("' ");
		buffer.append("estructura").append("='").append(getEstructura()).append("' ");
		buffer.append("cimentaciones").append("='").append(getCimentaciones()).append("' ");
		buffer.append("accesibilidadAjustesRazonables").append("='").append(getAccesibilidadAjustesRazonables()).append("' ");
		buffer.append("eficienciasEnergeticas").append("='").append(getEficienciasEnergeticas()).append("' ");
		buffer.append("acusticaRuidosExteriores").append("='").append(getAcusticaRuidosExteriores()).append("' ");
		buffer.append("acusticaRuidosInterioresHorizontales").append("='").append(getAcusticaRuidosInterioresHorizontales()).append("' ");
		buffer.append("acusticaDatosGenerales").append("='").append(getAcusticaDatosGenerales()).append("' ");
		buffer.append("acusticas").append("='").append(getAcusticas()).append("' ");
		buffer.append("conservacion").append("='").append(getConservacion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Inspeccion))
			return false;
		Inspeccion castOther = (Inspeccion) other;

		return (this.getId() == castOther.getId()) && ((this.getAccesibilidadPublicos() == castOther.getAccesibilidadPublicos()) || (this.getAccesibilidadPublicos() != null && castOther.getAccesibilidadPublicos() != null && this.getAccesibilidadPublicos().equals(castOther.getAccesibilidadPublicos()))) && ((this.getAcusticaRuidosInterioresUniones() == castOther.getAcusticaRuidosInterioresUniones()) || (this.getAcusticaRuidosInterioresUniones() != null && castOther.getAcusticaRuidosInterioresUniones() != null && this.getAcusticaRuidosInterioresUniones().equals(castOther.getAcusticaRuidosInterioresUniones()))) && ((this.getAcusticaValoracionFinal() == castOther.getAcusticaValoracionFinal()) || (this.getAcusticaValoracionFinal() != null && castOther.getAcusticaValoracionFinal() != null && this.getAcusticaValoracionFinal().equals(castOther.getAcusticaValoracionFinal()))) && ((this.getAcusticaRuidosInterioresVerticales() == castOther.getAcusticaRuidosInterioresVerticales()) || (this.getAcusticaRuidosInterioresVerticales() != null && castOther.getAcusticaRuidosInterioresVerticales() != null && this.getAcusticaRuidosInterioresVerticales().equals(castOther.getAcusticaRuidosInterioresVerticales()))) && ((this.getAcusticaComprobaciones() == castOther.getAcusticaComprobaciones()) || (this.getAcusticaComprobaciones() != null && castOther.getAcusticaComprobaciones() != null && this.getAcusticaComprobaciones().equals(castOther.getAcusticaComprobaciones()))) && ((this.getInstalaciones() == castOther.getInstalaciones()) || (this.getInstalaciones() != null && castOther.getInstalaciones() != null && this.getInstalaciones().equals(castOther.getInstalaciones()))) && ((this.getCerramientosCubiertas() == castOther.getCerramientosCubiertas()) || (this.getCerramientosCubiertas() != null && castOther.getCerramientosCubiertas() != null && this.getCerramientosCubiertas().equals(castOther.getCerramientosCubiertas()))) && ((this.getAccesibilidadValoracionFinales() == castOther.getAccesibilidadValoracionFinales()) || (this.getAccesibilidadValoracionFinales() != null && castOther.getAccesibilidadValoracionFinales() != null && this.getAccesibilidadValoracionFinales().equals(castOther.getAccesibilidadValoracionFinales()))) && ((this.getAcusticaRuidoInstalaciones() == castOther.getAcusticaRuidoInstalaciones()) || (this.getAcusticaRuidoInstalaciones() != null && castOther.getAcusticaRuidoInstalaciones() != null && this.getAcusticaRuidoInstalaciones().equals(castOther.getAcusticaRuidoInstalaciones()))) && ((this.getEstructura() == castOther.getEstructura()) || (this.getEstructura() != null && castOther.getEstructura() != null && this.getEstructura().equals(castOther.getEstructura()))) && ((this.getCimentaciones() == castOther.getCimentaciones()) || (this.getCimentaciones() != null && castOther.getCimentaciones() != null && this.getCimentaciones().equals(castOther.getCimentaciones()))) && ((this.getAccesibilidadAjustesRazonables() == castOther.getAccesibilidadAjustesRazonables()) || (this.getAccesibilidadAjustesRazonables() != null && castOther.getAccesibilidadAjustesRazonables() != null && this.getAccesibilidadAjustesRazonables().equals(castOther.getAccesibilidadAjustesRazonables()))) && ((this.getEficienciasEnergeticas() == castOther.getEficienciasEnergeticas()) || (this.getEficienciasEnergeticas() != null && castOther.getEficienciasEnergeticas() != null && this.getEficienciasEnergeticas().equals(castOther.getEficienciasEnergeticas()))) && ((this.getAcusticaRuidosExteriores() == castOther.getAcusticaRuidosExteriores()) || (this.getAcusticaRuidosExteriores() != null && castOther.getAcusticaRuidosExteriores() != null && this.getAcusticaRuidosExteriores().equals(castOther.getAcusticaRuidosExteriores()))) && ((this.getAcusticaRuidosInterioresHorizontales() == castOther.getAcusticaRuidosInterioresHorizontales()) || (this.getAcusticaRuidosInterioresHorizontales() != null && castOther.getAcusticaRuidosInterioresHorizontales() != null && this.getAcusticaRuidosInterioresHorizontales().equals(castOther.getAcusticaRuidosInterioresHorizontales()))) && ((this.getAcusticaDatosGenerales() == castOther.getAcusticaDatosGenerales()) || (this.getAcusticaDatosGenerales() != null && castOther.getAcusticaDatosGenerales() != null && this.getAcusticaDatosGenerales().equals(castOther.getAcusticaDatosGenerales()))) && ((this.getAcusticas() == castOther.getAcusticas()) || (this.getAcusticas() != null && castOther.getAcusticas() != null && this.getAcusticas().equals(castOther.getAcusticas()))) && ((this.getConservacion() == castOther.getConservacion()) || (this.getConservacion() != null && castOther.getConservacion() != null && this.getConservacion().equals(castOther.getConservacion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();

		result = 37 * result + (getAccesibilidadPublicos() == null ? 0 : this.getAccesibilidadPublicos().hashCode());
		result = 37 * result + (getAcusticaRuidosInterioresUniones() == null ? 0 : this.getAcusticaRuidosInterioresUniones().hashCode());

		result = 37 * result + (getAcusticaValoracionFinal() == null ? 0 : this.getAcusticaValoracionFinal().hashCode());
		result = 37 * result + (getAcusticaRuidosInterioresVerticales() == null ? 0 : this.getAcusticaRuidosInterioresVerticales().hashCode());
		result = 37 * result + (getAcusticaComprobaciones() == null ? 0 : this.getAcusticaComprobaciones().hashCode());
		result = 37 * result + (getInstalaciones() == null ? 0 : this.getInstalaciones().hashCode());
		result = 37 * result + (getCerramientosCubiertas() == null ? 0 : this.getCerramientosCubiertas().hashCode());

		result = 37 * result + (getAccesibilidadValoracionFinales() == null ? 0 : this.getAccesibilidadValoracionFinales().hashCode());
		result = 37 * result + (getAcusticaRuidoInstalaciones() == null ? 0 : this.getAcusticaRuidoInstalaciones().hashCode());
		result = 37 * result + (getEstructura() == null ? 0 : this.getEstructura().hashCode());
		result = 37 * result + (getCimentaciones() == null ? 0 : this.getCimentaciones().hashCode());
		result = 37 * result + (getAccesibilidadAjustesRazonables() == null ? 0 : this.getAccesibilidadAjustesRazonables().hashCode());
		result = 37 * result + (getEficienciasEnergeticas() == null ? 0 : this.getEficienciasEnergeticas().hashCode());

		result = 37 * result + (getAcusticaRuidosExteriores() == null ? 0 : this.getAcusticaRuidosExteriores().hashCode());
		result = 37 * result + (getAcusticaRuidosInterioresHorizontales() == null ? 0 : this.getAcusticaRuidosInterioresHorizontales().hashCode());
		result = 37 * result + (getAcusticaDatosGenerales() == null ? 0 : this.getAcusticaDatosGenerales().hashCode());
		result = 37 * result + (getAcusticas() == null ? 0 : this.getAcusticas().hashCode());

		result = 37 * result + (getConservacion() == null ? 0 : this.getConservacion().hashCode());

		return result;
	}

}
