package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Instalaciones generated by hbm2java
 */
@Entity
@Table(name = "aed_instalaciones")
public class Instalaciones extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int claveInforme;
	private Inspeccion inspeccion;
	private Integer acsCaptadoressolares;
	private String acsCentralCombustibleTexto;
	private Integer acsCentralTiene;
	/**
	 * (acs_nocentral_calentadoreselectricosporcentaje)
	 */
	private String acsNocentralCalentadoreselectricosporcentaje;
	/**
	 * (acs_nocentral_gascanalizadoporcentaje)
	 */
	private String acsNocentralGascanalizadoporcentaje;
	/**
	 * (acs_nocentral_gasembotelladoporcentaje)
	 */
	private String acsNocentralGasembotelladoporcentaje;
	/**
	 * (acs_nocentral_individualporcentaje)
	 */
	private String acsNocentralIndividualporcentaje;
	private String acsNocentralOtrosporcentaje;
	private Integer acsTiene;
	/**
	 * (calefaccion_central_combustible_texto)
	 */
	private String calefaccionCentralCombustibleTexto;
	private String calefaccionCentralTexto;
	private Integer calefaccionCentralTiene;
	/**
	 * (calefaccion_nocentral_calderagasoleoporcentaje)
	 */
	private String calefaccionNocentralCalderagasoleoporcentaje;
	/**
	 * (calefaccion_nocentral_calefaccionelectricaporcentaje)
	 */
	private String calefaccionNocentralCalefaccionelectricaporcentaje;
	/**
	 * (calefaccion_nocentral_gascanalizadoporcentaje)
	 */
	private String calefaccionNocentralGascanalizadoporcentaje;
	/**
	 * (calefaccion_nocentral_individualporcentaje)
	 */
	private String calefaccionNocentralIndividualporcentaje;
	/**
	 * (calefaccion_nocentral_otrosporcentaje)
	 */
	private String calefaccionNocentralOtrosporcentaje;
	private Integer calefaccionTiene;
	private String comunicacionesictTexto;
	private Integer comunicacionesictTiene;
	private Integer contraincendiosTiene;
	private String contrarayoTexto;
	private Integer contrarayoTiene;
	private String electricaTexto;
	private String gascanalizadoPorcentaje;
	private Integer gascanalizadoTiene;
	/**
	 * (instalaciones_acsnocentralgascanalizados)
	 */
	private String instalacionesAcsnocentralgascanalizados;
	/**
	 * (instalaciones_acsnocentralgasembotellados)
	 */
	private String instalacionesAcsnocentralgasembotellados;
	/**
	 * (instalaciones_calefaccionnocentralcalefaccionelectricas)
	 */
	private String instalacionesCalefaccionnocentralcalefaccionelectricas;
	/**
	 * (instalaciones_calefaccionnocentralgascanalizados)
	 */
	private String instalacionesCalefaccionnocentralgascanalizados;
	private String observaciones;
	private Integer refrigeracionColectivoTiene;
	/**
	 * (refrigeracion_nocolectivo_aparatosenfachadas)
	 */
	private String refrigeracionNocolectivoAparatosenfachadas;
	/**
	 * (refrigeracion_nocolectivo_individualporcentaje)
	 */
	private String refrigeracionNocolectivoIndividualporcentaje;
	private Integer refrigeracionTiene;
	private String saneamientoBajantesTexto;
	private String saneamientoColectoresTexto;
	/**
	 * (ventilacion_cuartoshumedos_sinventilacion)
	 */
	private Integer ventilacionCuartoshumedosSinventilacion;
	/**
	 * (ventilacion_cuartoshumedos_texto)
	 */
	private String ventilacionCuartoshumedosTexto;
	private Integer ventilacionTiene;

	public Instalaciones() {
	}

	public Instalaciones(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public Instalaciones(Inspeccion inspeccion, Integer acsCaptadoressolares, String acsCentralCombustibleTexto, Integer acsCentralTiene, String acsNocentralCalentadoreselectricosporcentaje, String acsNocentralGascanalizadoporcentaje, String acsNocentralGasembotelladoporcentaje, String acsNocentralIndividualporcentaje, String acsNocentralOtrosporcentaje, Integer acsTiene, String calefaccionCentralCombustibleTexto, String calefaccionCentralTexto, Integer calefaccionCentralTiene, String calefaccionNocentralCalderagasoleoporcentaje, String calefaccionNocentralCalefaccionelectricaporcentaje, String calefaccionNocentralGascanalizadoporcentaje, String calefaccionNocentralIndividualporcentaje, String calefaccionNocentralOtrosporcentaje, Integer calefaccionTiene, String comunicacionesictTexto, Integer comunicacionesictTiene, Integer contraincendiosTiene, String contrarayoTexto, Integer contrarayoTiene, String electricaTexto, String gascanalizadoPorcentaje, Integer gascanalizadoTiene, String instalacionesAcsnocentralgascanalizados, String instalacionesAcsnocentralgasembotellados, String instalacionesCalefaccionnocentralcalefaccionelectricas, String instalacionesCalefaccionnocentralgascanalizados, String observaciones, Integer refrigeracionColectivoTiene, String refrigeracionNocolectivoAparatosenfachadas, String refrigeracionNocolectivoIndividualporcentaje, Integer refrigeracionTiene, String saneamientoBajantesTexto, String saneamientoColectoresTexto, Integer ventilacionCuartoshumedosSinventilacion, String ventilacionCuartoshumedosTexto, Integer ventilacionTiene) {
		this.inspeccion = inspeccion;
		this.acsCaptadoressolares = acsCaptadoressolares;
		this.acsCentralCombustibleTexto = acsCentralCombustibleTexto;
		this.acsCentralTiene = acsCentralTiene;
		this.acsNocentralCalentadoreselectricosporcentaje = acsNocentralCalentadoreselectricosporcentaje;
		this.acsNocentralGascanalizadoporcentaje = acsNocentralGascanalizadoporcentaje;
		this.acsNocentralGasembotelladoporcentaje = acsNocentralGasembotelladoporcentaje;
		this.acsNocentralIndividualporcentaje = acsNocentralIndividualporcentaje;
		this.acsNocentralOtrosporcentaje = acsNocentralOtrosporcentaje;
		this.acsTiene = acsTiene;
		this.calefaccionCentralCombustibleTexto = calefaccionCentralCombustibleTexto;
		this.calefaccionCentralTexto = calefaccionCentralTexto;
		this.calefaccionCentralTiene = calefaccionCentralTiene;
		this.calefaccionNocentralCalderagasoleoporcentaje = calefaccionNocentralCalderagasoleoporcentaje;
		this.calefaccionNocentralCalefaccionelectricaporcentaje = calefaccionNocentralCalefaccionelectricaporcentaje;
		this.calefaccionNocentralGascanalizadoporcentaje = calefaccionNocentralGascanalizadoporcentaje;
		this.calefaccionNocentralIndividualporcentaje = calefaccionNocentralIndividualporcentaje;
		this.calefaccionNocentralOtrosporcentaje = calefaccionNocentralOtrosporcentaje;
		this.calefaccionTiene = calefaccionTiene;
		this.comunicacionesictTexto = comunicacionesictTexto;
		this.comunicacionesictTiene = comunicacionesictTiene;
		this.contraincendiosTiene = contraincendiosTiene;
		this.contrarayoTexto = contrarayoTexto;
		this.contrarayoTiene = contrarayoTiene;
		this.electricaTexto = electricaTexto;
		this.gascanalizadoPorcentaje = gascanalizadoPorcentaje;
		this.gascanalizadoTiene = gascanalizadoTiene;
		this.instalacionesAcsnocentralgascanalizados = instalacionesAcsnocentralgascanalizados;
		this.instalacionesAcsnocentralgasembotellados = instalacionesAcsnocentralgasembotellados;
		this.instalacionesCalefaccionnocentralcalefaccionelectricas = instalacionesCalefaccionnocentralcalefaccionelectricas;
		this.instalacionesCalefaccionnocentralgascanalizados = instalacionesCalefaccionnocentralgascanalizados;
		this.observaciones = observaciones;
		this.refrigeracionColectivoTiene = refrigeracionColectivoTiene;
		this.refrigeracionNocolectivoAparatosenfachadas = refrigeracionNocolectivoAparatosenfachadas;
		this.refrigeracionNocolectivoIndividualporcentaje = refrigeracionNocolectivoIndividualporcentaje;
		this.refrigeracionTiene = refrigeracionTiene;
		this.saneamientoBajantesTexto = saneamientoBajantesTexto;
		this.saneamientoColectoresTexto = saneamientoColectoresTexto;
		this.ventilacionCuartoshumedosSinventilacion = ventilacionCuartoshumedosSinventilacion;
		this.ventilacionCuartoshumedosTexto = ventilacionCuartoshumedosTexto;
		this.ventilacionTiene = ventilacionTiene;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "inspeccion"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "clave_informe", unique = true, nullable = false)
	public int getClaveInforme() {
		return this.claveInforme;
	}

	public void setClaveInforme(int claveInforme) {
		this.claveInforme = claveInforme;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", unique = true, nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	@Column(name = "acs_captadoressolares")
	public Integer getAcsCaptadoressolares() {
		return this.acsCaptadoressolares;
	}

	public void setAcsCaptadoressolares(Integer acsCaptadoressolares) {
		this.acsCaptadoressolares = acsCaptadoressolares;
	}

	@Column(name = "acs_central_combustible_texto")
	public String getAcsCentralCombustibleTexto() {
		return this.acsCentralCombustibleTexto;
	}

	public void setAcsCentralCombustibleTexto(String acsCentralCombustibleTexto) {
		this.acsCentralCombustibleTexto = acsCentralCombustibleTexto;
	}

	@Column(name = "acs_central_tiene")
	public Integer getAcsCentralTiene() {
		return this.acsCentralTiene;
	}

	public void setAcsCentralTiene(Integer acsCentralTiene) {
		this.acsCentralTiene = acsCentralTiene;
	}

	/**
	 * * (acs_nocentral_calentadoreselectricosporcentaje)
	 */

	@Column(name = "acs_nocentr_calent_elec_porcen")
	public String getAcsNocentralCalentadoreselectricosporcentaje() {
		return this.acsNocentralCalentadoreselectricosporcentaje;
	}

	public void setAcsNocentralCalentadoreselectricosporcentaje(String acsNocentralCalentadoreselectricosporcentaje) {
		this.acsNocentralCalentadoreselectricosporcentaje = acsNocentralCalentadoreselectricosporcentaje;
	}

	/**
	 * * (acs_nocentral_gascanalizadoporcentaje)
	 */

	@Column(name = "acs_nocentr_gas_canal_porcen")
	public String getAcsNocentralGascanalizadoporcentaje() {
		return this.acsNocentralGascanalizadoporcentaje;
	}

	public void setAcsNocentralGascanalizadoporcentaje(String acsNocentralGascanalizadoporcentaje) {
		this.acsNocentralGascanalizadoporcentaje = acsNocentralGascanalizadoporcentaje;
	}

	/**
	 * * (acs_nocentral_gasembotelladoporcentaje)
	 */

	@Column(name = "acs_nocentral_gas_embot_porcen")
	public String getAcsNocentralGasembotelladoporcentaje() {
		return this.acsNocentralGasembotelladoporcentaje;
	}

	public void setAcsNocentralGasembotelladoporcentaje(String acsNocentralGasembotelladoporcentaje) {
		this.acsNocentralGasembotelladoporcentaje = acsNocentralGasembotelladoporcentaje;
	}

	/**
	 * * (acs_nocentral_individualporcentaje)
	 */

	@Column(name = "acs_nocentral_individualporcen")
	public String getAcsNocentralIndividualporcentaje() {
		return this.acsNocentralIndividualporcentaje;
	}

	public void setAcsNocentralIndividualporcentaje(String acsNocentralIndividualporcentaje) {
		this.acsNocentralIndividualporcentaje = acsNocentralIndividualporcentaje;
	}

	@Column(name = "acs_nocentral_otrosporcentaje")
	public String getAcsNocentralOtrosporcentaje() {
		return this.acsNocentralOtrosporcentaje;
	}

	public void setAcsNocentralOtrosporcentaje(String acsNocentralOtrosporcentaje) {
		this.acsNocentralOtrosporcentaje = acsNocentralOtrosporcentaje;
	}

	@Column(name = "acs_tiene")
	public Integer getAcsTiene() {
		return this.acsTiene;
	}

	public void setAcsTiene(Integer acsTiene) {
		this.acsTiene = acsTiene;
	}

	/**
	 * * (calefaccion_central_combustible_texto)
	 */

	@Column(name = "calef_central_combustible_tex")
	public String getCalefaccionCentralCombustibleTexto() {
		return this.calefaccionCentralCombustibleTexto;
	}

	public void setCalefaccionCentralCombustibleTexto(String calefaccionCentralCombustibleTexto) {
		this.calefaccionCentralCombustibleTexto = calefaccionCentralCombustibleTexto;
	}

	@Column(name = "calefaccion_central_texto")
	public String getCalefaccionCentralTexto() {
		return this.calefaccionCentralTexto;
	}

	public void setCalefaccionCentralTexto(String calefaccionCentralTexto) {
		this.calefaccionCentralTexto = calefaccionCentralTexto;
	}

	@Column(name = "calefaccion_central_tiene")
	public Integer getCalefaccionCentralTiene() {
		return this.calefaccionCentralTiene;
	}

	public void setCalefaccionCentralTiene(Integer calefaccionCentralTiene) {
		this.calefaccionCentralTiene = calefaccionCentralTiene;
	}

	/**
	 * * (calefaccion_nocentral_calderagasoleoporcentaje)
	 */

	@Column(name = "calef_nocen_cal_gasoleo_porcen")
	public String getCalefaccionNocentralCalderagasoleoporcentaje() {
		return this.calefaccionNocentralCalderagasoleoporcentaje;
	}

	public void setCalefaccionNocentralCalderagasoleoporcentaje(String calefaccionNocentralCalderagasoleoporcentaje) {
		this.calefaccionNocentralCalderagasoleoporcentaje = calefaccionNocentralCalderagasoleoporcentaje;
	}

	/**
	 * * (calefaccion_nocentral_calefaccionelectricaporcentaje)
	 */

	@Column(name = "calef_nocen_calef_elec_porcen")
	public String getCalefaccionNocentralCalefaccionelectricaporcentaje() {
		return this.calefaccionNocentralCalefaccionelectricaporcentaje;
	}

	public void setCalefaccionNocentralCalefaccionelectricaporcentaje(String calefaccionNocentralCalefaccionelectricaporcentaje) {
		this.calefaccionNocentralCalefaccionelectricaporcentaje = calefaccionNocentralCalefaccionelectricaporcentaje;
	}

	/**
	 * * (calefaccion_nocentral_gascanalizadoporcentaje)
	 */

	@Column(name = "calef_nocen_gas_canal_porcen")
	public String getCalefaccionNocentralGascanalizadoporcentaje() {
		return this.calefaccionNocentralGascanalizadoporcentaje;
	}

	public void setCalefaccionNocentralGascanalizadoporcentaje(String calefaccionNocentralGascanalizadoporcentaje) {
		this.calefaccionNocentralGascanalizadoporcentaje = calefaccionNocentralGascanalizadoporcentaje;
	}

	/**
	 * * (calefaccion_nocentral_individualporcentaje)
	 */

	@Column(name = "calef_nocentral_indivi_porcen")
	public String getCalefaccionNocentralIndividualporcentaje() {
		return this.calefaccionNocentralIndividualporcentaje;
	}

	public void setCalefaccionNocentralIndividualporcentaje(String calefaccionNocentralIndividualporcentaje) {
		this.calefaccionNocentralIndividualporcentaje = calefaccionNocentralIndividualporcentaje;
	}

	/**
	 * * (calefaccion_nocentral_otrosporcentaje)
	 */

	@Column(name = "calef_nocentral_otrosporcen")
	public String getCalefaccionNocentralOtrosporcentaje() {
		return this.calefaccionNocentralOtrosporcentaje;
	}

	public void setCalefaccionNocentralOtrosporcentaje(String calefaccionNocentralOtrosporcentaje) {
		this.calefaccionNocentralOtrosporcentaje = calefaccionNocentralOtrosporcentaje;
	}

	@Column(name = "calefaccion_tiene")
	public Integer getCalefaccionTiene() {
		return this.calefaccionTiene;
	}

	public void setCalefaccionTiene(Integer calefaccionTiene) {
		this.calefaccionTiene = calefaccionTiene;
	}

	@Column(name = "comunicacionesict_texto")
	public String getComunicacionesictTexto() {
		return this.comunicacionesictTexto;
	}

	public void setComunicacionesictTexto(String comunicacionesictTexto) {
		this.comunicacionesictTexto = comunicacionesictTexto;
	}

	@Column(name = "comunicacionesict_tiene")
	public Integer getComunicacionesictTiene() {
		return this.comunicacionesictTiene;
	}

	public void setComunicacionesictTiene(Integer comunicacionesictTiene) {
		this.comunicacionesictTiene = comunicacionesictTiene;
	}

	@Column(name = "contraincendios_tiene")
	public Integer getContraincendiosTiene() {
		return this.contraincendiosTiene;
	}

	public void setContraincendiosTiene(Integer contraincendiosTiene) {
		this.contraincendiosTiene = contraincendiosTiene;
	}

	@Column(name = "contrarayo_texto")
	public String getContrarayoTexto() {
		return this.contrarayoTexto;
	}

	public void setContrarayoTexto(String contrarayoTexto) {
		this.contrarayoTexto = contrarayoTexto;
	}

	@Column(name = "contrarayo_tiene")
	public Integer getContrarayoTiene() {
		return this.contrarayoTiene;
	}

	public void setContrarayoTiene(Integer contrarayoTiene) {
		this.contrarayoTiene = contrarayoTiene;
	}

	@Column(name = "electrica_texto")
	public String getElectricaTexto() {
		return this.electricaTexto;
	}

	public void setElectricaTexto(String electricaTexto) {
		this.electricaTexto = electricaTexto;
	}

	@Column(name = "gascanalizado_porcentaje")
	public String getGascanalizadoPorcentaje() {
		return this.gascanalizadoPorcentaje;
	}

	public void setGascanalizadoPorcentaje(String gascanalizadoPorcentaje) {
		this.gascanalizadoPorcentaje = gascanalizadoPorcentaje;
	}

	@Column(name = "gascanalizado_tiene")
	public Integer getGascanalizadoTiene() {
		return this.gascanalizadoTiene;
	}

	public void setGascanalizadoTiene(Integer gascanalizadoTiene) {
		this.gascanalizadoTiene = gascanalizadoTiene;
	}

	/**
	 * * (instalaciones_acsnocentralgascanalizados)
	 */

	@Column(name = "instal_acs_nocentral_gas_canal")
	public String getInstalacionesAcsnocentralgascanalizados() {
		return this.instalacionesAcsnocentralgascanalizados;
	}

	public void setInstalacionesAcsnocentralgascanalizados(String instalacionesAcsnocentralgascanalizados) {
		this.instalacionesAcsnocentralgascanalizados = instalacionesAcsnocentralgascanalizados;
	}

	/**
	 * * (instalaciones_acsnocentralgasembotellados)
	 */

	@Column(name = "instal_acs_nocentral_gas_embot")
	public String getInstalacionesAcsnocentralgasembotellados() {
		return this.instalacionesAcsnocentralgasembotellados;
	}

	public void setInstalacionesAcsnocentralgasembotellados(String instalacionesAcsnocentralgasembotellados) {
		this.instalacionesAcsnocentralgasembotellados = instalacionesAcsnocentralgasembotellados;
	}

	/**
	 * * (instalaciones_calefaccionnocentralcalefaccionelectricas)
	 */

	@Column(name = "instal_calef_nocent_calef_elec")
	public String getInstalacionesCalefaccionnocentralcalefaccionelectricas() {
		return this.instalacionesCalefaccionnocentralcalefaccionelectricas;
	}

	public void setInstalacionesCalefaccionnocentralcalefaccionelectricas(String instalacionesCalefaccionnocentralcalefaccionelectricas) {
		this.instalacionesCalefaccionnocentralcalefaccionelectricas = instalacionesCalefaccionnocentralcalefaccionelectricas;
	}

	/**
	 * * (instalaciones_calefaccionnocentralgascanalizados)
	 */

	@Column(name = "instal_calef_nocent_gas_canal")
	public String getInstalacionesCalefaccionnocentralgascanalizados() {
		return this.instalacionesCalefaccionnocentralgascanalizados;
	}

	public void setInstalacionesCalefaccionnocentralgascanalizados(String instalacionesCalefaccionnocentralgascanalizados) {
		this.instalacionesCalefaccionnocentralgascanalizados = instalacionesCalefaccionnocentralgascanalizados;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "refrigeracion_colectivo_tiene")
	public Integer getRefrigeracionColectivoTiene() {
		return this.refrigeracionColectivoTiene;
	}

	public void setRefrigeracionColectivoTiene(Integer refrigeracionColectivoTiene) {
		this.refrigeracionColectivoTiene = refrigeracionColectivoTiene;
	}

	/**
	 * * (refrigeracion_nocolectivo_aparatosenfachadas)
	 */

	@Column(name = "refrig_no_colect_apara_enfac")
	public String getRefrigeracionNocolectivoAparatosenfachadas() {
		return this.refrigeracionNocolectivoAparatosenfachadas;
	}

	public void setRefrigeracionNocolectivoAparatosenfachadas(String refrigeracionNocolectivoAparatosenfachadas) {
		this.refrigeracionNocolectivoAparatosenfachadas = refrigeracionNocolectivoAparatosenfachadas;
	}

	/**
	 * * (refrigeracion_nocolectivo_individualporcentaje)
	 */

	@Column(name = "refrig_no_colect_indiv_porcen")
	public String getRefrigeracionNocolectivoIndividualporcentaje() {
		return this.refrigeracionNocolectivoIndividualporcentaje;
	}

	public void setRefrigeracionNocolectivoIndividualporcentaje(String refrigeracionNocolectivoIndividualporcentaje) {
		this.refrigeracionNocolectivoIndividualporcentaje = refrigeracionNocolectivoIndividualporcentaje;
	}

	@Column(name = "refrigeracion_tiene")
	public Integer getRefrigeracionTiene() {
		return this.refrigeracionTiene;
	}

	public void setRefrigeracionTiene(Integer refrigeracionTiene) {
		this.refrigeracionTiene = refrigeracionTiene;
	}

	@Column(name = "saneamiento_bajantes_texto")
	public String getSaneamientoBajantesTexto() {
		return this.saneamientoBajantesTexto;
	}

	public void setSaneamientoBajantesTexto(String saneamientoBajantesTexto) {
		this.saneamientoBajantesTexto = saneamientoBajantesTexto;
	}

	@Column(name = "saneamiento_colectores_texto")
	public String getSaneamientoColectoresTexto() {
		return this.saneamientoColectoresTexto;
	}

	public void setSaneamientoColectoresTexto(String saneamientoColectoresTexto) {
		this.saneamientoColectoresTexto = saneamientoColectoresTexto;
	}

	/**
	 * * (ventilacion_cuartoshumedos_sinventilacion)
	 */

	@Column(name = "vent_cuartoshumedos_sinvent")
	public Integer getVentilacionCuartoshumedosSinventilacion() {
		return this.ventilacionCuartoshumedosSinventilacion;
	}

	public void setVentilacionCuartoshumedosSinventilacion(Integer ventilacionCuartoshumedosSinventilacion) {
		this.ventilacionCuartoshumedosSinventilacion = ventilacionCuartoshumedosSinventilacion;
	}

	/**
	 * * (ventilacion_cuartoshumedos_texto)
	 */

	@Column(name = "vent_cuartoshumedos_texto")
	public String getVentilacionCuartoshumedosTexto() {
		return this.ventilacionCuartoshumedosTexto;
	}

	public void setVentilacionCuartoshumedosTexto(String ventilacionCuartoshumedosTexto) {
		this.ventilacionCuartoshumedosTexto = ventilacionCuartoshumedosTexto;
	}

	@Column(name = "ventilacion_tiene")
	public Integer getVentilacionTiene() {
		return this.ventilacionTiene;
	}

	public void setVentilacionTiene(Integer ventilacionTiene) {
		this.ventilacionTiene = ventilacionTiene;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("claveInforme").append("='").append(getClaveInforme()).append("' ");
		buffer.append("inspeccion").append("='").append(getInspeccion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Instalaciones))
			return false;
		Instalaciones castOther = (Instalaciones) other;

		return (this.getClaveInforme() == castOther.getClaveInforme()) && ((this.getInspeccion() == castOther.getInspeccion()) || (this.getInspeccion() != null && castOther.getInspeccion() != null && this.getInspeccion().equals(castOther.getInspeccion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClaveInforme();
		result = 37 * result + (getInspeccion() == null ? 0 : this.getInspeccion().hashCode());

		return result;
	}

}
