package es.caib.avaedi.common.model;

// Generated 12-sep-2016 10:10:37

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "aed_municipio", uniqueConstraints = { @UniqueConstraint(columnNames = "codigo_catastro"), @UniqueConstraint(columnNames = "codigo_ine"), @UniqueConstraint(columnNames = "nombre") })
public class Municipio extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int clave;
	private Isla isla;
	private String nombre;
	private int codigoIne;
	private int codigoCatastro;
	private String organismoContacto;
	private String direccion;
	private String telefono;
	private String email;
	private String url;

	public Municipio() {
	}

	public Municipio(Isla isla, String nombre, int codigoIne, int codigoCatastro) {
		this.isla = isla;
		this.nombre = nombre;
		this.codigoIne = codigoIne;
		this.codigoCatastro = codigoCatastro;
	}

	public Municipio(Isla isla, String nombre, int codigoIne, int codigoCatastro, String organismoContacto, String direccion, String telefono, String email, String url) {
		this.isla = isla;
		this.nombre = nombre;
		this.codigoIne = codigoIne;
		this.codigoCatastro = codigoCatastro;
		this.organismoContacto = organismoContacto;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.url = url;
	}

	@SequenceGenerator(name = "generator", sequenceName = "AED_MUNICIPIO_SEQ", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "clave", unique = true, nullable = false)
	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_isla", nullable = false)
	public Isla getIsla() {
		return this.isla;
	}

	public void setIsla(Isla isla) {
		this.isla = isla;
	}

	@Column(name = "nombre", unique = true, nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_ine", unique = true, nullable = false)
	public int getCodigoIne() {
		return this.codigoIne;
	}

	public void setCodigoIne(int codigoIne) {
		this.codigoIne = codigoIne;
	}

	@Column(name = "codigo_catastro", unique = true, nullable = false)
	public int getCodigoCatastro() {
		return this.codigoCatastro;
	}

	public void setCodigoCatastro(int codigoCatastro) {
		this.codigoCatastro = codigoCatastro;
	}

	@Column(name = "organismo_contacto")
	public String getOrganismoContacto() {
		return this.organismoContacto;
	}

	public void setOrganismoContacto(String organismoContacto) {
		this.organismoContacto = organismoContacto;
	}

	@Column(name = "direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "telefono", length = 12)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("clave").append("='").append(getClave()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Municipio))
			return false;
		Municipio castOther = (Municipio) other;

		return (this.getClave() == castOther.getClave());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClave();

		return result;
	}

}
