package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Valor generated by hbm2java
 */
@Entity
@Table(name = "aed_valor")
public class Valor extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private ValorId id;
	private Caracteristica caracteristica;
	private String nombreEs;
	private String nombreCa;

	public Valor() {
	}

	public Valor(ValorId id, Caracteristica caracteristica, String nombreEs) {
		this.id = id;
		this.caracteristica = caracteristica;
		this.nombreEs = nombreEs;
	}

	public Valor(ValorId id, Caracteristica caracteristica, String nombreEs, String nombreCa) {
		this.id = id;
		this.caracteristica = caracteristica;
		this.nombreEs = nombreEs;
		this.nombreCa = nombreCa;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "caracteristica", column = @Column(name = "caracteristica", nullable = false)), @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public ValorId getId() {
		return this.id;
	}

	public void setId(ValorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "caracteristica", nullable = false, insertable = false, updatable = false)
	public Caracteristica getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(Caracteristica caracteristica) {
		this.caracteristica = caracteristica;
	}

	@Column(name = "nombre_es", nullable = false)
	public String getNombreEs() {
		return this.nombreEs;
	}

	public void setNombreEs(String nombreEs) {
		this.nombreEs = nombreEs;
	}

	@Column(name = "nombre_ca")
	public String getNombreCa() {
		return this.nombreCa;
	}

	public void setNombreCa(String nombreCa) {
		this.nombreCa = nombreCa;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Valor))
			return false;
		Valor castOther = (Valor) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		return result;
	}

}
