package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.directwebremoting.annotations.DataTransferObject;

import es.caib.avaedi.at4forms.common.basedao.BaseId;
import es.caib.avaedi.at4forms.common.util.FormData2Java;

/**
 * ValorId generated by hbm2java
 */
@Embeddable
@DataTransferObject
public class ValorId extends BaseId implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private String caracteristica;
	private int id;

	public ValorId() {
	}

	public ValorId(String caracteristica, int id) {
		this.caracteristica = caracteristica;
		this.id = id;
	}

	@Column(name = "caracteristica", nullable = false)
	public String getCaracteristica() {
		return this.caracteristica;
	}

	public void setCaracteristica(String caracteristica) {
		this.caracteristica = caracteristica;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(FormData2Java.toString(getCaracteristica()));			
		buffer.append("|"); 
		buffer.append(FormData2Java.toString(getId()));		

		return buffer.toString();
	}

	/**
	 * fromString
	 * 
	 * @return ValorId
	 */
	public static ValorId fromString(String id) {

		ValorId ret = new ValorId();
		String[] codi = id.split("\\|");
		String val;

	    val = codi[0];
	    ret.setCaracteristica(FormData2Java.toString(val) );
	    val = codi[1];
		ret.setId(FormData2Java.toInteger(val));

		return ret;

	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValorId))
			return false;
		ValorId castOther = (ValorId) other;

		return ((this.getCaracteristica() == castOther.getCaracteristica()) || (this.getCaracteristica() != null && castOther.getCaracteristica() != null && this.getCaracteristica().equals(castOther.getCaracteristica()))) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCaracteristica() == null ? 0 : this.getCaracteristica().hashCode());
		result = 37 * result + this.getId();
		return result;
	}

}
