package es.caib.avaedi.common.model;

// Generated 21-sep-2016 17:21:16

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * ValoracionParcial generated by hbm2java
 */
@Entity
@Table(name = "aed_valoracion_parcial")
public class ValoracionParcial extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Inspeccion inspeccion;
	/**
	 * (conservacion_sistemasconstructivos_tipo_id)
	 */
	private Integer conservacionSistemasconstructivosTipoId;
	/**
	 * (conservacion_valoraciones_tipo_id)
	 */
	private Integer conservacionValoracionesTipoId;
	private String plazoFinObras;
	private String plazoInicioObras;

	public ValoracionParcial() {
	}

	public ValoracionParcial(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	public ValoracionParcial(Inspeccion inspeccion, Integer conservacionSistemasconstructivosTipoId, Integer conservacionValoracionesTipoId, String plazoFinObras, String plazoInicioObras) {
		this.inspeccion = inspeccion;
		this.conservacionSistemasconstructivosTipoId = conservacionSistemasconstructivosTipoId;
		this.conservacionValoracionesTipoId = conservacionValoracionesTipoId;
		this.plazoFinObras = plazoFinObras;
		this.plazoInicioObras = plazoInicioObras;
	}

	@SequenceGenerator(name = "generator", sequenceName = "AED_VALORACION_PARCIAL_SEQ", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_informe", nullable = false)
	public Inspeccion getInspeccion() {
		return this.inspeccion;
	}

	public void setInspeccion(Inspeccion inspeccion) {
		this.inspeccion = inspeccion;
	}

	/**
	 * * (conservacion_sistemasconstructivos_tipo_id)
	 */

	@Column(name = "cons_sistemas_construc_tipo_id")
	public Integer getConservacionSistemasconstructivosTipoId() {
		return this.conservacionSistemasconstructivosTipoId;
	}

	public void setConservacionSistemasconstructivosTipoId(Integer conservacionSistemasconstructivosTipoId) {
		this.conservacionSistemasconstructivosTipoId = conservacionSistemasconstructivosTipoId;
	}

	/**
	 * * (conservacion_valoraciones_tipo_id)
	 */

	@Column(name = "cons_valoraciones_tipo_id")
	public Integer getConservacionValoracionesTipoId() {
		return this.conservacionValoracionesTipoId;
	}

	public void setConservacionValoracionesTipoId(Integer conservacionValoracionesTipoId) {
		this.conservacionValoracionesTipoId = conservacionValoracionesTipoId;
	}

	@Column(name = "plazo_fin_obras")
	public String getPlazoFinObras() {
		return this.plazoFinObras;
	}

	public void setPlazoFinObras(String plazoFinObras) {
		this.plazoFinObras = plazoFinObras;
	}

	@Column(name = "plazo_inicio_obras")
	public String getPlazoInicioObras() {
		return this.plazoInicioObras;
	}

	public void setPlazoInicioObras(String plazoInicioObras) {
		this.plazoInicioObras = plazoInicioObras;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValoracionParcial))
			return false;
		ValoracionParcial castOther = (ValoracionParcial) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());

		return result;
	}

}
