package es.caib.avaedi.common.model;

// Generated 12-sep-2016 10:10:37

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import es.caib.avaedi.at4forms.common.basedao.BaseModel;

/**
 * Via generated by hbm2java
 */
@Entity
@Table(name = "aed_via")
public class Via extends BaseModel implements java.io.Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private int clave;
	private TipoVia tipoVia;
	private Municipio municipio;
	private String nombre;
	private int codigoCatastro;

	public Via() {
	}

	public Via(TipoVia tipoVia, Municipio municipio, String nombre, int codigoCatastro) {
		this.tipoVia = tipoVia;
		this.municipio = municipio;
		this.nombre = nombre;
		this.codigoCatastro = codigoCatastro;
	}

	@SequenceGenerator(name = "generator", sequenceName = "AED_VIA_SEQ", allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "generator")
	@Column(name = "clave", unique = true, nullable = false)
	public int getClave() {
		return this.clave;
	}

	public void setClave(int clave) {
		this.clave = clave;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_tipo_via", nullable = false)
	public TipoVia getTipoVia() {
		return this.tipoVia;
	}

	public void setTipoVia(TipoVia tipoVia) {
		this.tipoVia = tipoVia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clave_municipio", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "codigo_catastro", nullable = false)
	public int getCodigoCatastro() {
		return this.codigoCatastro;
	}

	public void setCodigoCatastro(int codigoCatastro) {
		this.codigoCatastro = codigoCatastro;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("clave").append("='").append(getClave()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Via))
			return false;
		Via castOther = (Via) other;

		return (this.getClave() == castOther.getClave());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getClave();

		return result;
	}

}
